.travis.yml
tests/lib/rules/jsx-child-element-spacing.js
tests/lib/rules/jsx-closing-tag-location.js
tests/lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-max-depth.js
tests/lib/rules/no-did-mount-set-state.js
tests/lib/rules/no-did-update-set-state.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/sort-prop-types.js

Eslint 6.0.0-rc.0 is released 10 hours ago. This pr mostly fixes these two kinds of errors:
> A fatal parsing error occurred: Parsing error: sourceType 'module' is not supported when ecmaVersion < 2015. Consider adding `{ ecmaVersion: 2015 }` to the parser options.
> Parsers provided as strings to RuleTester must be absolute paths.

[Tests] make tests pass in eslint@6

---

lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

Fixes #442, fixes #1002, fixes #1257, fixes #1764. (`let {props} = this`)
Fixes #833, fixes #1116 (`const Foo = ({ a }) => <>{ a.b }</>`)
This pr fixed cases where a variable is defined as `props.**.*` For example:
```js
// cache props
let props = this.props;
use(props.a);
// cache a property of props
let {a} = props;
use(a.b)
// param destructuring
const Foo = ({ a }) => <>{ a.b }</>
```
In order to tell weather `foo.a` is a props usage, we need to tell whether `foo` is defined as `props.**.*`. For that purpose a Map is used.

[New] `prop-types`: handle variables defined as props

---

lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

Change reported range to only the identifier

---

lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

In eslint/eslint#9664 eslint added support for the shorthand fragment syntax (`<></>`) as a new node type: `JSXFragment`. The jsx-key rule hasn't been updated to handle it correctly so in some cases where it should report errors it doesn't. Here is an example
```js
[1, 2, 3].map(x => <>{x}</>);
```
This PR fixes this and adds some tests. The error messages could probably be improved and maybe we should add an example to the docs?

fix(jsx-key): handle shorthand fragment syntax

---

lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

[Fix] `prop-types`: fix crash on multiple destructuring

---

lib/util/version.js
tests/util/version.js

The fix to #2276 (commit https://github.com/golopot/eslint-plugin-react/commit/e2e246afd38dad4ee78d45143fe58e7d878c313c) caused a regression only for scenarios where react version cannot be detected. Once the first warning is logged, a second try always results in the raw error being thrown and failure of the lint process.
```
Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.
Error: Error while loading rule 'react/jsx-no-bind': Cannot find module 'react' from 'project-path'
Occurred while linting project-path/.eslintrc.js
at Function.module.exports [as sync] (project-path/node_modules/resolve/lib/sync.js:71:15)
at detectReactVersion …
```

Handle react version detect errors

---

docs/rules/no-unused-prop-types.md

Follow up of #2301. That limitation is fixed in #2301.

[docs] remove outdated docs for `no-unused-prop-types`

---

lib/util/usedPropTypes.js
tests/lib/rules/prop-types.js

Fixes false positive like:
```js
class Foo extends React.Component {
bar() {
this.setState((state, props) => {
function f(_, {aaaaaa}) {}
//             ~~~~~~   'aaaaaa' is missing in props validationeslint(react/prop-types)
// Above is false positive.
});
}
}
```
The function **in**SetStateUpdater really should be **is**SetStateUpdater, so this commit made that change.

[fix] `prop-types`: false positive with setState updater

---

lib/util/propTypes.js
tests/lib/rules/no-unused-prop-types.js

Fix #2358 by recognizing props wrapped in $ReadOnly<>

---

docs/rules/jsx-pascal-case.md
lib/rules/jsx-pascal-case.js
tests/lib/rules/jsx-pascal-case.js

Hello, I hope this finds you well.
My team uses a custom tool for Localization and by convention we've adopted an all-caps snake case for "Translatable Strings" like `<TS_USER_INPUT />` or `<TS_ADD_BUTTON />` to facilitate that.
Our ESLint configs fell out of date as we moved to adopt TypeScript, during which we've written hundreds of these new components. Now that I'm trying to refresh and re-enable them, the `jsx-pascal-case` rule is throwing tons of errors. I like what it's trying to do, though, so I don't want to turn it off. If I had more time I'd try to make `ignore` accept Regex patterns like `/^TS_[A-Z0-9]+$/` but I figure enabling Snake Case with the `allowAllCaps` rule is a simple enough change for most people as it doesn't seem like a breaking change to me.
I hope it meets with …

[Feat]: jsx-pascal-case allowAllCaps allows underscore

---

docs/rules/jsx-key.md
lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

There was a typo in the error messages, which made them confusing (does support instead of does **not** support) and I updated them to give a hint to use the regular fragment syntax. Also updated the docs and tests.
Closes #2365

fix(jsx-key): update error message and docs

---

lib/rules/require-optimization.js
tests/lib/rules/require-optimization.js

Fixes https://github.com/yannickcr/eslint-plugin-react/issues/2374
**Issue**
require-optimization breaks when using arrow function in class components.
**What went wrong**
When we encounter `ArrowFunctionExpression` we blindly calls `markSCUAsDeclared`. In case of functional components it works fine, but in case of class based components, calling `markSCUAsDeclared` sets SCU declared for that component as true.
Added a check, if `ArrowFunctionExpression` is part of a class, then ignore it.

Require Optimization breaks when using arrow function Fix

---

docs/rules/no-deprecated.md
lib/rules/no-deprecated.js
tests/lib/rules/no-deprecated.js

https://github.com/facebook/react/blob/master/CHANGELOG.md#1690-august-8-2019
https://github.com/facebook/react/pull/16103

Deprecate old lifecycles since React 16.9.0

---

lib/rules/jsx-wrap-multilines.js
tests/lib/rules/jsx-wrap-multilines.js

check for `tokenAfter` values to be `;` or `}`
And add spacing for indent after adding `(` or `)`

2390 - fix incorrect formatting in jsx-wrap-multilines

---

lib/rules/jsx-pascal-case.js
tests/lib/rules/jsx-pascal-case.js

Fixes #2394.
$ and _ are valid names for components that are neither upper nor lower
case. This change ensures the pascal case rule only applies to the rest
of the component name (if any).

[jsx-pascal-case] Components can with $ or _

---

lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

use `localCompare` rather than `comparison operator`

2381-fix camelCase error in jsx-sort-props

---

.eslintrc
lib/rules/boolean-prop-naming.js
lib/rules/no-danger-with-children.js
lib/rules/style-prop-object.js
lib/util/Components.js
lib/util/ast.js
lib/util/usedPropTypes.js

* Disable options `requireParamDescription` and `requireReturnDescription`: Personally I find it harmful to add meaningless descriptions to self descriptive params.
* `"requireReturn": false`: This option is a misnomer, actually it means "require `@returns` tag except for void functions". This helps avoid adding lots of `@returns {void}`.

[eslint] disable some options and manually fix `valid-jsdoc`

---

lib/util/Components.js
lib/util/ast.js
tests/lib/rules/destructuring-assignment.js
tests/lib/rules/display-name.js
tests/lib/rules/no-multi-comp.js
tests/lib/rules/no-this-in-sfc.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/require-default-props.js

Fixes #2350
This pr fixes `getParentStatelessComponent` when the current traversed node is like a callback (is a function and is an argument). The function `getParentStatelessComponent` is revised to use a more whitelist-ish approach.
Fixes false positive like:
```js
function Foo(props) {
useEffect(() => {
const { a } = props;
document.title = a;
});
return <p/>;
}
Foo.propTypes = {
a: PropTypes.string,
}
```

[Fix] `no-unused-prop-types`: false positive with callback

---

README.md
docs/rules/jsx-no-useless-fragment.md
index.js
lib/rules/jsx-no-useless-fragment.js
lib/types.d.ts
lib/util/jsx.js
tests/lib/rules/jsx-no-useless-fragment.js

fixes #2042
This rule disallows fragments with less than 2 children.

[New] add `jsx-no-useless-fragment` rule

---

docs/rules/sort-comp.md
lib/rules/sort-comp.js
tests/lib/rules/sort-comp.js

Added option `static-variables` for checking ordering of static variables.
Default order config
```
order: [
'static-variables',
'static-methods',
'lifecycle',
'everything-else',
'render'
]
```

[New]`sort-comp`: add static-variables option

---

lib/rules/jsx-curly-brace-presence.js
lib/rules/jsx-one-expression-per-line.js
lib/rules/no-danger-with-children.js
lib/util/jsx.js
tests/lib/rules/jsx-curly-brace-presence.js

Checks for more than one non-whitespace literal children of `JsxElement` instead of directly checking for `chidlren.length !== 1`.

[fix]`jsx-curly-brace-presence`: report unnecessary curly braces on multline child expressions

---

lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

```javascript
schema: [{
oneOf: [
{
type: 'object',
properties: {
eventHandlerPrefix: {type: 'string'},
eventHandlerPropPrefix: {type: 'string'}
},
additionalProperties: false
}, {
type: 'object',
properties: {
eventHandlerPrefix: {type: 'string'},
eventHandlerPropPrefix: {
type: 'boolean',
enum: [false]
}
},
additionalProperties: false
}, {
type: 'object',
properties: {
eventHandlerPrefix: {
type: 'boolean',
enum: [false]
},
eventHandlerPropPrefix: {type: 'string'}
},
additionalProperties: false
}
]
}]
```

fix[jsx-handler-name]: add option to disable property

---

lib/rules/display-name.js
tests/lib/rules/display-name.js

Wrapping a named function declaration with a React.memo or
React.forwardRef will no longer throw false positive errors.
Check how React devtools exposes the displayNames of components wrapped in memo and forwardRef in https://codesandbox.io/s/awesome-paper-hh0wh?module=App.js
The following no longer raise a linting warning (as react can determine displayNames for them):
```jsx
import React from 'react'
export const ComponentWithMemo = React.memo(function Component({ world }) {
return <div>Hello {world}</div>
})
export const ComponentWithForwardRef = React.forwardRef(function Component({ world }) {
return <div>Hello {world}</div>
})
```
Using either an unnamed Function declaration (`function() {/*...*/}`) or arrow functions continue to raise a warning, as a displayName can not be inferred. …

Fix false positives for display-name

---

lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

Check for single `JSXElement` in child.

[jsx curly brace presence]: fix jsx tags in braces

---

lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

[Fix] `jsx-indent`: Fix false positive when a jsx element is the last statement within a do expression

---

docs/rules/prefer-es6-class.md

I noticed a couple of minor typos while reading through the docs.

Fix typos in prefer-es6-class.md

---

lib/rules/jsx-curly-brace-presence.js

[Addresses changes requested in this issue](https://github.com/yannickcr/eslint-plugin-react/issues/2423).

fix`jsx-curly-brace-presence`: bail out checks when JSXElements are passed as props

---

lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

fixes #2424
Mark `foo` as used when `const {foo: {bar}} = props`.

[Fix] `no-unused-prop-types`: false positive when nested destructuring

---

lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

[Fix] jsx-curly-brace-presence warns incorrectly on trailing whitespace

---

lib/rules/jsx-curly-brace-presence.js
lib/rules/jsx-no-useless-fragment.js
tests/lib/rules/jsx-curly-brace-presence.js

Checks against use-case where white space literal is used to pad around JSX across newlines.

fix(jsx-curly-brace-presence): allow necessary white-space literal

---

docs/rules/jsx-sort-default-props.md
lib/rules/jsx-sort-default-props.js
lib/rules/sort-prop-types.js
lib/util/propTypesSort.js
tests/lib/rules/jsx-sort-default-props.js

There didn't seem to be a reason for not fixing `jsx-sort-default-props` automatically.
Most of this code is copy and pasted from [`sort-prop-types`](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/sort-prop-types.js). It might be good to abstract it somewhere so that it's not duplicated, but I wasn't sure where that should be. If you agree, feel free to point me to where these type of reusable functions usually live, and I'll move them there.
Should fix #2347.

Make jsx-sort-default-props fixable

---

docs/rules/jsx-no-bind.md

This PR is a response to @ljharb's and @draperunner's call for documentation in #2430.
If there's still room for improvement, feel free to review. I'll squash any edits down to a single commit in case you want to rebase this.

[docs] `jsx-no-bind`: add section about React Hooks

---

lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

`jsx-curly-brace-presence` with `never` reports invalid errors in following cases
```
<Foo>{' space before or after '}</Foo>
```
```
<Foo>
{'space after '}
<a>link</a>
{' space before'}
</Foo>
```

[fix] `jsx-curly-brace-presence`: allow trailing spaces in literal

---

lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

The `jsx/no-target-blank` rule does not detect the `_blank` value if written as an expression containing a string (such as `target={'_blank'}`). This PR fixes that.

Find target={'_blank'} expressions

---

docs/rules/jsx-props-no-spreading.md
lib/rules/jsx-props-no-spreading.js
tests/lib/rules/jsx-props-no-spreading.js

PR to resolve: https://github.com/yannickcr/eslint-plugin-react/issues/2439

Allow explicit spread of props

---

lib/rules/no-render-return-value.js
tests/lib/rules/no-render-return-value.js

Addresses #2461 .
With this PR, the `no-render-return-value` plugin will warn for usages like this:
```
this.x = ReactDOM.render(...);
```
or
```
let y;
...
y = ReactDOM.render(...);
```

[Fix] no-render-return-value should warn when used in assignment expression.

---

lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

Cause of error: 
```
<View 
prop={ ' ' }
/>
```
```
TypeError: Cannot read property 'filter' of undefined
Occurred while linting <file>.js:346
at hasAdjacentJsx (.../node_modules/eslint-plugin-react/lib/rules/jsx-curly-brace-presence.js:244:59)
at shouldCheckForUnnecessaryCurly (.../node_modules/eslint-plugin-react/lib/rules/jsx-curly-brace-presence.js:272:49)
at JSXExpressionContainer (.../node_modules/eslint-plugin-react/lib/rules/jsx-curly-brace-presence.js:304:13)
at listeners.(anonymous function).forEach.listener (.../node_modules/eslint/lib/linter/safe-emitter.js:45:58)
at Array.forEach (<anonymous>)
at Object.emit (.../node_modules/eslint/lib/linter/safe-emitter.js:45:38)
at NodeEventGenerator.applySelector (.../node_modules/eslint/lib/linter/node-event-generator.js:253:26)
at …
```

Fix filter of undefined

---

docs/rules/jsx-no-literals.md
lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

The `allowedStrings` option for `jsx-no-literals` is checked against an untrimmed string containing potential spaces and newlines. This is at odds with the [error message shown](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-no-literals.js#L53) and substantially increases the difficulty of managing the `allowedStrings` list.
I propose trimming strings before checking inclusion in `allowedStrings`.
related:
* #2377 
* https://github.com/yannickcr/eslint-plugin-react/pull/2380#issuecomment-537597565

[Fix] `jsx-no-literals`: trim whitespace for `allowedStrings` check

---

lib/rules/prop-types.js
lib/util/ast.js
lib/util/propTypes.js
tests/lib/rules/default-props-match-prop-types.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

This PR aims to support type spread like:
```typescript
// @flow
import * as React from 'react';
type DefaultProps = {|
foo: number,
|}
type Props = {
bar: string,
};
function MyComponent(props: Props) {}
MyComponent.defaultProps = {
foo: 42,
};
```
This PR also fixes https://github.com/yannickcr/eslint-plugin-react/issues/2138

[Fix] Support Flow type spread

---

.eslintrc
lib/rules/jsx-child-element-spacing.js
package.json
tests/lib/rules/default-props-match-prop-types.js
tests/lib/rules/destructuring-assignment.js
tests/lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-no-undef.js
tests/lib/rules/jsx-one-expression-per-line.js
tests/lib/rules/jsx-pascal-case.js
tests/lib/rules/jsx-wrap-multilines.js
tests/lib/rules/no-redundant-should-component-update.js
tests/lib/rules/no-typos.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js
tests/lib/rules/react-in-jsx-scope.js
tests/lib/rules/require-default-props.js

Most of the changes are deleting duplicate test cases.

[eslint] enable eslint-plugin-eslint-plugin

---

lib/rules/no-typos.js
tests/lib/rules/no-typos.js

Previously the report location is property value. Now the report location is property key. This change is scoped to typos for `propTypes`, `defaultProps`, and `ContextTypes`.
```js
class Zoo extends React.Component {
static PROPTYPES = {};
//                   ~~   previous
//       ~~~~~~~~~        now
}
function Foo() {
return <></>;
}
Foo.PROPTYPES = {};
//              ~~   previous
//  ~~~~~~~~~        now
```

[Fix] `no-typos`: improve report location

---

docs/rules/jsx-handler-names.md
lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

@ljharb I'm recreating this as a duplicate of #2470, which I will close. I had done a dopey job of making my commits in there and figured starting over might make life easier for you. Now it has the correct commit title and everything is in a single commit.

[New] `jsx-handler-names`: add `checkLocalVariables` option

---

docs/rules/jsx-handler-names.md
lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

In the `jsx-handler-names` rule, the code requires that the handler being checked is scoped to an object. This means that it will check `onChange={this.wackyHandler}` but because it requires the scoping it won't attempt to check handlers like `onChange={wackyHandler}`. In React.FC components we use this type of handlers all the time, since you can pass a locally-defined function as the handler. This change just removes a test that was causing it to return without the object scoping and then adds tests for a few conditions that it now covers.

No need to require handler names to be scoped to an object

---

docs/rules/jsx-sort-default-props.md
docs/rules/sort-prop-types.md
lib/rules/jsx-sort-default-props.js
lib/rules/sort-prop-types.js
tests/lib/rules/jsx-sort-default-props.js
tests/lib/rules/sort-prop-types.js

This addresses #1940 by disabling the fix option for `sort-prop-types` until a better fix to copy the comments is available.

Disable --fix for sort-prop-types

---

docs/rules/prop-types.md

Updates to the `react/prop-types` documentation to:
- Include 'skipUndeclared' in rule option's snippet.
- Indicate it's an optional boolean.

react/prop-types: Update 'skipUndeclared' in rule options

---

.eslintrc
lib/rules/boolean-prop-naming.js
lib/rules/default-props-match-prop-types.js
lib/rules/display-name.js
lib/rules/jsx-closing-bracket-location.js
lib/rules/jsx-filename-extension.js
lib/rules/jsx-fragments.js
lib/rules/jsx-indent.js
lib/rules/jsx-max-props-per-line.js
lib/rules/jsx-sort-props.js
lib/rules/no-array-index-key.js
lib/rules/no-direct-mutation-state.js
lib/rules/no-multi-comp.js
lib/rules/no-set-state.js
lib/rules/no-unescaped-entities.js
lib/rules/no-unused-prop-types.js
lib/rules/no-unused-state.js
lib/rules/prefer-read-only-props.js
lib/rules/prefer-stateless-function.js
lib/rules/prop-types.js
lib/rules/require-default-props.js
lib/rules/require-optimization.js
lib/rules/require-render-return.js
lib/rules/sort-comp.js
lib/util/Components.js
lib/util/propTypes.js
lib/util/usedPropTypes.js
tests/lib/rules/jsx-closing-bracket-location.js

`object-shorthand` is changed to `always`, otherwise `{'Program:exit'() {}}` is disallowed.

[eslint] fix func-names and change object-shorthand to 'always'

---

docs/rules/jsx-no-target-blank.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

Allows `<a href="foobar" target="_blank" rel="noopener"></a>` if the rule is configured with `allowReferrer` for links where we want the `referrer` for tracking. For rationale see https://github.com/yannickcr/eslint-plugin-react/issues/2054#issuecomment-466477132.
`referrer` is not a specified [link type](https://html.spec.whatwg.org/multipage/links.html#linkTypes) so I'd rather not introduce this magic-word for this rule.
See https://github.com/yannickcr/eslint-plugin-react/issues/776 (can be closed with this change?) and https://github.com/yannickcr/eslint-plugin-react/issues/2054

feat(no-target-blank): Configure noreferrer requirement

---

lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

Fix similar cases #2448 for template literal

[fix] `jsx-curly-brace-presence`: allow trailing spaces in TemplateLiteral

---

CHANGELOG.md
README.md
docs/rules/jsx-no-script-url.md
index.js
lib/rules/jsx-no-script-url.js
tests/lib/rules/jsx-no-script-url.js

**In React 16.9** any URLs starting with `javascript:` [scheme](https://wiki.whatwg.org/wiki/URL_schemes#javascript:_URLs) log a warning. React considers the pattern as a dangerous attack surface, see [details](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html#deprecating-javascript-urls) and **in a future major release** it will throw an error if it encounters a `javascript:` URL.
The rule prevents usage of `javascript:` URLs in JSX.

[New] Add `jsx-no-script-url` to prevent usage of `javascript:` URLs

---

lib/rules/no-typos.js
tests/lib/rules/no-typos.js

I got a compilation error when a component method name is string instead of identifier. The sample code is,
```javascript
class MyComponent {
"special-method-name"() {
// ...
}
}
```
Normally method names should be valid identifiers. However for some reason, I need one of my methods must be in a special form. `Eslint` raises an error, but babel goes well and the code works well in chrome too.
The difference between `Identifier` and `String` method is that the `node.key.type` is `Identifier`/`Literal`. If method name is `Identifier`, the `node.key.name` is the identifier name, however if method name is `String`, we should get the method name by `node.key.value`.

[Fix] Compilation error when method name is string instead of identifier

---

lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

Fixes #1727 
```
4107 passing (7s)
1 failing
1) jsx-curly-brace-presence
valid
<MyComponent prop="asdasd">
<div>
<p>
<span>
{"foo"}
</span>
</p>
</div>
</MyComponent>
:
AssertionError [ERR_ASSERTION]: Should have no errors but had 8: [ { ruleId: 'jsx-curly-brace-presence',
severity: 1,
message: 'Need to wrap this literal in a JSX expression.',
line: 2,
column: 36,
nodeType: 'Literal',
endLine: 3,
endColumn: 11 },
{ ruleId: 'jsx-curly-brace-presence',
severity: 1,
message: 'Need to wrap this literal in a JSX expression.',
line: 3,
column: 16,
nodeType: 'Literal',
endLine: 4,
endColumn: 13 },
{ ruleId: 'jsx-curly-brace-presence',
severity: 1,
message: 'Need to wrap this literal in a JSX expression.',
line: 4,
column: 16,
nodeType: 'Literal',
endLine: 5,
endColumn: 15 },
{ ruleId: …
```

fix[jsx-curly-brace-presence] Fix error related to tag line breaks

---

lib/rules/no-unknown-property.js
lib/util/version.js

Changed `allowTransparency`to `allowtransparency` to account for the following react error:
Warning: React does not recognize the `allowTransparency` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `allowtransparency` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
react - `16.1.1`
react-dom - `16.1.1`

change allowTransparency to allowtransparency

---

tests/lib/rules/no-unused-prop-types.js

Hello! I figured I would open a PR instead of an issue to be able to show the two failing test cases.
The first, should pass because notTarget is used. But it fails with `'target' PropType is defined but prop is never used`. It seems like it takes the destructuring as the props instead of the `props: Props`. Note that this is fine if instead of destructuring `{ target }` I do a simple argument like `infos` (added a test case to show).
```
type Props = {notTarget: string};
class Hello extends React.Component {
props: Props;
onEvent({ target }: { target: Object }) {};
//   onEvent(infos: { target: Object }) {}; passes
render () {
return <div>Hello {this.props.notTarget}</div>;
}
}
```
And on the invalid side, I added a similar test case with two props, one unused, but it fails on the wrong …

Bug Repro: Unused PropTypes detects flow destructuring

---

lib/util/Components.js
tests/lib/rules/prop-types.js

[Fix]: Does not validate for LogicalExpression

---

docs/rules/jsx-first-prop-new-line.md

"Rule Options" section for the "jsx-first-prop-new-line" rule had an erroneous reference to "react/jsx-first-**props-per-line**" (instead of prop-new-line) which didn't work when I tried to change my .eslintrc file.
This fixes the section of the md, correcting said reference.

Fix rule name reference in "Rule Options" section of jsx-first-prop-new-line.md

---

lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

Fixes https://github.com/yannickcr/eslint-plugin-react/issues/2524
The example below was not being handled.
```jsx
<Component>
text
</Component>
```
Fixes https://github.com/yannickcr/eslint-plugin-react/issues/2522
- Ignores HTML entities
- Correctly handle their output

Fix `curly-brace-presence` edge cases

---

docs/rules/no-typos.md
lib/rules/no-typos.js
tests/lib/rules/no-typos.js

This updates the `"no-typos"` rule so that it checks for lifecycle methods that should be static, like `getDerivedStateFromProps`.
Closes https://github.com/yannickcr/eslint-plugin-react/issues/1999

Update no-typos rule to check static lifecycle methods

---

CHANGELOG.md
docs/rules/no-adjacent-inline-elements.md
index.js
lib/rules/no-adjacent-inline-elements.js
tests/lib/rules/no-adjacent-inline-elements.js

FYI, this is my first time writing an eslint rule.
I wrote this because I want to be warned when I have adjacent inline elements without any whitespace, as it affects the way the page looks when unstyled, and may affect the way search engines see the page.
Let me know if you think any changes are needed. If this is something you're interested in merging I'll add the related docs.

Prevent adjacent inline elements not separated by whitespace.

---

CHANGELOG.md
docs/rules/require-default-props.md
lib/rules/require-default-props.js
tests/lib/rules/require-default-props.js

Addresses the discussion from https://github.com/yannickcr/eslint-plugin-react/issues/1009
Specifically from the recommendation at: https://github.com/yannickcr/eslint-plugin-react/issues/1009#issuecomment-516485145 to 'warn less'.
This PR adds an option to `require-default-props` to ignore functional components, as react will soon deprecate defaultProps on functional components https://github.com/reactjs/rfcs/pull/107.

feat(require-default-props): add option to ignore functional components

---

lib/types.d.ts
lib/util/propTypes.js

`UnionTypeDefinition.children` had a inconvenient type `unknown[]|true`. It turned out `children === true` never happens, so the related codes can be removed.

[Refactor]: remove unused codes in util/propTypes

---

docs/rules/no-render-return-value.md

Small fix to change title from `React.render` to `ReactDOM.render` in `react/no-render-return-value` rule.

Fix title for "no-render-return-value" rule docs

---

lib/rules/no-unused-state.js
lib/util/ast.js
lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-state.js

Fixes #2517:
* adds an ast util for unwrapping TS `as` assertion.
* fixes false positives for `no-unused-prop-types`
* fixes false positives for `no-unused-state`
I tried to reuse as much of the existing solution as possible by handling cases where the `as` expression might occur.
I'm wondering tho if it would be better to just process the code with anything that would remove TS-specific syntax (type annotations, `as` assertions, etc.) and then parse the result so the entire logic could be reused. Just thinking out loud 😅

[Fix]: false positives for `no-unused-...` when using TS type assertions

---

lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

Previously this would be an error, since the rel wasn't read:
<a target={"_blank"} href={"//"} rel={"noopener noreferrer"}>
Now this works, so you can enable this rule together with
`jsx-curly-brace-presence`.
Fixes #2508.

[Fix] `jsx-no-target-blank`: allow rel to be an expression

---

.editorconfig
lib/rules/jsx-props-no-spreading.js
tests/lib/rules/jsx-props-no-spreading.js

Sub-components support for jsx-props-no-spreading

---

docs/rules/jsx-props-no-spreading.md

Add `enabled` option to use this option.

Fix typo `jsx-props-no-spreading` document 

---

.travis.yml
README.md
lib/rules/void-dom-elements-no-children.js
markdown.config.js
package.json

To make it easier to find rules.
It will be appreciated if you review it. 😊

[Docs] Re-sort all rules alphabetically

---

lib/rules/jsx-indent.js
package.json
tests/lib/rules/jsx-indent.js

Fixes #2467, Fixes #2484, Fixes #1136 
This PR fixes the problem of does not check `jsx-indent` for `JSXText`.
`JSXText` Node is different from other formats.
e.g. The following code.  `JSXText`'s node.value returns `\n    text\n    text\n    `.
```js
const f = () => (
<div>
text
text
</div>
);
```
<details><summary>changes</summary>
1. add handler for JSXText Node
https://github.com/yannickcr/eslint-plugin-react/blob/0076cb09abfed7a3777102359efb5f39dee2e01e/lib/rules/jsx-indent.js#L406-L412
2. check JSXText Indent
https://github.com/yannickcr/eslint-plugin-react/blob/0076cb09abfed7a3777102359efb5f39dee2e01e/lib/rules/jsx-indent.js#L304-L341
3. add the fix for JSXText
https://github.com/yannickcr/eslint-plugin-react/blob/0076cb09abfed7a3777102359efb5f39dee2e01e/lib/rules/jsx-indent.js#L100 …

[Fix] `jsx-indent`: Does not check indents for JSXText

---

lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

[Fix]`jsx-indent`: don't check literals not within JSX

---

lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js

Fix crash on TSEmptyBodyFunctionExpression AST node

---

README.md
lib/rules/jsx-curly-newline.js

Everywhere else it starts with capital letter

Small visual inconsistency in README.md

---

lib/rules/jsx-pascal-case.js
package.json
tests/lib/rules/jsx-pascal-case.js

Fixes #1654 
Uses the `\p` Unicode character property matcher, and the tests run fine. 👍
Note
---
I pulled in the `xregexp` package to definitely support `\p`. The tests _does_ seem to work without it, at least it Works On My Machine™, but `eslint`, or something at least, doesn't seem to like it? 🤔

[New] `jsx-pascal-case`: Support unicode characters

---

docs/rules/self-closing-comp.md
lib/rules/self-closing-comp.js
tests/lib/rules/self-closing-comp.js

[Compound components ](https://blog.bitsrc.io/understanding-compound-components-in-react-23c4b84535b5) syntax was not considered in `self-closing-comp` rule. This PR include this syntax in the rule by adding `JSXMemberExpression` as valid components to be checked.

[Fix] `self-closing-comp`: consider JSXMemberExpression as component too

---

docs/rules/style-prop-object.md
lib/rules/style-prop-object.js
tests/lib/rules/style-prop-object.js

Fixes https://github.com/yannickcr/eslint-plugin-react/issues/1813

[New] `style-prop-object`: Add `allow` option

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

Fixes #2287
This change seems rather trivial, which made me wonder if there was ever a reason why it was not done this way? 🤔 
The code used to report only on `prop.node` value, then it would report like this:
However, this logic was changed in this commit to report only on the `node.value` instead. But this commit doesn't really explain why and seems mostly about another rule instead. I'm thinking that it may have been done by accident?
https://github.com/yannickcr/eslint-plugin-react/commit/2e4f91afdc8a089936a2ff49e6b4c83cccb3432a
So now I question whether we should report back to the full `node` or change it to `node.key`.
Otherwise, I tried it out on a local project and seemed to work fine, all tests also continue to pass once the column context values were adjusted.
Before:
After:

Change the reporting for no-unused-prop-types

---

package.json
tests/lib/rules/no-unescaped-entities.js

CI is failing after the release of acorn-jsx@5.2.0, 4 days ago, which is a dependency of espree. https://github.com/acornjs/acorn-jsx/releases/tag/5.2.0. That release introduced a breaking change that forbids `>` and `}` in JSXText. Therefore codes like `<p>></p>` became a parsing error.
This PR removed test cases that became parsing error after acorn-jsx@5.2.0.
An expensive alternative is to setup tests for both acorn-jsx < 5.2.0 and > 5.2.0. But that is expensive.

[tests] delete test cases that became parsing error after acorn-jsx@5.2.0

---

lib/rules/prefer-stateless-function.js
tests/lib/rules/prefer-stateless-function.js

fixes #2187
Typescript allows constructor without body, like
```ts
class Foo {
constructor(a)
}
```
This PR adds a null check to avoid crash.

[fix] `prefer-stateless-function`: avoid crash on ts empty constructor

---

lib/util/Components.js
tests/lib/rules/display-name.js

This pr adds a null check, to avoid a crash that happens when using `React.memo` plus a return statement without an argument. Like
```js
import React from 'react';
const Hello = React.memo(function Hello() {
return;
});
```

[fix] `displayName`: avoid a crash when using React.memo

---

docs/rules/jsx-no-literals.md
lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

- Update Tests Accordingly
- Update Rule Readme file
- Rule shouldn't allow strings in empty tags

[New]: `jsx-no-literals`: add `ignoreProps` option to ignore props validation

---

package.json

`semver` is listed in `dependencies`, but only seems to be used in this test and not in the plugin itself:
https://github.com/yannickcr/eslint-plugin-react/blob/e231f44c38d28878039edeb43e009b153614ca0a/tests/lib/rules/no-unescaped-entities.js#L12
This PR moves it to `devDependencies` so that downstream projects don't have to include an unnecessary dependency.

[deps] Move "semver" to devDependencies

---

lib/rules/jsx-no-comment-textnodes.js
package.json
tests/helpers/parsers.js
tests/lib/rules/jsx-no-comment-textnodes.js

Fix no-comment-text-nodes for @typescript-eslint/parser

---

lib/util/ast.js
tests/lib/rules/prop-types.js

[Fix] `prop-types`: avoid crash when spreading any type

---

tests/lib/rules/display-name.js

Closes #2445.
#2445 was already fixed by #2399. This pr just adds the missing test case.

[tests] `displayName`: add a test case

---

docs/rules/no-this-in-sfc.md
lib/rules/no-this-in-sfc.js
tests/lib/rules/no-this-in-sfc.js

I had a "Who's on First?" moment looking at `no-this-in-sfc`'s error message: `Stateless functional components should not use this'.
In this case this message caused this hacker to seek the referent of "this" in this rule (that is, `no-this-in-sfc`) which was not a this or a that in general, or this line qua this, but then saw that the "this" in this line of the `no-this-in-sfc` rule that the linter was telling me to not this in an sfc was in fact the `this` on this line of this function, because the `this` of this kind of component isn't used the way the `this` of that other kind of component is, like to sometimes set the state of its `state` and such, which, to state the obvious, is the sine qua non of a stateless functional component, as a stateless functional component is a functional …

(cosmetic) Quote this as `this` in the no-this-in-sfc rule

---

docs/rules/button-has-type.md
lib/rules/button-has-type.js
tests/lib/rules/button-has-type.js

[Fix] `button-has-type`: improve message when non-static value is used

---

README.md
docs/rules/jsx-no-target-blank.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

Fixes #2022 
Just a minor change to only require `no-referrer` rather than both `noreferrer noopener`.

Updating no-target-blank logic to only require no-referrer

---

README.md

Added the `rules-of-hooks` plugin to the Other useful plugins-section in the README.md as it's pretty much recommended for those who use hooks

Add Rules of Hooks to Other useful plugins section

---

lib/rules/jsx-pascal-case.js
lib/util/jsx.js
tests/lib/rules/jsx-pascal-case.js

When testing whether a component is a DOM element, we select the first portion of the name up until `:` or `.`, then tests for `^[a-z]|-`.
There are many problems with this:
- It doesn't test the name but the namespace, which I don't think is what was intended
- ~In effect it only tests the first character; not the full tag~ EDIT: [Irrelevant](url)
- It allows for tags that start with `-` (Related to [this](https://github.com/babel/babel/issues/7163))
- In JSX it is not possible to be a DOM element and be in a namespace as well
- `:` is not an allowed character
It may be a dangerous change, but ~the tests are still passing and~ locally it is "more correct".
UPDATE: So this triggers a "chain reaction" in `jsx-pascal-case`, which if followed solves  #1334.

Do not consider namespaces when checking for DOM

---

docs/rules/forbid-component-props.md
docs/rules/forbid-dom-props.md
lib/rules/forbid-component-props.js
lib/rules/forbid-dom-props.js
tests/lib/rules/forbid-component-props.js
tests/lib/rules/forbid-dom-props.js

Hi team! When considering using the forbid-component-props and forbid-dom-props rules, an early topic of discussion was whether or not it would be possible to provide a custom error message. This gives the user a chance to better explain _why_ the prop is forbidden, and possible offer an alternative, or best practice, etc.
This PR aims to add custom messaging functionality to both rules of these rules. Let me know if such an enhancement is something you would consider adding and I'm happy to make improvements on it and take any suggestions! Thanks!

Allow a custom message with forbid props

---

lib/rules/no-unused-state.js
tests/helpers/parsers.js
tests/lib/rules/jsx-no-comment-textnodes.js
tests/lib/rules/no-unused-state.js

[Fix] `no-unused-state`: handle optional chaining

---

lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

For [#2594](https://github.com/yannickcr/eslint-plugin-react/issues/2594)

[Fix] `jsx-key`: support optional chaining

---

docs/rules/boolean-prop-naming.md
docs/rules/default-props-match-prop-types.md
docs/rules/no-unused-prop-types.md
docs/rules/prop-types.md
docs/rules/require-default-props.md
docs/rules/sort-prop-types.md

In a separate commit I cleaned up examples to be a bit more modern, preferring function components, so they are easier to read, then documented that this rule isn't only for `PropTypes`, but that it accepts static types, too.

Document that rules dealing with prop types recognize static types, too

---

lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

remove the use  of `localCompare`

[Fix] `jsx-sort-props`: only use localeCompare when case is ignored

---

lib/rules/jsx-pascal-case.js
package.json

Reimplemented the logic of extended regular expressions with functions in the `jsx-pascal-case` rule in order to remove the dependency on `xregexp`. This reduced the size of `node_modules` on my machine from 150MB to 140MB.
----
The dependency on `xregexp` was introduced in #2557 to support the full Unicode range. More specifically, it allows for using the `\p{Lu}` and `\p{Ll}` character classes, which are defined as such:
> \p{Ll} or \p{Lowercase_Letter}: a lowercase letter that has an uppercase variant.
> \p{Lu} or \p{Uppercase_Letter}: an uppercase letter that has a lowercase variant.
([Source](http://www.regular-expressions.info/unicode.html))
However, this logic can be implemented in JS by the respective expressions:
- `char === char.toLowerCase() && char.toUpperCase() !== …

Remove dependency on xregexp

---

lib/util/propTypes.js
package.json
tests/lib/rules/no-unused-prop-types.js

Hi there,
This is a first draft to solve https://github.com/yannickcr/eslint-plugin-react/issues/2569
I would be thankful if someone involved in this rule creation could give feedback about edge cases to be handled (spread operator, etc.). I am afraid to have forgotten some...
Thank you !

[Fix] no-unused-prop-types with typescript eslint parser

---

lib/rules/forbid-dom-props.js
lib/rules/function-component-definition.js

Small typos in rule schema definitions I discovered testing my VSCode extension to manage .eslintrc files.

[Fix] `forbid-dom-props`, `function-component-definition`: fix schema typos

---

lib/util/pragma.js
package.json
tests/util/pragma.js

Fixes #2642.
This PR relaxes the JSX pragma detection slightly.
Previously, only pragmas at the beginning of docstring comments were recognised. But pragmas can occur anywhere in any block comment (not just docstring comments). This PR fixes the regexp that recognises pragmas.

Relax JSX pragma regexp

---

lib/util/version.js
tests/util/version.js

I've been timing and profiling ESLint runs at Airbnb and noticed that
react/no-unknown-property is particularly slow for us when using the
"detect" setting for React version.
When running ESLint using TIMING=1 on a directory that contains about
500 files to be linted in it, react/no-unknown-property shows up as
taking about 1700ms.
Looking at the callstacks in the profiler, it seems that when this rule
calls getStandardName for every JSXAttribute here, it will actually do
all of the work to detect the React version every time to determine the
correct set of DOM property names. Since there may be a lot of
JSXAttribute nodes in a codebase, this adds up to quite a bit of work.
By specifying the react version in our ESLint config, the
no-unkown-property rule drops out of the top 10 slowest …

Cache detected React version

---

tests/lib/rules/no-typos.js

It seems CI is failing.
```
4345 passing (12s)
1 failing
1) no-typos
invalid
import 'react';
class Component extends React.Component {};
:
AssertionError [ERR_ASSERTION]: Invalid cases must have at least one error
at testInvalidTemplate (node_modules/eslint/lib/rule-tester/rule-tester.js:648:24)
at Context.RuleTester.it (node_modules/eslint/lib/rule-tester/rule-tester.js:883:25)
at processImmediate (internal/timers.js:443:21)
```
I moved a valid case into a valid section.

[Tests] `no-typos`:  move a valid case into valid section

---

lib/rules/forbid-prop-types.js
tests/lib/rules/forbid-prop-types.js

In this case the type of the callee was 'Identifier' (vs 'MemberExpression'), which seems to makes sense because it is not being called as a property on PropTypes object.  I looked back at the history to see if maybe that check was added for a particular reason but it seems like it has been there from the beginning:
https://github.com/yannickcr/eslint-plugin-react/commit/00f716a990c247e844a5dba85220d3af7d6e3693
I can't think of any reason why it would be needed but if someone who knows better than me does, I'd be happy to hear it.

Forbid objectof 2662

---

lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js

Handle optional chaining in usedPropTypes.
Before:
```
const Hello = props => {
const firstname = props?.name;
};
Hello.propTypes = {
name: PropTypes.string.isRequired, <<< 'name' PropType is defined but prop is never used eslint(react/no-unused-prop-types)
};
```
After this pr the error should be resolved.

[Fix]`no-unused-prop-types`:handle optional chaining

---

lib/util/propTypes.js
lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

This pr is trying to fix #2686 and #2689 .
To fix #2686 :
I add both string and number Literal type support to interface.
And to fix #2689 :
I add a validation for FunctionComponent in propTypes.js function markAnnotatedFunctionArgumentsAsDeclared which name isJSXFunctionComponent.It can check whether function is return JSXElement or not.
AFAIK only function that return JSXElement need propTypes validation.
Thanks you so much for your code review!

[Fix]:`no-unused-prop-types`: typescript interface support literal type and only FunctionComponent should have propTypes validation

---

lib/util/propTypes.js
tests/lib/rules/prop-types.js

Use the variable value in cases where the type is given by a variable. Example:
```jsx
const firstType = PropTypes.shape({
id: PropTypes.number,
});
class ComponentX extends React.Component {
static propTypes = {
first: firstType.isRequired, // resolve to `first: PropTypes.shape({ id: PropTypes.number }).isRequired`
};
render() {
return (
<div>
{/*Correctly validates that first.name is not defined in propTypes.*/}
<div>Counter = {this.props.first.name}</div>
</div>
);
}
}
```
Fixes #2236

[Fix]: use variable value in prop type field defined by a variable

---

lib/util/Components.js
tests/lib/rules/function-component-definition.js
tests/lib/rules/prop-types.js

As stated by @ljharb in https://github.com/yannickcr/eslint-plugin-react/issues/2554#issuecomment-596631942, functions starting with a lowercase letter are not components.
This PR adds a check for the capitalization of the first letter in functional components detection.
With this change all the reported cases in the issue work properly.
Fixes #2554. Fixes #2495. Fixes #2607. Fixes #2352

[Fix]: Functional components first letter capitalization check

---

lib/util/propTypes.js
tests/lib/rules/prop-types.js

This pr is related to https://github.com/yannickcr/eslint-plugin-react/issues/2654#issuecomment-652868302
Previous isJSXFunctionComponent did not handle nullable component correctly.
So I replaced it with utils.isReturningJSXOrNull.
Sorry for the issue.
Fixes #2705.

[Fix]:`prop-types`: handle component returning null

---

lib/util/Components.js
lib/util/variable.js
tests/lib/rules/no-multi-comp.js
tests/util/variable.js

Improve `isDestructuredFromPragmaImport` algorithm to more accurately recognize variables coming from the pragma.
Fixes #2164

[Fix]: improve algorithm to check if a variable is coming from the pragma

---

lib/util/Components.js
tests/lib/rules/prop-types.js

For 7.20.4 version of `eslint-plugin-react` I receive TypeError when I lint [this file](https://github.com/wKich/creevey/blob/master/src/server/master/index.ts#L37). I added additional check for anonymous functions where error was raised.

[Fix] `prop-types`: handle anonymous functions

---

lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

[Fix] `jsx-curly-brace-presence`: disable disallowed JSX text chars check in props

---

lib/rules/no-access-state-in-setstate.js
tests/lib/rules/no-access-state-in-setstate.js

[Fix] `no-access-state-in-setstate`: add check for class component

---

lib/util/Components.js
tests/lib/rules/no-this-in-sfc.js

As reported in issue #2010 comment https://github.com/yannickcr/eslint-plugin-react/issues/2010#issuecomment-545458545 there is an inconsistency in the detection of components returned from functions with and without return statements.
Since arrow functions can do a direct return without return statement, this PR adds ArrowFunctionExpression to the list of allowed position for component.
Also adds a test for #2010 to show it is fixed.
Closes #2010.

[Fix] `no-this-in-sfc`/component detection: add arrow function to list of allowed position for component

---

lib/util/ast.js
lib/util/propTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

Fixes #2654. Fixes #2719. Fixes #2703.
Now support the following typescript syntax for prop validation,
but extension only support with parser @typescript-eslint/parser since typescript-eslint-parser is deprecated.
1. interface extension.
```
interface GenericProps {
a: () => void;
}
interface ImplementationProps extends GenericProps {
b: () => void;
}
export const Implementation: FC<ImplementationProps> = ({
a,
b,
}: ImplementationProps) => <div />;
```
2. interface extension with ReturnType<T>
```
const mapStateToProps = (state) => ({
books: state.books,
});
interface BooksTable extends ReturnType<typeof mapStateToProps> {
username: string;
}
const App = (props: BooksTable) => {
props.books();
return (
<div>
<span>{props.username}</span>
</div>
);
};
```
ReturnType can only accept one …

[Fix] `prop-types`: Support typescript props interface extension and TSTypeAliasDeclaration

---

lib/rules/no-find-dom-node.js
tests/lib/rules/no-find-dom-node.js

The error message for `no-find-dom-node` wasn't very informative, which makes it less likely that people will respect the rule instead of just disabling it. This PR adds a more informative message.

[Fix] Improve error message for no-find-dom-node

---

lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

Checks if props string is included in `allowedStrings` option
Fixes #2720.

[Fix] jsx-no-literals with allowStrings doesn't work in props

---

lib/rules/jsx-no-useless-fragment.js
tests/lib/rules/jsx-no-useless-fragment.js

[Fix] `jsx-no-useless-fragment`: accept fragments with call expressions

---

CHANGELOG.md
docs/rules/button-has-type.md
lib/rules/button-has-type.js
tests/lib/rules/button-has-type.js

This adds support for trivial ternary expressions to `button-has-type` rule:
```jsx
<button type={condition ? 'button' : 'submit'} />
```
See https://github.com/yannickcr/eslint-plugin-react/issues/1555#issuecomment-362262866

button-has-type: support trivial ternary expressions

---

lib/util/propTypes.js
tests/lib/rules/prop-types.js

[New] `prop-types`: add support for `PropTypes.exact` 

---

docs/rules/jsx-props-no-multi-spaces.md
lib/rules/jsx-props-no-multi-spaces.js
tests/lib/rules/jsx-props-no-multi-spaces.js

[Fix] `jsx-props-no-multi-spaces`: Show error in multi-line props

---

docs/rules/jsx-filename-extension.md
lib/rules/jsx-filename-extension.js
tests/lib/rules/jsx-filename-extension.js

This option allows users to disallow the filename extension in files not using JSX syntax.
Closes #2742

[New] `jsx-filename-extension` add  "allow" option with "as-needed"

---

.eslintrc
markdown.config.js

In #2763 @dylanOshima got a cryptic CI error that only manifested in Node 4. It took a bunch of time to get the environment setup correctly to trigger that error correctly. It seems like the kind of thing that could be caught earlier with a lint rule, so I thought I'd add one.
Test plan:
Check out an early commit of #2763 and see this error:

Disallow object destructuring via ESLint since we support Node v4

---

README.md
lib/rules/jsx-uses-react.js
tests/lib/rules/jsx-uses-react.js

This allows to use the following syntax:
```jsx
import { createElement, Fragment } from 'react';
function Component {
return <></>;
}
```
Or more common in Preact:
```jsx
import { Fragment, h } from 'preact';
function Component {
return <></>;
}
```
The `react.fragment` setting already existed for other rules, but it was
undocumented.

[Fix] `jsx-uses-react`: mark fragment variables as used

---

CHANGELOG.md
lib/rules/function-component-definition.js
tests/lib/rules/function-component-definition.js

function-component-definition: ignore properties

---

CHANGELOG.md
docs/rules/jsx-handler-names.md
lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

Add `checkInlineFunction` option for `jsx-handler-names` rule
PR resolve #2586

[New] `jsx-handler-names`: add `checkInlineFunction` option

---

CHANGELOG.md
lib/rules/forbid-component-props.js
tests/lib/rules/forbid-component-props.js

I don't really know what I am doing. I have just looked at the structure of the `node`, added a test and updated code so the tests pass. 
Fixes #2766.

[Fix] `forbid-component-props`: Implemented support for "namespaced" components.

---

CHANGELOG.md
lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

[Fix] `jsx-handler-names`: handle whitespace

---

CHANGELOG.md
docs/rules/prop-types.md
lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Detect TypeScript types for destructured default prop values

---

CHANGELOG.md
lib/rules/jsx-closing-bracket-location.js
tests/lib/rules/jsx-closing-bracket-location.js

To differentiate between tab and space, modified `lib/rules/jsx-closing-bracket-location` 
and added test case in `tests/lib/rules/jsx-closing-bracket-location`.
PR fixes #756

[Fix] `jsx-closing-bracket-location`: In `tag-aligned`, made a distinction between tabs and spaces

---

CHANGELOG.md
docs/rules/jsx-no-literals.md
lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

[New] `jsx-no-literals`: add `noAttributeStrings` option

---

lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

Updated unit test and EVENT_HANDLER_REGEX regex.

Issue #1686 - jsx-handler-names: false positive when handler name begins with number

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/prop-types.js

Resolves #2800. Implements `isReturnsSequentialJSX()` and uses it in `isReturningJSX()` (in conjunction with `isReturnsConditionalJSX()` and `isReturnsLogicalJSX()`).

[Fix] Detect JSX returned by sequential expression

---

CHANGELOG.md
tests/lib/rules/jsx-one-expression-per-line.js

This issue has been resolved, added test to confirm that the bug has been fixed.
Closes #1835.

[closes] jsx-one-expression-per-line fix option inserts blank lines 

---

CHANGELOG.md
lib/rules/jsx-props-no-multi-spaces.js
tests/lib/rules/jsx-props-no-multi-spaces.js

[Fix] "Expected no line gap between" false positive

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

I think this is ready now. I checked my project with this rule and it didn't break anything :-)
I wasn't sure if this rule should also check completely unknown attributes. My view is that it should, but I didn't do it in this patch.
With this patch the rule will probably find new errors in existing code, so it should probably be versioned in a new minor or major version.
Tell me what you think!
(pretest fails but this seems to happen on master too?)

Fix no-unknown-property: check attributes with any input case

---

CHANGELOG.md
lib/util/ast.js
lib/util/propTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

This pr fixes: #2795.
This pr handle CallExpression which come from two places.
1. From ReturnType function body:
For example:
```
const mapDispatchToProps = (dispatch: ThunkDispatch<State, null, Action>) => 
bindActionCreators<{props1: ()=>void,props2: ()=>string}>(
{ prop1: importedAction, prop2: anotherImportedAction },
dispatch,
)
```
2. From RerturnType function return object spread properties:
For example:
```
const mapDispatchToProps = (dispatch: ThunkDispatch<State, null, Action>) => ({
...bindActionCreators<{prop1: ()=>void,prop2: ()=>string}>(
{ prop1: importedAction, prop2: anotherImportedAction },
dispatch,
),
})
```
If user give us typeParameters of CallExpression, eslint will do prop-types check.
If user did not give us, eslint will ignore the prop-types check since we …

[Fix] `prop-types`: Should handle CallExpression in ReturnType

---

CHANGELOG.md
lib/rules/prop-types.js
tests/lib/rules/prop-types.js

This pr fixes: #2804 .
Function parameter will have `RestElement` which do not have property value.
It will cause undefined property error.

[Fix] `prop-types`: handle RestElement in destructured param

---

CHANGELOG.md
lib/rules/prop-types.js
tests/lib/rules/prop-types.js

This pr fixes: #2804, #2805.
Function parameter will have `ExperimentalRestProperty`(JSX) and which do not have property value.
It will cause undefined property error.

[Fix]: fix `prop-types` Cannot read property 'type' of undefined error when destructured param

---

CHANGELOG.md
lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

Adding the type `never` is enforcing that the prop types is actually never set, so it's redundant to warn about this prop type not being used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/yannickcr/eslint-plugin-react/2815)

[Fix] `no-unused-prop-types`: Silence false positive on `never` type in TS

---

CHANGELOG.md
lib/rules/jsx-indent-props.js
tests/lib/rules/jsx-indent-props.js

To apply indentation if there is an operator in front of the line above,
modified `lib/rules/jsx-indent-props`, and added test case in `tests/lib/rules/jsx-indent-props`.
PR fixes #647

[Fix] `jsx-indent-props` : Apply indentation when operator is used in front of the upper line

---

CHANGELOG.md
tests/lib/rules/jsx-indent-props.js

This problem seems to be the same as https://github.com/yannickcr/eslint-plugin-react/issues/647 where I sent pr, 
so I added a test case in `tests/lib/rules/jsx-indent-props` to make sure it passes all the test cases.
PR fixes #1187

[Tests] `jsx-indent-props` : Apply indentation when used expression

---

CHANGELOG.md
lib/rules/jsx-indent-props.js
tests/lib/rules/jsx-indent-props.js

Since there were cases where indentation was not properly applied after https://github.com/yannickcr/eslint-plugin-react/pull/2808, 
modified `lib/rules/jsx-indent-props`, and added test case in `tests/lib/rules/jsx-indent-props`.

[Fix] `jsx-indent-props` : Apply indentation when using operator

---

tests/lib/rules/jsx-indent-props.js

This adds a failing test reproducing a regression described in https://github.com/yannickcr/eslint-plugin-react/issues/1187#issuecomment-706646097

Add a failing test for js-indent props

---

CHANGELOG.md
lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

Hi,
This fixes the issue presented in #2832

[Fix] `jsx-handler-names`: Skip inline handlers when checkInlineFunction=false. Fixes #2832

---

CHANGELOG.md
docs/rules/jsx-key.md
lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

fix #2830 
related: https://github.com/facebook/react/issues/20031#issuecomment-710346866

[New]: `jsx-key`: added `checkKeyMustBeforeSpread` option for new jsx transform

---

CHANGELOG.md
README.md
docs/rules/jsx-newline.md
index.js
lib/rules/jsx-newline.js
tests/lib/rules/jsx-newline.js

[New]`jsx-newline`: Enforce a new line after jsx elements and expressions

---

CHANGELOG.md
README.md
docs/rules/jsx-no-constructed-context-values.md
index.js
lib/rules/jsx-no-constructed-context-values.js
tests/lib/rules/jsx-no-constructed-context-values.js

Adds a new rule that checks if the value prop passed to a Context Provider will cause needless rerenders. A common example is inline object declaration such as:
```js
<Context.Provider value={{foo: 'bar'}}>
...
</Context.Provider>
```
which will cause the Context to rerender every time this code is run because the object is defined with a new reference. This is true for many other types of JS objects and variables.
This can lead to performance hits since not only will this rerender all the children of a context, it will also update all consumers of the value. The search React does to search the tree can also be very expensive. Some other instances that this rule covers are: array declarations, function declarations (i.e. arrow functions), or new class object instantiates.
For inline …

[New] `jsx-no-constructed-context-values`: add rule for unstable context values

---

CHANGELOG.md
lib/util/Components.js
lib/util/propTypes.js
tests/lib/rules/prop-types.js

[Fix] `prop-types`: function in class that returns a component causes false warning in typescript

---

CHANGELOG.md
lib/rules/prop-types.js
tests/lib/rules/prop-types.js

[Fix] `prop-types`: default argument does not count as props-types declaration

---

CHANGELOG.md
lib/rules/jsx-props-no-multi-spaces.js
tests/lib/rules/jsx-props-no-multi-spaces.js

[Fix] `jsx-props-no-multi-spaces`: fix a false positive for beside comments

---

CHANGELOG.md
docs/rules/jsx-no-target-blank.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

Resolves #2827
I've changed the rule to warn on the `JSXOpeningElement` instead of a specific attribute. There is a technical reason and an architectural reason:
- when disabling `trustSpreadAttributes`, we could end up with multiple warnings for the same problem e.g. once on a `target="_blank"` attribute and once on `{...myUnsafeObject}` spread attribute
- it makes more sense (to me) that the rule warns on the element instead of a specific attribute since the problem is not necessarily due to any specific attribute, but the combination and order of the attributes on the element
Commit message
---
```
Add trustSpreadAttributes for jsx-no-target-blank
Defaults to true. When disabled, treats spread attributes as dangerous
unless explicitly overriden e.g. the following is safe:
<a …
```

[New] `jsx-no-target-blank`: Add `warnOnSpreadAttributes` option

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

Fixes #2850.
The option `skipShapeProps` was only applied to `PropTypes.shape`, this pr make the option apply to `PropTypes.exact` as well.
Props usages like `props.a.map({b} => use(b))` are hard to handle. Currently `PropTypes.shape` has the same bug under the option `skipShapeProps: false`. People do not complain about it because most people use `skipShapeProps: true`.
The bug has two parts:
1. `skipShapeProps` should applies to `PropTypes.exact`.
2. Props usages like `props.a.map({b} => use(b))` should be handled.
This pr only fixes 1.

[Fix] `no-unused-prop-types`: apply `skipShapeProps` to exact types

---

lib/rules/no-adjacent-inline-elements.js
lib/rules/no-danger-with-children.js
lib/rules/style-prop-object.js

The category for the `react/no-danger-with-children` rule is missing a category. This adds the category as `'Possible Errors'`.

[Fix] `no-danger-with-children`: add category

---

lib/rules/no-adjacent-inline-elements.js
lib/rules/no-danger-with-children.js
lib/rules/style-prop-object.js

The category for the `react/style-prop-object` rule is missing a category. This adds the category as `'Possible Errors'`.

[Fix] `style-prop-object`: add category

---

lib/rules/no-adjacent-inline-elements.js
lib/rules/no-danger-with-children.js
lib/rules/style-prop-object.js

The url for the `react/style-prop-object` rule is missing. This adds the correct url using the `docsUrl` util.

[Fix] `no-adjacent-inline-elements`: add url

---

CHANGELOG.md
lib/rules/static-property-placement.js
tests/lib/rules/static-property-placement.js

[Fix] `static-property-placement`: do not report non-components

---

CHANGELOG.md
docs/rules/jsx-curly-brace-presence.md
lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

[Fix] `jsx-curly-brace-presence`: ignore containers with comments

---

CHANGELOG.md
docs/rules/jsx-pascal-case.md
lib/rules/jsx-pascal-case.js
package.json
tests/lib/rules/jsx-pascal-case.js

Fixes #2905.
Note: This will potentially relax existing `ignore`s:
- **Before**, `ignore`only checked exact matches
- **After**, `ignore` checks partial matches as well
I think this is fine, since it mirrors ESLint's behavior for the `camelcase` rule. If we prefer to be extra careful, I can make this a new option (eg. `ignoreRegex`).

[Fix] `jsx-pascal-case`: support regex ignore option

---

.eslintrc
CHANGELOG.md
README.md
markdown.config.js

The README contains three different lists of rules (basic rules, JSX-specific ones, recommended ones). I've found that looking through those lists to find out what rule is part of the recommended ruleset is not as simple as it could be.
This PR replaces the lists of available rules with tables containing indicators for whether a rule is enabled in the recommended ruleset and if it is fixable (just like the official [ESLint page](https://eslint.org/docs/rules/) does).
I have removed the list of the recommended rules entirely as the information can now be found in the tables mentioned above, but I can undo that change if you prefer to keep that list in (or transform it into a table as well).
The result looks like this:
✔: Enabled in the [`recommended`](#recommended) configuration.\
🔧: …

[Docs] Improve legibility of lists of available rules in readme

---

CHANGELOG.md
lib/rules/destructuring-assignment.js
tests/lib/rules/destructuring-assignment.js

Fixes #2911.
Related pull request: https://github.com/yannickcr/eslint-plugin-react/pull/2912
> hm, does eslint itself not have utilities for determining the relationship to function params?
I adjusted my code. `createSFCParams` collect the props and context info in SFC.
```javascript
function handleStatelessComponent(node) {
const params = evalParams(node.params);
const SFCComponent = components.get(context.getScope(node).block);
if (!SFCComponent) {
return;
}
sfcParams.push(params);
// ......
}
```

[Fix] `destructuring-assignment`: fix a false prositive for local prop named `context` in SFC

---

CHANGELOG.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

Fix #2924 by allowing either `rel="noreferrer"` or `rel="noopener"` when `allowReferrer` is true.
Also add a missing negative test with `allowReferrer` set to true.

[Fix] `jsx-no-target-blank`: Allow rel="noreferrer" when `allowReferrer` is true

---

CHANGELOG.md
lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

Add a check for typescript boolean type without the need to explicitly define react PropTypes.
```
type Props = {
enabled: boolean
}
const Hello = (props: Props) => <div />;
```
Will throw a linting error for the above code.

[Fix] `boolean-prop-naming`: add check for typescript "boolean" type

---

CHANGELOG.md
docs/rules/jsx-pascal-case.md
lib/rules/jsx-pascal-case.js
tests/lib/rules/jsx-pascal-case.js

Fixes #2914.
New feature allows users to ignore text after the dot for namespaced components such as Theme-UI's Styled component `<Styled.h1>`.
As part of the changes, also addressed some issues that I identified in the rule. Previously if a component was namespaced the text before the dot could be not camelcase and could even be non-alphanumeric.

[New] `jsx-pascal-case`: support namespace option

---

CHANGELOG.md
lib/util/version.js
tests/fixtures/version/detect-version-sibling/node_modules/flow-bin/package.json
tests/fixtures/version/detect-version-sibling/node_modules/react/index.js
tests/fixtures/version/detect-version-sibling/node_modules/react/package.json
tests/fixtures/version/detect-version/detect-version-child/node_modules/flow-bin/package.json
tests/fixtures/version/detect-version/detect-version-child/node_modules/react/index.js
tests/fixtures/version/detect-version/detect-version-child/node_modules/react/package.json
tests/util/version.js

This fixes #2218.  This changes version.js to detect the React and Flow versions relative to the file being linted.

Detect the React and Flow versions relative to the file being linted.

---

CHANGELOG.md
README.md
docs/rules/jsx-newline.md
lib/rules/jsx-newline.js
tests/lib/rules/jsx-newline.js

[New] `jsx-newline` support prevent option

---

CHANGELOG.md
lib/rules/jsx-curly-newline.js

The error messages for 'unexpected' curlys use the opposite curly.

[Fix] `jsx-curly-newline`: Update error messages

---

CHANGELOG.md
README.md
docs/rules/no-unstable-nested-components.md
index.js
lib/rules/no-unstable-nested-components.js
tests/lib/rules/no-unstable-nested-components.js

Fixes #2749.
This is my first time playing with AST. Feel free to guide me in any way.

[New] `no-unstable-nested-components`: Prevent creating unstable components inside components

---

CHANGELOG.md
lib/util/version.js
tests/util/version.js

[Fix] version detection: support processor virtual filename

---

CHANGELOG.md
lib/rules/jsx-max-depth.js
tests/lib/rules/jsx-max-depth.js

Fixes #2880.
`findJSXElementOrFragment` is getting stuck if given variable A references variable B, while variable B also references variable A (directly or via another references).
Before calling method recursively, check whether we have already checked references of the variable.
1. Simple circular reference check for a single level
2. Complex circular reference check for multiple levels. Makes sure `previousReferences` is passed through the whole call chain, instead of just a single call.
Ran `eslint-remote-tester` in comparison mode against 500 repositories. First run caught ~86K ESLint reports. Second call (with the fix) was identical except the old crash being missing. Results: https://github.com/AriPerkkio/eslint-plugin-react/pull/1#issuecomment-810785700
I had to do couple of …

[Fix] `jsx-max-depth`: Prevent getting stuck in circular references

---

CHANGELOG.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

fix handling of warnOnSpreadAttributes being false

---

CHANGELOG.md
lib/rules/forbid-dom-props.js
tests/lib/rules/forbid-dom-props.js

This rather strange pattern is common in [FBT](https://facebook.github.io/fbt/docs/params) and valid according to [JSX](http://facebook.github.io/jsx/) (see `JSXNamespacedName`). Without this change the rule fails on the following error:
```
TypeError: Cannot read property 'toUpperCase' of undefined
```
See: https://github.com/adeira/universe/issues/2005

forbid-dom-props: support `JSXNamespacedName`

---

CHANGELOG.md
README.md
lib/util/Components.js
tests/lib/rules/prop-types.js

[New] component detection: add componentWrapperFunctions setting

---

CHANGELOG.md
README.md
lib/util/Components.js
tests/lib/rules/prop-types.js

This PR is my attempt to resurrect the #2713 PR by @jzabala. I haven't changed anything in the original PR other than making the changes suggested by @ljharb and rebasing on top of the latest master.
Please let me know if there's anything else required. I'd really love to land this PR so I can use it. Thanks!
CC @jzabala, @flut1, @ljharb, @jillesme

Resurrection of #2713: add componentWrapperFunctions setting

---

CHANGELOG.md
lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

Currently the output is `ESLint: Prop key for handleChange must begin with '{{handlerPropPrefix}'(react/jsx-handler-names)`

[Fix] `jsx-handler-names`: properly substitute value into message

---

CHANGELOG.md
docs/rules/no-unused-prop-types.md
lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

Add support for the `ignore` option to `no-unused-prop-types` (same as `prop-types`).
This is useful when using `react-navigation` with `flow` because the navigators require components to have `navigation` and `route` props defined even if they're not used in the component.

[New] `no-unused-prop-types`: add `ignore` option

---

CHANGELOG.md
lib/util/Components.js

closes #1126.
The rule spends lots of time in`utils.isCreateElement` -> `isDestructuredFromPragmaImport`.  This pr reduces that expensive function call by short-circuiting it when possible.
Benchmarks:
```
Before this pr:
$ TIMING=50 npx eslint . | grep react/void-dom
react/void-dom-elements-no-children             |   263.673 |     3.6%
react/void-dom-elements-no-children             |   256.981 |     3.4%
react/void-dom-elements-no-children             |   230.990 |     3.3%
react/void-dom-elements-no-children             |   235.888 |     3.2%
react/void-dom-elements-no-children             |   251.152 |     3.5%
After this pr:
react/void-dom-elements-no-children             |   106.662 |     1.6%
react/void-dom-elements-no-children             |   106.205 |     1.6% …
```

[Refactor] `void-dom-elements-no-children`: improve performance

---

CHANGELOG.md
lib/rules/jsx-uses-vars.js
tests/lib/rules/jsx-uses-vars.js

JSX namespaces are transpiled into strings, not identifiers.
This can be seen in [here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MA8BBAXAIRgegD4g) for TypeScript.
Babel behaves the same, but it requires a configuration which isn’t supported by their playground.

[fix] `jsx-uses-vars`: ignore namespaces

---

CHANGELOG.md
lib/rules/jsx-no-undef.js
tests/lib/rules/jsx-no-undef.js

JSX namespaces are transpiled into strings, not identifiers.
This can be seen in [here](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAZiEMC8MA8BBAXAIRgegD4g) for TypeScript.
Babel behaves the same, but it requires a configuration which isn’t supported by their playground.

[fix] `jsx-no-undef`: ignore namespaces

---

CHANGELOG.md
lib/rules/jsx-child-element-spacing.js
tests/lib/rules/jsx-child-element-spacing.js

Ref: https://github.com/yannickcr/eslint-plugin-react/issues/2988
This PR simply removes BR from the set of inline elements, because I don't think there's any case where whitespace around a br tag would result in a different result rendered in the browser.
Adds example tests for code that should not be flagged by this rule:
```
<App>
A
<br/>
B
</App>
<App>
A<br/>
B
</App>
<App>
A<br/>B
</App>
<App>A<br/>B</App>
```

Don't flag whitespace around `<br/>` tags

---

CHANGELOG.md
lib/util/version.js
package.json
tests/util/version.js

continue to work on #2949
---
According to https://github.com/eslint/eslint/pull/14227#discussion_r602802758, virtual filename could be recursive, this PR fix this possible issue.

[Fix] version detection: support recursive processor virtual filename

---

CHANGELOG.md
lib/rules/no-typos.js
lib/util/Components.js
lib/util/ast.js
lib/util/jsx.js
package.json
tests/lib/rules/destructuring-assignment.js
tests/util/ast.js
tests/util/jsx.js

+ Added [estraverse](https://github.com/estools/estraverse) as dependency.
+ Implemented function `traverseReturns` using `estraverse` to improve return value analysis.
+ Rewrote `isReturningJSX` function to handle return statements nested inside other structures (`IfConditions`, `SwitchStatements`, etc)
+ This should also fix #2960

Improve component detection

---

CHANGELOG.md
docs/rules/jsx-no-bind.md

this is a follow-up from the discussion in https://github.com/yannickcr/eslint-plugin-react/pull/2991 to update documentation to make it clear why sending new functions to refs does not cause re-renders.
It felt a little too self-serving to add the demo I made for this https://codesandbox.io/s/inline-arrow-refs-do-not-cause-rerenders-4cdmf?file=/src/App.js but if it's deemed helpful, I'd be happy to add it.

[Docs] updates jsx-no-bind discussion of refs

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/destructuring-assignment.js
tests/lib/rules/no-multi-comp.js
tests/lib/rules/no-unstable-nested-components.js

Fixes: #2956
Description: 
Example code that shows incorrect error:
```
const columns = [
{
render: (val) => {
if (val.url) {
return (
<a href={val.url} rel="noopener noreferrer" target="_blank">
{val.fileName || 'PDF'}
</a>
);
}
return null;
},
},
];
```
Error shows up because `getParentComponent` calls `getParentStatelessComponent` that calls  [`getStatelessComponent`](https://github.com/yannickcr/eslint-plugin-react/blob/faadccb65d9a4d813fe58efc86293f97447a96da/lib/util/Components.js#L637) on the `ArrowFunctionExpression` (val =>...) in the example code above which incorrectly returns the same `ArrowFunctionExpression` instead of `undefined`.

[Fix] destructuring-assignment, no-multi-comp, `no-unstable-nested-components`, component detection: improve component detection

---

CHANGELOG.md
docs/rules/jsx-no-useless-fragment.md
lib/rules/jsx-no-useless-fragment.js
tests/lib/rules/jsx-no-useless-fragment.js

When writing JSX in typescript, a common problem is that Typescript expects the return type of a component to be `ReactElement`. This excludes other types that a component could return, for example just a plain string. This is a problem that's been discussed with the TS community here: [21699](https://github.com/microsoft/TypeScript/issues/21699), however my understanding is there are technical barriers to overcome in order to support this.
A common workaround for this is to wrap a variable in a fragment and expression to get the desired result:
```tsx
type Person = { name: string }
// type error
const WhatsMyName: React.FC<{ person: Person }> = ({ person }) => person.name
// workaround
const WhatsMyName: React.FC<{ person: Person }> = ({ person }) => <>{person.name}</>
```
This works …

[react/jsx-no-useless-fragments] add option to allow single expressions in fragments

---

CHANGELOG.md
lib/rules/destructuring-assignment.js
tests/lib/rules/destructuring-assignment.js

correct #2929, for issue #2911

[Fix] `destructuring-assignment`: get the contextName correctly

---

CHANGELOG.md
README.md
docs/rules/jsx-no-target-blank.md
lib/rules/jsx-no-target-blank.js
lib/util/linkComponents.js
tests/lib/rules/jsx-no-target-blank.js

This should fix #1143.
I am not sure if this should be an option or not (as suggested in the issue)(?).

jsx-no-target-blank to check for forms with target="_blank"

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/destructuring-assignment.js

Fixes: #3024 
Added code to deal with `ExportDefaultDeclaration` as the parent node of a `ArrowFunctionExpression`

[Fix] destructuring-assignment, component detection: handle default export edge case

---

.github/workflows/node-4+.yml
.github/workflows/smoke-test.yml
.gitignore
CHANGELOG.md
package.json
test/eslint-remote-tester.config.js
tests/fixtures/version/detect-version-missing/node_modules/react/index.js
tests/fixtures/version/detect-version-missing/node_modules/react/package.json
tests/util/version.js

Context: https://github.com/AriPerkkio/eslint-remote-tester/issues/29
Adds weekly scheduled smoke tests to be run on every Sunday at 00:00. Tests can also be trigger manually (`workflow_dispatch`). These tests will be looking for rule crashes.
Previously these tests have been run in `eslint-remote-tester`'s repository. So far bugs below have been found by automated CI runs:
1. `jsx-no-constructed-context-values: Cannot read property 'set' of undefined` yannickcr/eslint-plugin-react#2894
2. `jsx-no-constructed-context-values: Cannot read property 'type' of null` yannickcr/eslint-plugin-react#2895
3. `no-unknown-property: allowedTags.indexOf is not a function` yannickcr/eslint-plugin-react#2879
4. `jsx-max-depth: Maximum call stack size exceeded` yannickcr/eslint-plugin-react#2880
5. …

[Tests]: add weekly scheduled smoke tests

---

CHANGELOG.md
docs/rules/jsx-pascal-case.md
lib/rules/jsx-pascal-case.js
tests/lib/rules/jsx-pascal-case.js

Fixes #2603
* Adds a new *optional* `allowLeadingUnderscore` property to the existing `jsx-pascal-case` rule. 
* Updates documentation to clearly explain when *not* to use it
* Updates unit tests to ensure coverage

[New] `jsx-pascal-case`: add `allowLeadingUnderscore` option

---

CHANGELOG.md
docs/rules/no-children-prop.md
lib/rules/no-children-prop.js
tests/lib/rules/no-children-prop.js

[New] `no-children-prop`: Add `allowFunctions` option 

---

CHANGELOG.md
docs/rules/jsx-no-bind.md
lib/rules/jsx-no-bind.js
tests/lib/rules/jsx-no-bind.js

Fixes #3047 
I implemented this in a pretty straightforward way, so there are some trade-offs:
1. Any assignments to a function declaration are not considered. Consequently, a function that is unconditionally re-assigned with something that doesn't bind will still trigger a violation.
2. It uses the same configuration value and error message as the usage of a function expression.
To fix 1 would require some fancy analysis, and is probably not worth the effort, though 2 would be easy to fix and I can do so if needed.

jsx-no-bind: Report usage of local functions as violations

---

CHANGELOG.md
lib/util/propTypes.js
tests/lib/rules/prop-types.js

Fixes #3045 and related issues.
Implements logic discussed in this comment: https://github.com/yannickcr/eslint-plugin-react/issues/2777#issuecomment-683944481

[Fix] `prop-types`, `propTypes`: handle React.* TypeScript types

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/no-this-in-sfc.js

+ Modified `getStatelessComponent` method
+ Added check for functions assigned to properties (property name must be PascalCase)
Fixes #3054

[Fix] False positive in `no-this-in-sfc`

---

CHANGELOG.md
docs/rules/jsx-no-useless-fragment.md
lib/rules/jsx-no-useless-fragment.js
tests/lib/rules/jsx-no-useless-fragment.js

Bug fix.
Problem: When `react/jsx-no-useless-fragment` has `allowExpression` set to `true`, the following code produces an error:
```jsx
<>
{foo ? (
<Bar />
) : (
<Baz />
)}
</>
```
This PR amends the `allowExpressions` rule added in #3006 to allow insignificant whitespace around the expression.

[Fix] `jsx-no-useless-fragments`: Allow whitespace when `allowExpressions` is `true`

---

CHANGELOG.md
lib/util/propTypes.js
tests/lib/rules/prop-types.js

#3062 
All react generic type extends from `type PropsWithChildren<P> = P & { children?: ReactNode | undefined };`. So whenever a generic type from React is used I've added an optional children prop to `this.declaredPropTypes`.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L824

[Fix] `prop-types`, `propTypes`: handle implicit `children` prop in react's generic types

---

CHANGELOG.md
lib/util/jsx.js
tests/util/jsx.js

- when determining if an `ArrowFunctionExpression` returns JSX, do not check arguments to a returned `CallExpression`
Arrow function expressions that return the result of a function call taking JSX arguments are incorrectly deemed to be returning JSX. This leads to some misinterpretations of arrow functions as function components, which are then flagged as "missing display name".
```
const obj = {
prop: () => console.log(<a>something</a>)
};
const obj2 = {
prop: () => { return console.log(<a>something</a>); }
};
```
```
let obj3;
obj3 = () => console.log(<a>something</a>);
```
I think any other examples of `ArrowFunctionExpressions` that pass `utils.isInAllowedPositionForComponent` at https://github.com/yannickcr/eslint-plugin-react/blob/810806e58d5a611e6743227c91d859c2c02563bb/lib/util/Co …

[Fix] `display-name`: fix misinterpreted function components

---

CHANGELOG.md
lib/rules/jsx-uses-vars.js
tests/lib/rules/jsx-uses-vars.js

[fix] `jsx-uses-vars` ignores lowercase tag names

---

README.md

Fix broken link to ESLint docs in README

[readme] Update broken link for configuration files

---

CHANGELOG.md
lib/util/propTypes.js
tests/lib/rules/prop-types.js

Fixes #3074 
when `const Comp = (props: NonReactGeneric<T>) => {...}` proceed as usual instead of early return.

[Fix] `prop-types` `propTypes`: bail out unknown generic types inside func params

---

CHANGELOG.md
README.md
docs/rules/no-namespace.md
index.js
lib/rules/button-has-type.js
lib/rules/forbid-elements.js
lib/rules/no-adjacent-inline-elements.js
lib/rules/no-children-prop.js
lib/rules/no-namespace.js
lib/rules/style-prop-object.js
lib/util/Components.js
lib/util/isCreateElement.js
lib/util/isDestructuredFromPragmaImport.js
tests/lib/rules/no-namespace.js

Following the discussion in https://github.com/yannickcr/eslint-plugin-react/issues/1334#issuecomment-626245703, I am submitting the introduction of the rule `jsx-no-namespace`.
Summary: JSX namespaces are not supported by React. When a JSX namespace is used in a JSX component, the rules `jsx-no-undef` or `jsx-pascal-case` raise an error, which is unfortunate because none of them explain what is happening.
This rule is not of critical importance because the error is flagged at runtime by React. Still, I believe it to be a valuable inclusion.

[New] add `no-namespace` rule

---

CHANGELOG.md
lib/rules/display-name.js
tests/lib/rules/display-name.js

[Fix] `display-name`: Get rid of false position on component detection

---

CHANGELOG.md
tests/lib/rules/no-access-state-in-setstate.js

unstated uses `this.setState` and we're getting false positives when using this rule.
I figured this would be better than an issue. Is this something we could add?

[Tests] `no-access-state-in-setstate`: passing test for “don't error if it's not a React Component"

---

CHANGELOG.md
docs/rules/jsx-max-props-per-line.md
lib/rules/jsx-max-props-per-line.js
tests/lib/rules/jsx-max-props-per-line.js

You can only define single or multiple line prop count. 
Allow to config rule to check both multiple and single line tags while maintaining backward compatibility.

[New] `jsx-max-props-per-line`: allow defining both `multi` and `single` line prop count

---

docs/rules/react-in-jsx-scope.md

The lines have shifted since this was added, causing the incorrect
range to be highlighted. We can fix this by pinning the link to a specific
git SHA.

Pin link to code in react-in-jsx-scope docs

---

CHANGELOG.md
docs/rules/jsx-max-props-per-line.md

Small issues with `jsx-max-props-per-line`  docs

[Docs] `jsx-max-props-per-line`: fix options example

---

CHANGELOG.md
docs/rules/jsx-no-target-blank.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

The current error message is confusing because it complains about links missing `rel="noreferrer"` even if `allowReferrer` is set to `true` and so `rel="noopener"` is enough to satisfy it. I made it report different messages depending on `allowReferrer` value and state that even if `rel="noopener"` is enough, `rel="noreferrer"` is preferred as per https://github.com/yannickcr/eslint-plugin-react/issues/3044#issuecomment-916801701. Also clarified the docs for `allowReferrer` to prevent misunderstandings like #3044.

[Fix] `jsx-no-target-blank`: improve error messages

---

CHANGELOG.md
README.md
docs/rules/no-unused-class-component-methods.md
index.js
lib/rules/no-unused-class-component-methods.js
tests/lib/rules/no-unused-class-component-methods.js

Display errors in case class component contains unused methods.
Fixes #2166.

[New] add `no-unused-class-component-methods` 

---

CHANGELOG.md
README.md
docs/rules/no-arrow-function-lifecycle.md
index.js
lib/rules/no-arrow-function-lifecycle.js
lib/rules/no-typos.js
lib/util/lifecycleMethods.js
tests/lib/rules/no-arrow-function-lifecycle.js
tests/lib/rules/no-typos.js

I would like to add one more rule no-arrow-function-lifecycle which checks that it is not necessary to use arrow function for lifecycle methods and it will affect a bit performance.
I did code review some projects and found that our teammates use arrow function for lifecycle methods constantly. Beside that, I also found a ticket related to this issue. See [react/issues/10810](https://github.com/facebook/react/issues/10810) for more details. 
Consider the below code 
```
class Hello extends React.Component {
render = () => {
}
}
```
Do you need to use arrow function here? I believe that, you will have the same idea that it shouldn't.
I'm eagerly looking forward to seeing your comments.

[New] Add `no-arrow-function-lifecycle` rule

---

tests/lib/rules/jsx-uses-vars.js

This PR is to add a failing test for the following situation:
```js
// False Negative:
// The `div` parameter below is not recognized as an unused variable
function App(div) {
return <div />
}
```
This also happens with other variables (eg. variables declared separately):
```js
const div = 123;
export function App() {
}
```
Incorrectly reported here: https://github.com/typescript-eslint/typescript-eslint/issues/2985

[react/jsx-uses-vars]: False negative on HTML elements used in JSX

---

CHANGELOG.md
lib/util/propTypes.js
tests/lib/rules/prop-types.js

[Fix] `propTypes`: add `VoidFunctionComponent` to react generic list

---

package.json

Fixes "Invalid hook call" of https://github.com/yannickcr/eslint-plugin-react/runs/4057441339?check_suite_focus=true. See https://github.com/AriPerkkio/eslint-remote-tester/pull/302. The previous smoke test was unable to log any output to stdout, but the test was still run successfully. Everything was linted properly, it was just the output which was missing.
- `eslint-remote-tester@2` fixes the react version conflicts. It also improves erroneous ruleId parsing when used with ESLint v8. It is compatible with ESLint 7. https://github.com/AriPerkkio/eslint-remote-tester/blob/master/CHANGELOG.md

[Dev Deps] update `eslint-remote-tester`

---

CHANGELOG.md
README.md
docs/rules/no-invalid-html-attribute.md
index.js
lib/rules/no-invalid-html-attribute.js
tests/lib/rules/no-invalid-html-attribute.js

This rule (and fixer) checks the "rel" value to make sure that it correctly relates to the tag that the "rel" property is on.

[New] add `no-invalid-html-attribute` rule

---

.github/workflows/smoke-test.yml

Adds support for ESLint v8. Works with ESLint v7 too. 
Example run: https://github.com/AriPerkkio/eslint-plugin-react/actions/runs/1415490892. The `no-invalid-html-attribute` rule crashed couple of times there.

[Dev Deps] update `eslint-remote-tester-run-action`

---

CHANGELOG.md
lib/util/Components.js
lib/util/jsx.js
tests/lib/rules/destructuring-assignment.js

[Fix] `destructuring-assignment`, component detection: improve component detection

---

CHANGELOG.md
docs/rules/jsx-no-target-blank.md

Fixes #3123.
Additionally:
- I added the missing `warnOnSpreadAttributes` option to the code block with a rule configuration.
- Rearranged items on the enumeration list so that they match the order of options in the mentioned code block.
- Adjusted formatting of those items so that all of them have the same style. (I chose the colon over the hyphen, as that's how most other rules have their options described.)

[Docs] `jsx-no-target-blank`: adjust options description

---

.github/workflows/node-4+.yml
CHANGELOG.md
package.json
tests/helpers/getESLintCoreRule.js
tests/helpers/parsers.js
tests/lib/rules/destructuring-assignment.js
tests/lib/rules/jsx-no-undef.js
tests/lib/rules/jsx-no-useless-fragment.js
tests/lib/rules/jsx-uses-react.js
tests/lib/rules/jsx-uses-vars.js
tests/lib/rules/no-unused-prop-types.js

ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉
devDependency compatibility with ESLint 8:
---
Closes #3055

[New] support eslint 8.x

---

CHANGELOG.md
lib/rules/no-unused-class-component-methods.js
tests/lib/rules/no-unused-class-component-methods.js

[Fix] `no-unused-class-component-methods`: add getChildContext lifecycle method

---

CHANGELOG.md
README.md

[readme] fix syntax typo

---

CHANGELOG.md
lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

Fixes #2944.
```js
const { styles: x } = props;
```
Our code incorrectly picks up `styles` as a prop, while `x` is the correct one.

[Fix] `prop-types`: fix false positives on renames in object destructuring

---

CHANGELOG.md
lib/util/Components.js
tests/util/Component.js

This PR adds a couple of basic tests to the existing `Components.detect` functionality.
Next it adds a facility for detecting the imported React identifiers during a parse, and adds a simple test for that detection.
This is an extraction of work initiated in https://github.com/yannickcr/eslint-plugin-react/pull/2921 and supports that PR
I think having a test runner for the `Components.detect` utility was worthwhile in itself, and separated that test-runner functionality into its own commit.

[New] component detection: track React imports

---

CHANGELOG.md
docs/rules/function-component-definition.md
lib/rules/function-component-definition.js
tests/lib/rules/function-component-definition.js

This adds support to the `function-component-definition`  rule to have the
`namedComponents` and `unnamedComponents` options be an array.

[New] `function-component-definition`: support `namedComponents` option being an array

---

tests/helpers/parsers.js

In order to generate suggestions for https://github.com/yannickcr/eslint-plugin-react/pull/2921 I need support for augmenting suggestions in the `parsers.all` work, to ensure my spec examples get decorated with the `extraComment`.
parsers.all generates an `extraComment` which is appended to test case examples and their expected output.
Eslint's suggestions API also allows recommended code changes, and RuleTester compares expected changes against generated changes. However, `parsers.all` didn't augment these expected outputs with the `extraComment`.
I intend to include these changes with the `hook-use-state` PR where the utility will be more obvious, but I wanted to open discussion here in case my approach needs to be refined, and to keep the already long-running `hook-use-state` PR …

[Test] parsers.all augments suggestion code output

---

CHANGELOG.md
lib/util/Components.js
tests/util/Components.js

* Rename Components test suite filename to match sibling lib/util/Components filename.
* Extend Components `testComponentsDetect` function to accept custom instructions, and to accumulate the results of processing those instructions.
* Add utility to check whether a `CallExpression` is a React hook call.
This work extracts the somewhat complicated guard clause from #2921
It also makes hooks-usage detection generic, so the util can be used to check for:
* call to any React hook
* call to one or more specific React hooks; this will be used to check for `useState` calls in #2921
I converted this PR to a Draft while I work to extract this in a way that leaves the `hook-use-state` rule clean and easy to process.

[New] Component detection: add `util.isReactHookCall`

---

CHANGELOG.md
README.md
docs/rules/hook-use-state.md
index.js
lib/rules/hook-use-state.js
tests/lib/rules/hook-use-state.js

Ensure two symmetrically-named variables are destructured from useState hook calls
This is a re-opening of https://github.com/yannickcr/eslint-plugin-react/pull/2873
I've rebased and updated the README using `npm run generate-list-of-rules` to follow the new table-ish layout.
* Supports both `useState` and `React.useState`
* Tested with TypeScript parser and `useState<>` type annotation
* Robust against weird `useState` uses like destructuring too many items, or not destructuring at all
* Fixable when 2nd destructured arg does not match `set<X>` naming convention
Fixes #2417.

[New] Symmetric useState hook variable names

---

CHANGELOG.md
lib/util/ast.js
lib/util/propTypes.js
tests/lib/rules/prop-types.js

[Fix] `prop-types`, `propTypes`: add support for exported type inference

---

CHANGELOG.md
README.md

Small issues with `react/jsx-runtime` docs

[Docs] update `react/jsx-runtime` link

---

CHANGELOG.md
lib/rules/no-invalid-html-attribute.js
tests/lib/rules/no-invalid-html-attribute.js

Closes #3172 
For historical reasons, the icon keyword may be preceded by the keyword "shortcut".
[https://html.spec.whatwg.org/multipage/links.html#rel-icon](https://html.spec.whatwg.org/multipage/links.html#rel-icon) (last sentence before the next paragraph about `license`)
1. First of all I'm checking if there are pairs registered for the given attribute name after all.
2. Now I'm splitting the attribute value(s) into *overlapping* pairs. If you want to check on the funky regex: https://regex101.com/r/aJXAEz/1
3. now I'm iterating pair by pair
4. on each pair I check what are the possible siblings for my current item - currently there is only 1:1 but potentially there could be a pair where `foo` can go with `bar` OR `baz` but NEVER `qux`
5. now I check if my pair is separated by a …

[Fix] `no-invalid-html-attribute`: allow 'shortcut icon' on `link`

---

CHANGELOG.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

> If you do not support Internet Explorer (any version), Chrome < 49, Opera < 36, Firefox < 52, desktop Safari < 10.1 or iOS Safari < 10.3, you may set `allowReferrer` to `true`, keep the HTTP Referer header and only add `rel="noopener"` to your links.
Source: https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md#when-to-override-it
This PR improves the fixer to use `rel="noopener"` if `allowReferrer` is set.

[New] `jsx-no-target-blank`: Improve fixer with option `allowReferrer`

---

CHANGELOG.md
README.md

(lower case after  period, and also reiteration at the beginning)

[readme] Some grammar fixes 

---

CHANGELOG.md
docs/rules/jsx-no-target-blank.md

See https://web.dev/external-anchors-use-rel-noopener/, https://chromestatus.com/feature/6140064063029248 and https://caniuse.com/mdn-html_elements_a_implicit_noopener for some background information on this change.

[Fix] `jsx-no-target-blank`: Improve readme

---

CHANGELOG.md
lib/rules/prefer-exact-props.js
tests/lib/rules/prefer-exact-props.js

Use `getStatelessComponent` instead of `getParentStatelessComponent` because the second will find the component to it's ancestors. That is incorrect and could cause performance problem.
See the changed test case.

[Fix] fix `prefer-exact-props` and improve performance

---

CHANGELOG.md
docs/rules/jsx-curly-brace-presence.md
lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

[New] `jsx-curly-brace-presence`: add "propElementValues" config option

---

CHANGELOG.md
lib/util/propTypes.js
tests/lib/rules/no-unused-prop-types.js

:wave: from GitHub Desktop land!
We're currently upgrading to TypeScript 4.5 (https://github.com/desktop/desktop/pull/13768) and while doing that I wanted to start using the `react/no-unused-props-type` rule instead of the `react-unused-props-and-state` from the obsolete `tslint-microsoft-contrib` package.
Unfortunately I couldn't get the rule to produce any errors. I put up a minimal reproduction repository at https://github.com/niik/no-unused-prop-types-repro which illustrates the problem. To test it just clone and run `yarn lint`
Doing so very haphazardly troubleshooting I noticed that when encountering our prop types in `propTypes.js` they were of type `TSTypeReference` which was not being handled in the switch case.  Spotting that `DeclarePropTypesForTSTypeAnnotation` seemed to be …

Handle TSTypeReference in no-unused-prop-types

---

CHANGELOG.md
README.md
docs/rules/iframe-missing-sandbox.md
index.js
lib/rules/iframe-missing-sandbox.js
tests/lib/rules/iframe-missing-sandbox.js

[New] add `iframe-missing-sandbox` rule (migrate rule from TSLint)

---

CHANGELOG.md
lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

This PR will fix the issue describe in https://github.com/yannickcr/eslint-plugin-react/issues/618 where the indentation of the closing parentheses on return statements was not working.
I know some tests are failing, because the existing fixtures doesn't fit with the new behaviour. Therefore I think this should be enabled with an option. Before I fix that, I would like to get some feedback if the implementation is good so far.
Fixes #618.

Fix indentation of closing parentheses 

---

tests/lib/rules/jsx-sort-props.js

Updated unit test with failing case for callbacksLast not working when used in combination with reservedFirst. (First ever pull request - tell me if I did something wrong!)

Issue #1632 - jsx-sort-props: reservedFirst conflicts with callbacksLast

---

CHANGELOG.md
docs/rules/jsx-sort-props.md
lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

Hello :wave: 
This PR Adds a new multiline group for the `jsx-sort-props` rule. Related to the issue: #3170
The shorthand and callback rules take precedence over the multiline rule set

[New] `jsx-sort-props`: support multiline prop groups

---

CHANGELOG.md
docs/rules/jsx-no-target-blank.md

Documentation is hard to read with `json` Markdown code block:
This PR fixes it.
I've ended up on [the page](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md) after clicking the popup in VS Code:

Get rid of red in jsx-no-target-blank documentation

---

CHANGELOG.md
docs/rules/jsx-key.md

Using an index for a key is a violation of the [no-array-index-key](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-array-index-key.md) lint rule, so it feel weird to me that we're showing it as an example for "correct" code, even though it isn't strictly a violation of the `js-key` rule.

[Docs] `jsx-key`: improve example 

---

.github/workflows/release.yml

Based on the discussion in #3221 this adds a workflow that runs when tags are pushed and creates/updates a release of the same name.
After some testing it turns out GitHub detects force pushes of tags and automatically points an existing release to the new commit. This means the extra steps to check for an existing release, delete it if found, etc. aren't needed.
With this in place you should be able to:
- push a `v2.0.0` tag
- a release will be created automatically
- the changelog contents will be copied to it
- make some changes to `main`
- move the tag up a few commits
- force push the `v2.0.0` tag
- GitHub will auto-update the release's tag/sha
- this workflow will update the release notes with anything new

[actions] add release workflow

---

CHANGELOG.md
lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

**Types of changes**
This PR fixes #3197, therefore, the `boolean-prop-naming` rule validates correctly the following code: 
```tsx
import type { FC } from 'react' // or import { FC } from 'react'
type Props = {
enabled: boolean // ❌ error
} 
export const Component: FC<Props> = props => { 
return <div /> 
}
```
```tsx
import * as React from 'react' 
type Props = {
enabled: boolean // ❌ error
} 
export const Component: React.FC<Props> = props => { 
return <div /> 
}
```
```tsx
import type { FC } from 'react' // or import { FC } from 'react'
type Props = {
isEnabled: boolean // ✅
} 
export const Component: FC<Props> = props => { 
return <div /> 
}
```
```tsx
import * as React from 'react' 
type Props = {
isEnabled: boolean // ✅
} 
export const Component: React.FC<Props> = props => { 
return …
```

[Fix] `boolean-prop-naming`: handle React.FC, intersection, union types

---

CHANGELOG.md
lib/rules/hook-use-state.js
tests/lib/rules/hook-use-state.js

Closes https://github.com/yannickcr/eslint-plugin-react/issues/3243
This PR allows `useState` destructured variable names to use ALL-UPPER-CASE for the first segment of the setter variable name.
```js
// Previously invalid, now valid
const [rgbColor, setRGBColor] = useState();
```
The existing suggested variable name `setRgbColor` is still the sole suggestion; `setRGBColor` is considered valid, but is never suggested.
This should be a non-breaking change as all previously-valid code is still considered valid.

[Fix] `hook-use-state`: Allow UPPERCASE setState setter prefixes

---

CHANGELOG.md
README.md
docs/rules/destructuring-assignment.md
lib/rules/destructuring-assignment.js
tests/lib/rules/destructuring-assignment.js

[New] `destructuring-assignment`: add option `destructureInSignature`

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

[New] `no-unknown-property`: Allow crossOrigin on image tag (SVG)

---

CHANGELOG.md
README.md

I've also updated eslint@7 => eslint@8(latest).

[readme] remove global usage and eslint version from readme

---

.eslintrc
CHANGELOG.md
lib/rules/jsx-max-depth.js
lib/rules/jsx-pascal-case.js
lib/rules/jsx-sort-props.js
lib/rules/require-render-return.js
lib/rules/sort-comp.js
lib/util/ast.js
lib/util/makeNoMethodSetStateRule.js

Before:
✖ 91 problems (0 errors, 91 warnings)
After:
✖ 53 problems (0 errors, 53 warnings)

[Refactor] fix linter errors

---

CHANGELOG.md
docs/rules/jsx-tag-spacing.md
lib/rules/jsx-tag-spacing.js
tests/lib/rules/jsx-tag-spacing.js

- This option enforces that the closingTag or the selfClosingTag is on a
new line if the entire tag is a multiline tag
Fixes #3210.

[New] `jsx-tag-spacing`: Add `multiline-always` option

---

CHANGELOG.md
lib/rules/no-unused-state.js
tests/lib/rules/no-unused-state.js

Try to fix #3240 with the smallest change.

Fix issue #3240

---

CHANGELOG.md
lib/util/ast.js
lib/util/jsx.js
tests/util/ast.js

Benchmark on a private repo with `time npx eslint .` (real time):
|  | before | after |
| --- | -- | -- |
| run 1 | 6.6s | 4.8s |
| run 2 | 6.5s | 4.7s |
| run 3 | 6.7s | 4.8s |
Benchmark with `TIMING=10 npx eslint .`:
Before:
```
Rule                                | Time (ms) | Relative
:-----------------------------------|----------:|--------:
react/destructuring-assignment      |   345.923 |     7.0%
react/no-unstable-nested-components |   208.838 |     4.2%
react/no-did-mount-set-state        |   189.097 |     3.8%
react/boolean-prop-naming           |   187.663 |     3.8%
react/no-direct-mutation-state      |   186.664 |     3.8%
react/no-deprecated                 |   184.020 |     3.7%
react/hook-use-state                |   146.379 |     3.0%
react/no-access-state-in-setstate   | …
```

[Refactor]: improve performance for detecting function components

---

CHANGELOG.md
lib/rules/jsx-no-useless-fragment.js

As per title :) 
Currently live:

[Fix] Use curly single quote in error message for `jsx-no-useless-fragment`

---

CHANGELOG.md
lib/util/Components.js

Benchmark on the [eslint repo](https://github.com/eslint/eslint) with `extends: plugin:react/recommended` and `time npx eslint .` (real time):
|  | before | after |
| --- | -- | -- |
| run 1 | 8.0s | 7.3s |
| run 2 | 7.8s | 7.4s |
| run 3 | 8.0s | 7.3s |
Benchmark with `TIMING=10 npx eslint .`:
```
Before:
Rule                           | Time (ms) | Relative
:------------------------------|----------:|--------:
react/no-deprecated            |   762.467 |    21.0%
react/no-direct-mutation-state |   648.951 |    17.9%
react/display-name             |   635.527 |    17.5%
react/no-string-refs           |   531.934 |    14.7%
react/prop-types               |   387.259 |    10.7%
react/require-render-return    |   382.931 |    10.6%
react/no-children-prop         |   165.876 |     4.6% …
```

[Refactor] improve performance for detecting class components

---

CHANGELOG.md
lib/rules/no-deprecated.js

🤔 Call `getDeprecated` for every MemberExpression.
🙂 Call `getDeprecated` for every file linted.
Benchmark with `TIMING=10 npx eslint .`:
```diff
- react/no-deprecated                  |   658.734 |     4.8%
+ react/no-deprecated                  |   324.518 |     2.4%
```

[Refactor] `no-deprecated`: improve performance

---

CHANGELOG.md
lib/util/makeNoMethodSetStateRule.js

❌ Early return on CallExpression
✔️ Early return on rule creation
Benchmark:
```diff
- react/no-did-mount-set-state               |   602.202 |     4.5%
- react/no-did-update-set-state              |   302.628 |     2.3%
- react/no-will-update-set-state             |    10.411 |     0.1%
+ react/no-did-mount-set-state               |     7.566 |     0.1%
+ react/no-will-update-set-state             |     4.627 |     0.0%
+ react/no-did-update-set-state              |     3.381 |     0.0%
```

[Refactor] `no-*-set-state`: improve performance

---

CHANGELOG.md
lib/rules/display-name.js
lib/rules/jsx-indent.js
lib/rules/jsx-no-bind.js
lib/rules/no-access-state-in-setstate.js
lib/rules/no-arrow-function-lifecycle.js
lib/rules/no-deprecated.js
lib/rules/no-direct-mutation-state.js
lib/rules/no-redundant-should-component-update.js
lib/rules/no-string-refs.js
lib/rules/no-typos.js
lib/rules/no-unsafe.js
lib/rules/no-unused-class-component-methods.js
lib/rules/no-unused-state.js
lib/rules/prefer-es6-class.js
lib/rules/prefer-stateless-function.js
lib/rules/require-optimization.js
lib/rules/require-render-return.js
lib/rules/state-in-constructor.js
lib/rules/static-property-placement.js
lib/rules/void-dom-elements-no-children.js
lib/types.d.ts
lib/util/Components.js
lib/util/ast.js
lib/util/componentUtil.js
lib/util/defaultProps.js
lib/util/jsx.js
lib/util/pragma.js
lib/util/usedPropTypes.js
tests/util/jsx.js

Rules using `Component.detect()` are generally slow. Some rules uses `Component.detect(context, components, utils)` solely for the `utils` it provided. These `Component.detect`s can be avoided by extracting some `utils` functions into a module.
Benchmark with config `plugin:react/all`:
```diff
$ time npx eslint .
- 16.429
+ 13.692
```

[Refactor] improve performance by avoiding unnecessary component detect

---

CHANGELOG.md
docs/rules/function-component-definition.md
lib/rules/function-component-definition.js
tests/lib/rules/function-component-definition.js

Thank you for your amazing job, this rule is almost perfect but something is missing to me.
`var` is almost not used since ES6 was introduced and I am not able to find any React documentation showing a functional component using `var` instead of const.
fix #3152

[New] `function-component-definition`: replace `var` by `const` in certain situations

---

CHANGELOG.md
README.md
docs/rules/jsx-no-leaked-render.md
index.js
lib/rules/jsx-no-leaked-render.js
lib/rules/jsx-wrap-multilines.js
lib/util/ast.js
tests/lib/rules/jsx-no-leaked-render.js

New rule `jsx-no-leaked-zero` to prevent potential 0 leaked to the DOM from numeric inline conditions. It includes 2 autofix strategies.

[New] add `jsx-no-leaked-render`

---

CHANGELOG.md
docs/rules/require-default-props.md
lib/rules/require-default-props.js
lib/util/ast.js
tests/lib/rules/require-default-props.js
tests/util/ast.js

[New] `require-default-props`: add option `functions`

---

CHANGELOG.md
lib/util/propTypes.js
tests/lib/rules/prop-types.js

Fixes: #3140 
Fix is to ignore when type declarations are not present in the same file.
Turns out imported external interfaces & types were already handled by the searchDeclaration function, the error was happening because i mistakenly hardcoded `ignorePropsValidation: false` when handling the `forwardRef<element, props>` case 💀

[Fix] propType: ignore imported types/interface in forwardRef generic

---

CHANGELOG.md
lib/util/Components.js

The performance for merged rule in `Component.detect` is improved. In an end-to-end linting benchmark this change is 4% faster.
Benchmark (mean of 5 runs):
```diff
- 5.164 s
+ 4.966 s
```

[Refactor] improve performance of rule merging

---

CHANGELOG.md
lib/util/Components.js

Some node visitors for components detection are redundant.
Benchmark with `time npx eslint .` (mean of 5 runs):
```diff
- 5.06 s
+ 5.01 s
```

[Refactor] improve performance of component detection

---

CHANGELOG.md
lib/rules/jsx-tag-spacing.js
lib/util/getTokenBeforeClosingBracket.js
tests/lib/rules/jsx-tag-spacing.js

- If the node is multiline then require newline
- If the node is singleline then require space
Signed-off-by: Sebastian Malton <sebastian@malton.name>

Fix: change multiline-always to proportional-always

---

CHANGELOG.md
lib/rules/no-unstable-nested-components.js
tests/lib/rules/no-unstable-nested-components.js

Fixes https://github.com/yannickcr/eslint-plugin-react/issues/3231.
The bugfix itself is just one line since `React.memo` wrappers are already being detected as components; this plugin just wasn't searching for `CallExpression`s.
I've also updated the error message to be more specific about the recommended fix. Technically this can also be fixed by calling the function directly (`renderComponent(props)` vs `<Component {...props} />`) but I'm not sure if we want to squeeze that into the error message. 
Memoizing with `useCallback()` is not generally safe since the returned function isn't guaranteed to be stable, even if the deps are empty. I have a branch that can detect this, but that probably has other consequences so I'll leave it to a separate PR.

Improve no-unstable-nested-components error message and catch React.memo()

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/display-name.js

Fixes #3289.
Stop considering `const any = () => (props) => null` as a component.

[Fix] `display-name`: fix false positive for HOF returning only nulls

---

CHANGELOG.md
docs/rules/jsx-key.md

- clarifies these were three different examples.
- I didn't understand these were three different examples :)

Clarify the number of examples.

---

CHANGELOG.md
lib/rules/jsx-no-leaked-render.js
tests/lib/rules/jsx-no-leaked-render.js

Closes #3297
Relates to #3292
This fixes:
- adding unnecessary negation operators
- delete valid ternary branches

fix(jsx-no-leaked-render): avoid unnecessary negation operators and ternary branches deletion

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/display-name.js

Fix #3303.
PR #3276 caused the following to be considered a component, while in v7.29.0 it is not considered a component:
```js
const MemoizedMyComponent = React.memo(
MyComponent,
() => 1
)
```
This PR adds a check that the function being wrapped must return JSX to be considered a component.
The bug is so subtle and I am not sure this is the right way to fix it.

[Fix] `display-name`: fix false positive when using memo

---

CHANGELOG.md
docs/rules/jsx-newline.md
lib/rules/jsx-newline.js
tests/lib/rules/jsx-newline.js

Fixes #3033
This is an initial PR to confirm that this is the change required to allow multi-lines in the `jsx-newlines` rule.

Allow multiline JSX expressions when prevent option is true: `jsx-newline`

---

CHANGELOG.md
lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

[Fix] `jsx-no-literals`: properly error on children with noAttributeStrings: true

---

CHANGELOG.md
lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

[Fix] `jsx-key`: catch key errors inside conditional statements

---

CHANGELOG.md
tests/lib/rules/jsx-indent.js
tests/lib/rules/jsx-one-expression-per-line.js

Increased test coverage for jsx-one-expression-per-line.js 
Fixes #2318

[Tests] `jsx-indent`, `jsx-one-expression-per-line`: add passing test cases

---

CHANGELOG.md
lib/rules/display-name.js
tests/lib/rules/display-name.js

[Fix] `display-name`: Accept forwardRef and Memo nesting in newer React versions

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/display-name.js

Fixes https://github.com/jsx-eslint/eslint-plugin-react/issues/3329
Stop considering `let any; any = () => null` as a component.

[Fix] `display-name`: fix false positive for assignment of function returning null

---

lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

When an HTML entity such as &mdash; is checked with ESLint, the `value`
property becomes the actual unicode character instead of the raw
literal.
This means if `&mdash;` is in the allowed strings array, and `&mdash;`
is in the code being checked, the actual value used in the JSXText check
will be `—`, which will not match against `&mdash;`, so it causes a
false positive error.
When checking against the set of allowed strings, this will now check
both the `value` and the `raw` properties of the node. For `&mdash;`, the
`raw` property will still be `&mdash;`.
If _either_ of these match the list of allowed values, then no error
will be returned.
I am very new to the project so if this is not the right fix, I will not be offended if you close the PR. 😆 
Fixes #3130

[Fix] `jsx-no-literals`: properly handle HTML entities when allowed

---

CHANGELOG.md
docs/rules/sort-comp.md

Hello, I updated the examples for sort-comp, that were still using `createClass` with class component examples.
Cheers

[Docs] `sort-comp`: add class component examples

---

CHANGELOG.md
lib/util/isFirstLetterCapitalized.js
tests/lib/rules/display-name.js
tests/util/isFirstLetterCapitalized.js

[Fix] display-name: fix identifying `_` as a capital letter

---

CHANGELOG.md
lib/rules/require-default-props.js
tests/lib/rules/require-default-props.js

[Fix]: avoid a crash when function has no props param

---

CHANGELOG.md
docs/rules/jsx-no-useless-fragment.md

Hey @ljharb ! 👋
Just a quick PR to:
1. Add some simpler examples of how to resolve the `react/jsx-no-useless-fragment` problems when they appear (there are not as many simple examples of just removing the fragment when there's a single child)
2. Add an example with an embedded expression and ternary

[Docs] `jsx-no-useless-fragment`: add more examples of correct code

---

CHANGELOG.md
lib/rules/jsx-boolean-value.js

Attempted to define the data types of parameters expressed within functions within the jsx-boolean-value.js file.

jsx-boolean-value.js documentation

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/display-name.js

[Fix] `display-name`, component detection: fix HOF returning null as Components

---

CHANGELOG.md
docs/rules/forbid-dom-props.md
lib/rules/forbid-dom-props.js
tests/lib/rules/forbid-dom-props.js

[New] `forbid-dom-props`: add `disallowedFor` option

---

CHANGELOG.md
README.md

The `david-dm` service is no longer available, so this badge can be removed from the `README`.

Remove `david-dm` badge from `README`

---

CHANGELOG.md
lib/rules/forbid-prop-types.js
tests/lib/rules/forbid-prop-types.js

[Fix] `forbid-prop-types`: Ignore objects that are not of type React.PropTypes

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/display-name.js
tests/lib/rules/no-this-in-sfc.js

Fixes #3300.
This bug is caused by #3276.
Stop considering the following a component:
```js
const f = (a) => () => {
if (a) {
return null;
}
return 1;
};
```
The bug is triggered when a literal like `1` or `"a"` is returned somewhere.

[Fix] `display-name`: fix false positive for HOF returning only nulls and literals

---

CHANGELOG.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

Fixes [#2962](https://github.com/jsx-eslint/eslint-plugin-react/issues/2962)

[Fix] False negative when rel attribute assigned using ternary

---

CHANGELOG.md
lib/rules/jsx-no-leaked-render.js
tests/lib/rules/jsx-no-leaked-render.js

A partial fix to #3323
I welcome suggestions and help if you think it does not improve performance 🙂

[Fix] `jsx-no-leaked-render`: autofix nested "&&" logical expressions

---

CHANGELOG.md
lib/rules/jsx-closing-bracket-location.js
lib/rules/jsx-no-bind.js

[Refactor] `jsx-closing-bracket-location`, `jsx-no-bind`: fix eslint issues

---

CHANGELOG.md
tests/lib/rules/function-component-definition.js

Closes #3057
@ljharb I added the code snippets from the issue but they're passing. They were also not being auto-fixed.

[Tests] `function-component-definition`: add passing test cases 

---

CHANGELOG.md
docs/rules/jsx-no-target-blank.md

I updated the link to the "noreferrer" explanation instead of a link to the "noopener" explanation, since the paragraph where this link is located only talks about the "noreferrer".

[Docs] `jsx-no-target-blank`: Fix link to link-type-noreferrer

---

lib/rules/jsx-uses-react.js
lib/rules/jsx-uses-vars.js
package.json
tests/lib/rules/no-invalid-html-attribute.js

- Autofixed one violation
- Disabled rule for two violations due to a bug
https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/releases/tag/v5.0.0

Update eslint-plugin-eslint-plugin to v5

---

CHANGELOG.md
README.md
docs/rules/jsx-space-before-closing.md
markdown.config.js
tests/index.js

```
❌ This rule is deprecated.
```
* Standardize deprecation notice in rule docs to be more consistent with the other rule notices and add a test that it's present for deprecated rules. Note that rule-specific deprecation information is allowed at the end of the line for this notice.
* In the README rules list, mention if a rule is deprecated next to its description. Note that I chose not to add a deprecation column like the other columns we have for recommended/fixable/suggestable because I didn't want to waste more horizontal width on this for something that is probably rare. We can always switch to a separate column in the future if needed.
Extracted from this PR: #3362

[Docs] Standardize deprecated rule notice

---

CHANGELOG.md
docs/rules/jsx-curly-brace-presence.md
docs/rules/jsx-no-useless-fragment.md

Follow-up to #3359.
I accidentally left two old-style fixable rule notices in place. The replacement fixable notice is at the top.

[Docs] Remove duplicate fixable notice

---

CHANGELOG.md
docs/rules/jsx-pascal-case.md
docs/rules/jsx-props-no-spreading.md
docs/rules/no-arrow-function-lifecycle.md
docs/rules/no-unstable-nested-components.md
docs/rules/sort-prop-types.md
lib/rules/jsx-curly-brace-presence.js
lib/rules/no-access-state-in-setstate.js
lib/rules/no-danger.js
lib/rules/no-direct-mutation-state.js
lib/rules/no-unescaped-entities.js
lib/rules/no-unstable-nested-components.js
lib/rules/prefer-stateless-function.js
lib/util/Components.js
lib/util/ast.js
lib/util/propTypesSort.js
tests/lib/rules/no-typos.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prefer-stateless-function.js
tests/lib/rules/prop-types.js
tests/lib/rules/require-optimization.js
tests/lib/rules/static-property-placement.js
tests/util/ast.js

I went through hundreds of potential spelling mistakes flagged by running variations of this [cspell](https://www.npmjs.com/package/cspell) command:
```
cspell "{lib,test,tests}/**/*.{js,ts,md}"
```
This is not something we can enforce on CI due to the hundreds of false positives from names and other technical API words not in the dictionary. It's worth running manually every once in a while.
I do however recommend the [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension for VSCode to find mistakes while coding.

Fix typos in documentation

---

CHANGELOG.md
lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

Fixes https://github.com/jsx-eslint/eslint-plugin-react/issues/2366
Previously comments were not sorted with rule.
With fix, comments are included during sort.
Special Attribute Conditions:
- if comment found between two attributes, attributes and comment are sorted to end (to be manually sorted if necessary)
- above condition also applies to block comments
- single-line comments on same attribute-line are sorted

[Fix] `jsx-sort-props`: sorted attributes now respect comments

---

CHANGELOG.md
docs/rules/jsx-key.md
lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

Closes #3368 
Now the `jsx-key` rule will catch these invalid cases:
```
Array.from([1, 2 ,3], function(x) { return <App /> });
Array.from([1, 2 ,3], (x => { return <App /> }));
Array.from([1, 2 ,3], (x => <App />));
```
and will allow these valid cases:
```
Array.from([1, 2, 3], function(x) { return <App key={x} /> });
Array.from([1, 2, 3], (x => <App key={x} />));
Array.from([1, 2, 3], (x => {return <App key={x} />}));
Array.from([1, 2, 3], someFn);
Array.from([1, 2, 3]);
```
In addition, I did some refactoring to keep the code DRY (the checking for keys in `Array.prototype.map` and `Array.from` had many repetitions).

[Fix] `jsx-key` not detecting missing keys in `Array.from`'s mapping function

---

CHANGELOG.md
docs/rules/jsx-no-leaked-render.md
lib/rules/jsx-no-leaked-render.js
tests/lib/rules/jsx-no-leaked-render.js

Closes #3354 
Now, when the `jsx-no-leaked-render` has `{validStrategies: ['coerce']}`, the following code is considered as valid and therefore is not autofixed:
```jsx
{ foo ? <Component1 /> : <Component2 />}
```

[Fix] `jsx-no-leaked-render` autofixed JSXElements away in coerce strategy

---

.github/workflows/smoke-test.yml

See https://github.com/jsx-eslint/eslint-plugin-react/issues/3371#issuecomment-1229383022.

[actions] update `eslint-remote-tester-run-action`

---

CHANGELOG.md
docs/rules/jsx-sort-props.md

Just rewriting `ref` props using `ref` variables.

[Docs] Replacing legacy ref string with ref variable

---

CHANGELOG.md
docs/rules/no-unknown-property.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

Closes #757 by...
- renaming an old error message (`unknownProp` to `unknownPropWithStandardName`), since it reports an unknown property that is close (one lower/higher case letter) to an allowed (standard) name
- adding a new error message (`unknownProp`) that is used when an unknown property (without a 
- listing all one word and multiple word valid HTML/DOM attributes, and `aria-*` attributes
- adding a function that checks if attribute name is a valid `data-*` attribute
- adding more unit test cases
- moving one test that should have failed, from valid to invalid tests
- updating rule documentation
What was not implemented in this PR:
- mapping element specific tags to `ATTRIBUTE_TAGS_MAP` (e.g. attributes `optimum`, `high` and `low` should be used only on `<meter>` element)
While …

[Fix] `no-unknown-property`: properly recognise unknown HTML/DOM attributes

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

fixes https://github.com/jsx-eslint/eslint-plugin-react/issues/3380
I don't know if the added attributes are exhaustive or not. I sure hope MDN covered all possible attributes.

[Fix] no-unknown-property: No unknown property doesn't recognize svg properties

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

Closes  #3397 by
- fixing the typo in `controlList` to `controlsList`
Closes #3400 by
- by adding many `xxxYyyCapture` properties
In addition:
- adds [`manifest`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1beed2ef47be5c1c283132c6cdfbd806ad0fb4ae/types/react/index.d.ts#L1967), [`results`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1beed2ef47be5c1c283132c6cdfbd806ad0fb4ae/types/react/index.d.ts#L1894), [`security`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1beed2ef47be5c1c283132c6cdfbd806ad0fb4ae/types/react/index.d.ts#L1895), [`summary`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1beed2ef47be5c1c283132c6cdfbd806ad0fb4ae/types/react/index.d.ts#L2011) and [`wmode`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1beed2ef47be5c1c283 …

[Fix] `no-unknown-property`: add more capture event properties

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

This pull requests allows `imageSrcSet` and `imageSizes` on the `<link />` element, as these properties are actually valid and allowed:
* MDN Docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-imagesrcset
* React typings: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2276
This is a fix for #3401

[Fix] `no-unknown-property`: allow `imageSrcSet` and `imageSizes` attributes on `<link>`

---

CHANGELOG.md
package.json

Perhaps a `"files"` key in package.json is a better idea than expanding the `"ignore"` list again. But I'll leave that to the maintainer.

Don't add markdownlint config to NPM package

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

Fixes #3418
[https://www.w3resource.com/html/attributes/html-abbr-attribute.php]()

[Fix] `no-unknown-property`: allow `abbr` on `<th>` and `<td>`

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

Adds the rest of the tags, where `viewBox` can be used 
Ref: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/viewBox

[Fix] no-unknown-property `viewBox` for `pattern`, `symbol`, `view`

---

CHANGELOG.md
lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

`jsx-key` rule should always succeed if we're inside `React.Children.toArray()` because omitting `key` there doesn't cause a React warning.
Fixes #1574.

Ignore jsx-key if inside React.Children.toArray()

---

CHANGELOG.md
docs/rules/no-unknown-property.md

Removes a parenthesis in the link to emotion's CSS prop docs.

[Docs] `no-unknown-property`: fix typo in link

---

CHANGELOG.md
lib/rules/jsx-no-constructed-context-values.js
tests/lib/rules/jsx-no-constructed-context-values.js

[Fix] `jsx-no-constructed-context-values`: fix false positive for usage in non-components

---

CHANGELOG.md
lib/util/Components.js

Profiler shows it's about 2% faster overall.

[Perf] improve performance by optimizing getId

---

lib/util/isCreateElement.js

This change makes `eslint .` run about 4% faster by optimizing `isCreateElement`.

[Perf] improve performance for rules using isCreateElement

---

CHANGELOG.md
docs/rules/no-unstable-nested-components.md
tests/lib/rules/no-unstable-nested-components.js

The issue this rule catches is a very common beginner issue that requires understanding of the reconciler. Ideally this issue wouldn't exist but until then let's make sure you start out with a linter that catches these issues.
I adjusted the docs to no longer recommend memoizing nested component and document migration strategies.
/cc @gaearon

[Docs] `no-unstable-nested-components`: Warn about memoized, nested components

---

CHANGELOG.md
docs/rules/hook-use-state.md
lib/rules/hook-use-state.js
tests/lib/rules/hook-use-state.js

This PR fixes https://github.com/jsx-eslint/eslint-plugin-react/issues/3443 by adding a new option to the rule.
I want to be sure that I'm on the right path, so I could add fixes later.

[New] `hook-use-state`: add `allowDestructuredState` option

---

CHANGELOG.md
README.md
docs/rules/sort-default-props.md
index.js
lib/rules/sort-default-props.js
tests/lib/rules/sort-default-props.js

[New] add `sort-default-props` and deprecate `jsx-sort-default-props`

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/destructuring-assignment.js

This change makes an `eslint .` with `plugin:react/all` enabled run about 13% faster.

[Perf] component detection: improve performance by avoiding traversing parents unnecessarily

---

CHANGELOG.md
README.md
configs/all.js
docs/rules/no-object-type-as-default-prop.md
lib/rules/no-object-type-as-default-prop.js
tests/lib/rules/no-object-type-as-default-prop.js

Discussed in 
https://github.com/yannickcr/eslint-plugin-react/issues/2847
```
npm run lint
npm run test
```
shows no errors and warnings
---

[New] add `no-object-type-as-default-prop` rule

---

CHANGELOG.md
README.md
docs/rules/sort-prop-types.md
lib/rules/sort-prop-types.js
lib/util/propTypesSort.js
tests/lib/rules/sort-prop-types.js

All tests cases currently pass.
Fixed typos in test cases. Concatenated all invalid tests.

[Fix] sort props test cases

---

.github/workflows/npm-publish.yml

This PR adds a GitHub Actions workflow to publish to npm registry using one-time password (OTP). 
- Runs on workflow dispatch and expects a tag
- It checks that the tag follows semver pattern and version has not been published before to npm registry
- Checks that required checks have run and passed when the tag was pushed
- Uses `step-security/wait-for-secrets` so OTP can be sent to the workflow
It requires setting two secrets:
1. `NODE_AUTH_TOKEN` - this should be a Publish token for npm registry. The package should have `require two-factor authentication to publish` checked in the package settings. 
2. `SLACK_WEBHOOK_URL` - this is to get notification on Slack when OTP needs to be entered. If this notification is not needed, I can remove this part from the workflow. 
I have also added …

[actions]: Add npm publish workflow

---

CHANGELOG.md
docs/rules/forbid-component-props.md

Hello! Love this plugin! Just noticed an opportunity to make the language a bit more inclusive in the docs for the rule `forbid-component-props` by switching to the term "allowlist", as other projects have been doing lately. Up to the maintainers though! Thanks.
Side note: Have we considered opting this repository into Hacktoberfest? Simply adding the `hacktoberfest` topic to the repo will allow contributors to get credit for their changes! https://hacktoberfest.com/participation/ Thanks again!

docs: inclusive language w/ allowlist

---

CHANGELOG.md
docs/rules/jsx-key.md
lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

Fixes https://github.com/jsx-eslint/eslint-plugin-react/issues/3481
I've also updated the docs to stay consistent with the comment from below `In the last example the key is being spread...`

[Fix] `jsx-key`: detect keys in logical expression and conditional expression

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

Currently `<fbs>` nodes are tagged with this linter warning:
```
Unknown property 'desc' foundNuclide-ESLint[react/no-unknown-property](https://www.internalfb.com/intern/bunny?q%3Deslint%2Breact%2Fno-unknown-property)
```
`<fbt>` nodes are already exempt from this lint rule, and `<fbs>` should be treated the same. 
Internal WP discussion: https://fb.workplace.com/groups/eslintfeedback/permalink/6064426636924059/

[Fix] `no-unknown-property`: do not check `fbs` elements

---

CHANGELOG.md
lib/rules/jsx-newline.js
tests/lib/rules/jsx-newline.js

Fixes #3478 and  #2926 and adds a couple more tests to show what was failing.
From what I can gather this should be the default behaviour. If not then then this can be hidden behind an option.
I was not sure about the behaviour of multiple Block comments before a Multiline Component. Decided the comments should stick together, based on sujan-s comment in #3478.

[Fix] `jsx-newline`: No newline between comments and jsx elements

---

CHANGELOG.md
lib/rules/jsx-no-leaked-render.js
tests/lib/rules/jsx-no-leaked-render.js

jsx-no-leaked-render: Don't report errors on empty strings if React >= v18

---

CHANGELOG.md
docs/rules/jsx-no-leaked-render.md

Ref: https://github.com/jsx-eslint/eslint-plugin-react/pull/3203#issuecomment-1282517969
Also cleans up some formatting in the JSX examples

Remove mentions of empty strings for React 18

---

CHANGELOG.md
docs/rules/sort-prop-types.md
lib/util/propTypesSort.js
tests/lib/rules/sort-prop-types.js

Fixes https://github.com/jsx-eslint/eslint-plugin-react/issues/3470
Now rule respects multiple comments before and after prop.
Fixes issue of no comments before and after prop not being considered during parsing.

[Fix] `sort-prop-types`: avoid crash when autofixing

---

CHANGELOG.md
docs/rules/prefer-exact-props.md

[Docs] Correct example for prefer-exact-props rule

---

CHANGELOG.md
lib/rules/jsx-no-leaked-render.js
tests/lib/rules/jsx-no-leaked-render.js

[Fix] `jsx-no-leaked-render`: invalid fixes in coerce mode

---

lib/rules/destructuring-assignment.js
tests/lib/rules/destructuring-assignment.js

i reopen PR on resolve issue - #2309 cause i did a lot of commits while editing.
* add rule of handling destructuring of useContext in SFC
* delete detecting variable named 'context' in SFC
Fixes #2309. Closes #2787.

[Fix] `destructuring-assignment`: Handle destructuring of useContext in SFC

---

package.json

Bumps version of `eslint-remote-tester-repositories` to new major. No breaking changes. API is now considered as stable.
Related to https://github.com/jsx-eslint/eslint-plugin-react/issues/3513.

[Dev Deps] update `eslint-remote-tester-repositories`

---

README.md

Quick PR to update the link to `eslint-plugin-jsx-a11y` in the README.

Update link to `eslint-plugin-jsx-a11y` in README

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

Similar to https://github.com/jsx-eslint/eslint-plugin-react/issues/3416 but for fill of marker
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker
```jsx
error  Invalid property 'fill' found on tag 'marker', but it is only allowed on: altGlyph, circle, ellipse, g, line, mask, path, polygon, polyline, rect, svg, text, textPath, tref, tspan, use, animate, animateColor, animateMotion, animateTransform, set  react/no-unknown-property
<marker fill='#000' />
```

[Fix] no-unknown-property `fill` for `marker`

---

CHANGELOG.md
docs/rules/no-array-index-key.md
lib/rules/no-array-index-key.js
tests/lib/rules/no-array-index-key.js

The rule currently considers `.map()` but not `.flatMap()`

consider flatMap for no-array-index-key

---

CHANGELOG.md
docs/rules/display-name.md
lib/rules/display-name.js
lib/util/isCreateContext.js
tests/lib/rules/display-name.js

I'm proposing adding a new rule that checks if the `displayName` property is set for context objects, see [`Context.displayName`](https://reactjs.org/docs/context.html#contextdisplayname) in the React docs.
With multiple Context providers in an app, consistently setting a `displayName` makes it easy to see which is which in the React dev tools.
Some things to consider
* Should it perhaps be part of the `display-name` rule instead of a separate rule?
* Does it need more tests?
* Does this checking approach make sense? (This is my first time writing an ESLint rule, so I wouldn't be surprised if this is not the best way)
* Does it need to check more cases?

[New] `checkContextObjects` option in `display-name`

---

CHANGELOG.md
lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

fix https://github.com/jsx-eslint/eslint-plugin-react/issues/3537

[Fix] `jsx-curly-brace-presence`: handle single and only expression template literals

---

CHANGELOG.md
docs/rules/jsx-first-prop-new-line.md
lib/rules/jsx-first-prop-new-line.js
tests/lib/rules/jsx-first-prop-new-line.js

The `jsx-first-prop-new-line` rule is great but it just falls short in one place for me. This addition allows the rule to enforce a new line, but only if there are multiple props, else it forces it inline - a hybrid between `multiline` and `multiline-multiprop`.
Before Linting (currently the div element thinks that it is valid, but I want it to throw a linting error)
After Linting (the div is automatically formatted to put the prop on the first line, but the component below is kept multiline)
(I hope I've formatted this okay as I couldn't find a template for PRs)

[New] `jsx-first-prop-new-line`: add `multiprop` option

---

CHANGELOG.md
docs/rules/no-deprecated.md
lib/rules/no-deprecated.js
tests/lib/rules/no-deprecated.js

The list of deprecated APIs in React 18.0.0:
- react-dom: `ReactDOM.render`
- react-dom: `ReactDOM.hydrate`
- react-dom: `ReactDOM.unmountComponentAtNode`
- react-dom/server: `ReactDOMServer.renderToNodeStream`
Ref: https://github.com/facebook/react/blob/main/CHANGELOG.md#deprecations
Migration guide: https://beta.reactjs.org/blog/2022/03/08/react-18-upgrade-guide

[New] Align `no-deprecated` rule with React 18 deprecations

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

this adds `fill` to the list of allowed props for `<symbol>` in `no-unknown-props`. see https://developer.mozilla.org/en-US/docs/Web/SVG/Element/symbol#global_attributes

[Fix] `no-unknown-property`: allow `fill` prop on `<symbol>`

---

CHANGELOG.md
docs/rules/forbid-component-props.md
lib/rules/forbid-component-props.js
tests/lib/rules/forbid-component-props.js

[New] `forbid-component-props`: add `disallowedFor` option

---

CHANGELOG.md
docs/rules/forbid-component-props.md
lib/rules/forbid-component-props.js
tests/lib/rules/forbid-component-props.js

My use case is component props: I am using a component system (Antd) and want to disallow the `required` parameter on `Form.Item` to avoid confusion with a `require` parameter in HOCs that we create.
I found #3422 already existing, so this is a PR to solve that, as well as adding `allowList` to `forbid-dom-props` for symmetry.
I haven't yet figured out what the best way is to raise configuration issues, right now I'm just throwing an error, let me know if there's a better way!
(Motivation details: in Antd `require` only controls styling, and doesn't actually validate, in our HOCs I want it to validate, but don't want that confusion to bleed over into using `require` in the base (non-HOC) `Form.Item`s)

Add `disallowedFor` to `forbid-component-props` and `allowedFor` to `forbid-dom-props`

---

CHANGELOG.md
docs/rules/jsx-newline.md
docs/rules/no-unsafe.md
docs/rules/static-property-placement.md

I fixed the issue with code syntax highlighting that caused a red background line to appear.
Before
After

[Docs] Fix code syntax highlighting

---

CHANGELOG.md
lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js

[Fix] `no-unused-prop-types`: returns no errors when using the spread operator in JSX element

---

CHANGELOG.md
README.md

Hi, 
When I run `eslint` on some React files, this is what I get:
```bash
$ npm run lint:js
> @gokaygurcan/test@1.0.0 lint:js
> eslint --config .eslintrc --color .
Warning: React version not specified in eslint-plugin-react settings. See https://github.com/jsx-eslint/eslint-plugin-react#configuration .
```
And the given URL resolves the repository, but doesn't scroll to the anchored place because of this change: https://github.com/jsx-eslint/eslint-plugin-react/commit/17858beeedaaf5d0eb4fd1cc292fb34d07f9f659#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R20 
This PR is here to fix the URL and point the correct location.
I hope this makes sense. Thanks in advance for your consideration.
Best,
G.

[Fix] update configuration URL

---

CHANGELOG.md
lib/rules/destructuring-assignment.js
tests/lib/rules/destructuring-assignment.js

It seems that the use of modern context is forced to use the destructuring assignment after #2797; the problem was raised in #3536. 
~~This PR introduces additional flag that won't affect the existing behavior when it is unset, but will allow users to upgrade the lib version without having this rule disabled.~~
The approach was reviewed and now it consists of the following:
1. #2797 changes were reverted
2. Additional test cases were added in order to make sure that the value returned from `useContext` could now be used both with destructuring and without it
Fixes #3536

[Fix] `destructuring-assignment`: remove `useContext` destructuring check

---

CHANGELOG.md
docs/rules/jsx-no-bind.md

I'm proposing rewording the rationale for jsx-no-bind to:
* clarify that the performance concerns apply to specific situations; although it's qualified, the statement "is bad for performance" is a general statement and [not strictly accurate](https://react.dev/reference/react/memo#skipping-re-rendering-when-props-are-unchanged)
* refer explicitly to `memo` since I think `memo`ised components are probably the most common component with performance impacts from this rule
* include the fact that this rule also covers any function declared in the render method of a component, including both anonymous or named functions, not just arrow or bound functions, as shown in the examples

Reword jsx-no-bind rationale

---

CHANGELOG.md
docs/rules/prefer-read-only-props.md
lib/rules/prefer-read-only-props.js
tests/lib/rules/prefer-read-only-props.js

Fixes #3535 
Adds TypeScript support to `prefer-read-only-props` rule.

[Fix] `prefer-read-only-props`: Add TypeScript Support

---

CHANGELOG.md
docs/rules/jsx-first-prop-new-line.md

Added missing possible value, The value is listed near the top of the docs document, but not near the bottom

[Docs] `jsx-first-prop-new-line`: add missing multiprop value

---

CHANGELOG.md
lib/rules/require-default-props.js

Fix #3604 
Removes extraneous “allow” keyword from JSON schema definition. I couldn’t find any references to this keyword in JSON schema, nor documentation on its purpose, but it seems to break the TypeScript definitions generated in projects like [eslint-define-config](https://github.com/Shinigami92/eslint-define-config).
If the “allow” keyword has a purpose here that I’m not aware of, please feel free to close this PR.

[Fix] `require-default-props`: fix config schema

---

CHANGELOG.md
lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

This reverts https://github.com/jsx-eslint/eslint-plugin-react/pull/3538, while keeping the test case there for explanation and future breakage prevention.
The previous commit broke for intended type casting usage: https://github.com/jsx-eslint/eslint-plugin-react/issues/3607
Sorry for adding the change, did not think enough before making it, apparently this is definitely legit use case for casting other type to string, we might be able to keep this rule and limit it to string single template literal with typechecker, but just a bit overkill at this moment.

fix: revert single template literal expression which might be intended usage

---

CHANGELOG.md
lib/rules/sort-prop-types.js
lib/util/propTypesSort.js
tests/lib/rules/sort-prop-types.js

Fixes https://github.com/jsx-eslint/eslint-plugin-react/issues/3591

Fix `noSortAlphabetically` not respected in `sort-prop-types`

---

.github/workflows/release.yml

These commands were deprecated awhile back, removing them will also get rid of the warnings in the run log.
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

[actions] Replace `set-output` commands with environment files

---

CHANGELOG.md
lib/rules/no-deprecated.js
tests/lib/rules/no-deprecated.js

[Fix] `no-deprecated`: false positive on commonjs import in `no-deprecated` rule

---

CHANGELOG.md
docs/rules/sort-prop-types.md
lib/rules/sort-prop-types.js
tests/lib/rules/sort-prop-types.js

This PR is an attempt to solve #3578

[New] `sort-prop-types`: give errors on TS types

---

CHANGELOG.md
lib/rules/jsx-no-leaked-render.js
tests/lib/rules/jsx-no-leaked-render.js

[Fix] `jsx-no-leaked-render`: preserve RHS parens for multiline jsx element while fixing

---

.github/workflows/smoke-test.yml

Adds issue labels for smoke tests. This allows renaming the issues created by bot, and still be able to receive next week's results on the same issue.
- Ref. https://github.com/jsx-eslint/eslint-plugin-react/issues/3637
- Ref. https://github.com/jsx-eslint/eslint-plugin-react/issues/3632
Updates `eslint-remote-tester-run-action` from v3 to v4.1:
- https://github.com/AriPerkkio/eslint-remote-tester-run-action/releases/tag/v4
- https://github.com/AriPerkkio/eslint-remote-tester-run-action/releases/tag/v4.1.0

[actions]: use issue label on smoke tests

---

CHANGELOG.md
lib/rules/no-invalid-html-attribute.js
tests/lib/rules/no-invalid-html-attribute.js

Currently this attribute fails on the latest version:
```
“apple-touch-startup-image” is never a valid “rel” attribute value  react/no-invalid-html-attribute
```
According to [the docs](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/no-invalid-html-attribute.md) the accepted values for this rule come from MDN, and MDN states that this value is [non-standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel) but not disallowed, the same as `apple-touch-icon`.
If I am incorrect here please let me know.
To test this I've added a generic example as seen in [Apple's own documentation](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_r …

[New] `no-invalid-html-attribute`: add support for `apple-touch-startup-image` `rel` attributes in `link` tags

---

CHANGELOG.md
lib/rules/boolean-prop-naming.js
lib/rules/function-component-definition.js
lib/rules/jsx-props-no-multi-spaces.js
lib/util/propTypes.js

First of a two part pr to transition to `typeArguments` and fallback to `typeParameters` for `@typescript-eslint` `v6`.
This pr extracts type parameters to a variable before being used.
Second part can be found: #3629

[Refactor] extract type parameters to a variable

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

The `math` element supports a property called `displaystyle` which is not currently recognized by the `no-unknown-property` rule.
https://developer.mozilla.org/en-US/docs/Web/MathML/Global_attributes/displaystyle

Add displaystyle as known property on math elements

---

CHANGELOG.md
lib/util/Components.js
tests/lib/rules/prefer-read-only-props.js
tests/lib/rules/prop-types.js

React introduced server components, now async functions can be components.
Closes #3653

[New] `prefer-read-only-props`, `prop-types`, component detection: allow components to be async functions

---

CHANGELOG.md
docs/rules/jsx-key.md

In the 3rd item of the correct example, `x.id` is used as the key. However, since an number type array is entered in Array.from, x is a number, all keys have undefined. Additionally, searching the number property is generally considered an error in TypeScript.
Therefore, the key was modified to use `x` itself so that the key has a unique value and does not cause an error in TypeScript.

[Docs] `jsx-key`: fix correct example

---

CHANGELOG.md
docs/rules/jsx-wrap-multilines.md
lib/rules/jsx-wrap-multilines.js
tests/lib/rules/jsx-wrap-multilines.js

Fixes #1035 
First PR here so if I'm missing anything please let me know!
(Also I'm aware this particular option is very controversial, please don't hate me 😇)

[New] `jsx-wrap-multilines`: add `never` option to prohibit wrapping parens on multiline JSX

---

CHANGELOG.md
docs/rules/jsx-filename-extension.md
lib/rules/jsx-filename-extension.js
tests/lib/rules/jsx-filename-extension.js

[New] `jsx-filename-extension`: add `ignoreFilesWithoutCode` option to allow empty files

---

CHANGELOG.md
docs/rules/jsx-boolean-value.md
lib/rules/jsx-boolean-value.js
tests/lib/rules/jsx-boolean-value.js

Fixes https://github.com/jsx-eslint/eslint-plugin-react/issues/3234
A new option has been added referring to the comments on this issue.
I think there are some parts that need explanation, so I'll list them below.
1. As you can see in the test case, if you remove both properties and values, a space remains, but that space can be modified with other rules such as jsx-props-no-multi-spaces, so it was left behind.
2. While adding new options, I noticed that there was some issue with the options in the error message. After setting never or always in the second option, if the modification is made not only to the first option but also to the second option, an error message containing the properties of the second option is displayed as shown below. If it is confirmed to be an issue, a new mr …

[New] `jsx-boolean-value`: add `assumeUndefinedIsFalse` option

---

CHANGELOG.md
README.md
docs/rules/jsx-no-script-url.md
lib/rules/jsx-no-script-url.js
lib/rules/jsx-no-target-blank.js
lib/util/linkComponents.js
tests/lib/rules/jsx-no-script-url.js
tests/lib/rules/jsx-no-target-blank.js
tests/util/linkComponents.js

[jsx-no-script-url]: use shared settings to specify link components

---

CHANGELOG.md
docs/rules/jsx-one-expression-per-line.md
lib/rules/jsx-one-expression-per-line.js
tests/lib/rules/jsx-one-expression-per-line.js

[New] `jsx-one-expression-per-line`: add `non-jsx` option to allow non-JSX children in one line

---

CHANGELOG.md
lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Fix #3521
- Modified to allow an exception that skips the type check of memo when forwardRef and memo are nested.
- forwardRef, memo, forwardRef with memo testcase add

[Fix] `prop-types`: handle nested forwardRef + memo

---

CHANGELOG.md
docs/rules/hook-use-state.md

[Docs] `hook-use-state`: fix an undefined variable

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

See:
- [HTML Standard](https://html.spec.whatwg.org/multipage/indices.html#attributes-3:~:text=Sets%20the%20priority%20for%20fetches%20initiated%20by%20the%20element)
- [mdn](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/fetchpriority)
- DefinitelyTyped/DefinitelyTyped#68645

[Fix] `no-unknown-property`: add `fetchPriority`

---

configs/all.js
lib/rules/index.js

Figured I'd split this out of #3694
This PR adds a few JSDoc type annotations to hint to TS what the types are. This helps work-around issues like https://github.com/typescript-eslint/typescript-eslint/issues/8522 / https://github.com/microsoft/TypeScript/issues/57460 where TS would infer the wrong type from the JS and would break strictly-typed config files.

[Fix] add a few jsdoc type annotations to work around TS inference bugs for consumers

---

CHANGELOG.md
lib/rules/jsx-boolean-value.js
tests/lib/rules/jsx-boolean-value.js

As mentioned in #3675, jsx-boolean-value error message is not clear.
in current code, after setting never or always in the second option, if the modification is made not only to the first option but also to the second option, an error message containing the properties of the second option is displayed as shown below. 
```
{
code: '<App foo={true} bar={true} baz />;',
output: '<App foo bar baz={true} />;',
options: ['always', { never: ['foo', 'bar'] }],
errors: [
{
messageId: 'omitBoolean',
data: { exceptionsMessage: ' for the following props: `foo`, `bar`' },
},
{
messageId: 'omitBoolean',
data: { exceptionsMessage: ' for the following props: `foo`, `bar`' },
},
{
messageId: 'setBoolean',
data: { exceptionsMessage: ' for the following props: `foo`, `bar`' },
// setBoolean attribute is not …
```

[Fix] `jsx-boolean-value`: make error messages clearer

---

CHANGELOG.md
lib/rules/jsx-no-leaked-render.js
tests/lib/rules/jsx-no-leaked-render.js

Closes #3698
In jsx-no-leaked-render rule, `connection && (hasError || hasErrorUpdate)` code is changed to `!!connection && hasError || hasErrorUpdate` but two code is not equal. 
so if right exprssion's(`(hasError || hasErrorUpdate)`) type is LogicalExpression, add parentheses both side

[Fix] `jsx-no-leaked-render`: prevent wrongly adding parens

---

CHANGELOG.md
lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

related to #3285
in this issue I found four error case. The test case is below:
```
interface Props {
enabled: boolean
}
const Hello = (props: Props) => <div />;
```
```
const Hello = (props: {enabled:boolean}) => <div />;
```
```
type Props = {
enabled: boolean
}
const Hello = (props: Props & BaseProps) => <div />;
```
```
type Props = {
enabled: boolean
}
const Hello: React.FC<Props> = (props) => <div />;
```
Currently, PR is working on the first case fix that corrects the interface error, which is the main content raised in the issue.
I think the code needs to be modified so that all test cases succeed, but it seems like there is many cases to work on at once in this PR, so I am wondering whether this should be done in one PR, or if it can be done in a different PR for each test case.

[Fix] `boolean-prop-naming`: detect TS interfaces

---

CHANGELOG.md
lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

related #3285 As mentioned in #3701, the rule is modified to apply even when the type of props is directly specified.
```
const Hello = (props: {enabled:boolean}) => <div />;
```

[Fix] `boolean-prop-naming`: literalType error fix

---

CHANGELOG.md
lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

fix literal TSIntersectionType not allow error like below test case
```
type Props = {
enabled: boolean
}
type BaseProps = {
semi: boolean
}
const Hello = (props: Props & BaseProps) => <div />;`
```
and left one error test case messioned in #3701 is exsit in test code 
```
type Props = {
enabled: boolean
}
const Hello: React.FC<Props> = (props) => <div />;
```
so I think this pr is merged, the issue #3285 can be closed.

[Fix] `boolean-prop-naming`: literal TSIntersectionType not allow error fix

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

This fixed behaviour with the `requireDataLowercase` option enabled:
1. For standard HTML elements, a attribute named `dataNotAnDataAttribute` now raises `unknownProp` instead of `dataLowercaseRequired`.
2. For React components, a attribute named `dataNotAnDataAttribute` no longer raise an error.
Also, I removed one useless capture group in this regexp.
Fixes: https://github.com/jsx-eslint/eslint-plugin-react/issues/3712

[Fix] `no-unknown-property`: only match `data-*` attributes containing `-`

---

CHANGELOG.md
lib/rules/checked-requires-onchange-or-readonly.js
tests/lib/rules/checked-requires-onchange-or-readonly.js

Fixed options taht were behaving opposite to their meanings

[Fix] `checked-requires-onchange-or-readonly`: correct options that were behaving opposite

---

CHANGELOG.md
lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

related #3717
I think cause of bug  is no concider below case
```
type Props = {
enabled: boolean
}
const Hello = (props: Props & {
semi: boolean
}) => <div />;
```
To explain in detail, if the type is not `TSTypeReference` (literal type, etc.), a reference error appears to have occurred because there is no typeName property.
Therefore, if it is not the corresponding type, the type has been modified to be used as is rather than taken from objectTypeAnnotations.

[Fix] `boolean-prop-naming`: avoid a crash with a non-TSTypeReference type

---

CHANGELOG.md
lib/rules/jsx-no-leaked-render.js
tests/lib/rules/jsx-no-leaked-render.js

[Fix] `jsx-no-leaked-render`: invalid report if left side is boolean

---

CHANGELOG.md
lib/util/propTypes.js
tests/lib/rules/prop-types.js

I'm getting this error while linting some valid React/TS code after upgrading to the latest version (`7.34.2`):
<details>
<summary>Stack trace</summary>
```
Oops! Something went wrong! :(
ESLint: 8.57.0
TypeError: Missing required argument: node.
Occurred while linting ./OptionsTable.tsx:599
Rule: "react/display-name"
at SourceCode.getScope (./node_modules/eslint/lib/source-code/source-code.js:773:19)
at getScope (./node_modules/eslint-plugin-react/lib/util/eslint.js:19:23)
at resolveValueForIdentifierNode (./node_modules/eslint-plugin-react/lib/util/propTypes.js:378:21)
at buildReactDeclarationTypes (./node_modules/eslint-plugin-react/lib/util/propTypes.js:420:5)
at ./node_modules/eslint-plugin-react/lib/util/propTypes.js:788:39
at iterateProperties …
```

[Fix] Null check `rootNode` before calling `getScope` with it

---

CHANGELOG.md
lib/rules/jsx-boolean-value.js
tests/lib/rules/jsx-boolean-value.js

assumeUndefinedIsFalse should not affect the behaviour of props with true values when we have the "never" setting

[Fix] `jsx-boolean-value`: `assumeUndefinedIsFalse` with `never` must not allow explicit `true` value

---

CHANGELOG.md
lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

[Fix] `jsx-key`: incorrect behavior for `checkKeyMustBeforeSpread` with map callbacks

---

CHANGELOG.md
lib/util/propTypes.js
tests/lib/rules/prop-types.js

[Fix] prop-types: `className` missing in prop validation

---

CHANGELOG.md
lib/rules/sort-prop-types.js
tests/lib/rules/sort-prop-types.js

Fixes the bug reported in [this comment](https://github.com/jsx-eslint/eslint-plugin-react/issues/3763#issuecomment-2215163106)

[Fix] `sort-prop-types`: Check for undefined before accessing `node.typeAnnotation.typeAnnotation`

---

.eslint-doc-generatorrc.js
.eslintrc
CHANGELOG.md
README.md
configs/all.js
configs/jsx-runtime.js
configs/recommended.js
index.js
lib/rules/index.js
package.json
tests/fixtures/flat-config/config-all/eslint.config-deep.js
tests/fixtures/flat-config/config-all/eslint.config-root.js
tests/fixtures/flat-config/config-all/test.jsx
tests/fixtures/flat-config/config-jsx-runtime/eslint.config-deep.js
tests/fixtures/flat-config/config-jsx-runtime/eslint.config-root.js
tests/fixtures/flat-config/config-jsx-runtime/test.jsx
tests/fixtures/flat-config/config-recommended/eslint.config-deep.js
tests/fixtures/flat-config/config-recommended/eslint.config-root.js
tests/fixtures/flat-config/config-recommended/test.jsx
tests/fixtures/flat-config/plugin-and-config/eslint.config-deep.js
tests/fixtures/flat-config/plugin-and-config/eslint.config-root.js
tests/fixtures/flat-config/plugin-and-config/test.jsx
tests/fixtures/flat-config/plugin/eslint.config.js
tests/fixtures/flat-config/plugin/test.jsx
tests/flat-config.js

fixes #3693
This PR exposes the flat configs at the root of the plugin:
```js
const reactPlugin = require('eslint-plugin-react');
module.exports = [
// ...
reactPlugin.configs['flat/recommended'],
// ...
];
```
The `flat/` prefix is an approach a number of plugins are taking to enable supporting both styles at the top-level.
---
This was the easiest way to set things up so that the plugin reference was consistent across the root and all configs.
I'm open to a different approach to fixing the issue - for example if you want to ensure the `config/` exports all work as well - it's just going to be a much larger refactor to make that work because we need to restructure the configs so there isn't a cyclic dependency between the configs and the plugin.
*Personally* I'm of the opinion that this …

[New] export flat configs from plugin root and fix flat config crash

---

CHANGELOG.md
docs/rules/forbid-component-props.md
lib/rules/forbid-component-props.js
tests/lib/rules/forbid-component-props.js

Add `propNamePattern` option to allow / disallow prop name patterns
Closes #3681

[New]`forbid-component-props`: add `propNamePattern` option

---

CHANGELOG.md
docs/rules/jsx-handler-names.md
lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

[New] `jsx-handler-names`: support ignoring component names

---

CHANGELOG.md
lib/rules/jsx-max-depth.js
lib/rules/jsx-no-leaked-render.js
lib/rules/jsx-sort-default-props.js
lib/rules/no-danger-with-children.js
lib/rules/react-in-jsx-scope.js
lib/rules/sort-default-props.js
lib/rules/style-prop-object.js
lib/util/Components.js
lib/util/isDestructuredFromPragmaImport.js
lib/util/propTypes.js
lib/util/variable.js
package.json

A few weeks ago ([for reasons](https://github.com/microsoft/TypeScript/issues/59101#issuecomment-2201727047)), I ended up profiling the time spent linting on the [Sentry](https://github.com/getsentry/sentry) repository. One of the things I noticed was that a significant amount of time was being spent on `variablesInScope` and similar operations from the lint rules from the eslint-plugin-react repository.
The problem with most uses of `variablesInScope` is that this function creates a single flat scope out of all variables walking up the spine of a tree, and call-sites subsequently use that to look up the variables. This is a problem for a few reasons:
1. Intermediate arrays is thrown away on every parent scope encountered. In fact, several intermediate arrays may be created and thrown …

[Refactor] `variableUtil`: Avoid creating a single flat variable scope for each lookup

---

CHANGELOG.md
README.md
lib/util/version.js
tests/util/version.js

I have some projects where I want to detect the react version most of the time, but sometimes I expect that to fail. In those cases, I don't want to default to "latest". I instead want to choose the default fallback version of React.

[New] version settings: Allow react defaultVersion to be configurable

---

CHANGELOG.md
docs/rules/jsx-closing-tag-location.md
lib/rules/jsx-closing-tag-location.js
tests/lib/rules/jsx-closing-tag-location.js

Fixes #3740
I added new options to `jsx-closing-tag-location`: `line-aligned` and `tag-aligned (default)`.
With the `line-aligned` option, the following code would be accepted:
```
const test = <div>
Hello World
</div>
```
Users can use the `tag-aligned` option to ensure that the following code is accepted:
```
const test = (
<div>
Hello World
</div>
)
```
What I did:
1. Added code for the new options, including a error message.
2. Updated the documentation to explain the new options.
3. Added test cases for the new options and verified that they all pass.
Please let me know if there are any improvements needed. I am happy to fix them!
I am honored to contribute to this project.

[New] `jsx-closing-tag-location`: add `line-aligned` option

---

CHANGELOG.md
docs/rules/no-danger.md
lib/rules/no-danger.js
tests/lib/rules/no-danger.js

[New] `no-danger`: add `customComponentNames` option

---

CHANGELOG.md
lib/rules/sort-prop-types.js
lib/util/propTypesSort.js
tests/lib/rules/sort-prop-types.js

[Fix] `sort-prop-types`: single line type ending without semicolon

---

CHANGELOG.md
lib/rules/require-default-props.js
tests/lib/rules/require-default-props.js

[Fix]`require-default-props`: report when required props have default param value

---

CHANGELOG.md
lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

[Fix] `jsx-curly-brace-presence`: do not trigger on strings containing a quote character

---

CHANGELOG.md
lib/rules/no-string-refs.js
tests/lib/rules/no-string-refs.js

In React version 18.3.0 they released [a change to support writing to `this.refs`](https://github.com/facebook/react/pull/28867). In the [React 19 RC Upgrade Guide](https://react.dev/blog/2024/04/25/react-19-upgrade-guide#run-all-react-19-codemods) they suggest running a codemod that will remove the string ref usage but still use `this.refs`, which can cause false positives for the `no-string-refs` rule. 
My PR simply tests the React version before checking the `MemberExpression`. Thanks!

[New] `no-string-refs`: allow this.refs in > 18.3.0

---

.github/workflows/node-18+.yml
.github/workflows/node-minors.yml
CHANGELOG.md
lib/rules/boolean-prop-naming.js
lib/rules/function-component-definition.js
lib/rules/jsx-first-prop-new-line.js
lib/rules/jsx-max-depth.js
lib/rules/jsx-props-no-multi-spaces.js
lib/util/propTypes.js
lib/util/props.js
package.json
tests/helpers/parsers.js

Follows the [guide](https://typescript-eslint.io/linting/troubleshooting/#the-key-property-is-deprecated-on-type-nodes-use-key-instead-warnings) from `@typescript-eslint` to upgrade to `v6`, by adding a small utility function `getTypeArguments` which returns the `typeArguments` or falls back to `typeParameters`.
Closes #3602

[Fix] `@typescript-eslint` v6, v7, v8 use typeArguments with fallback to typeParameters

---

CHANGELOG.md
docs/rules/no-danger.md

Before, the URL was broken and pointed to a 404 Not Found page.
Now, the URL has been corrected

[Docs] `no-danger`: update broken link

---

CHANGELOG.md
docs/rules/jsx-no-literals.md
lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

Resolves #3808
Preface - I didn't intend to rewrite the whole rule, but I ended up needing to re-write the way the rule fetches and applies the config which resulted in the majority of the rule being reworked. 
Adds a new option, `elementOverrides` which adds the ability to override the rule options for any named component. Specifying options within `elementOverrides` creates a new context for the rule, so the rule will only apply the new options to the specified element and its children (if
`applyToNestedElements` is `true` - see below). This means that the root rule options will not apply to the specified element.
`elementOverrides` is an object where the keys are the element names and the values are objects with the same options that this rule previously supported (`noStrings`, …

[New] `jsx-no-literals`: add `elementOverrides` option

---

CHANGELOG.md
lib/rules/no-is-mounted.js
tests/lib/rules/no-is-mounted.js

The last change to `no-is-mounted` caused the rule to error with any method name, not just with "isMounted".
Fixes #3819

[Fix] `no-is-mounted`: fix logic in method name check

---

CHANGELOG.md
lib/rules/jsx-no-literals.js

b8217ed5f4104bd18b54f77ea108ec081ebbbd49 removed the `node.value` check leading to this crashing on any valueless boolean prop such as `<Component isWhatever />`
This just readds the check.
Fixes https://github.com/jsx-eslint/eslint-plugin-react/issues/3820

[Fix] `jsx-no-literals`: Avoid crashing on valueless boolean props

---

CHANGELOG.md
docs/rules/forbid-component-props.md
lib/rules/forbid-component-props.js
tests/lib/rules/forbid-component-props.js

Initially, issue was described [here](https://github.com/jsx-eslint/eslint-plugin-react/issues/3686), but it was closed by [another PR](https://github.com/jsx-eslint/eslint-plugin-react/pull/3774) (although this PR implements different case).
So, this PR just reimplements `Regex` implementation with `globs` as was suggested in [one](https://github.com/jsx-eslint/eslint-plugin-react/issues/3686#issuecomment-1951461748) of the comments.

[New] `forbid-component-props`: add `allowedForPatterns` and `disallowedForPatterns` options

---

CHANGELOG.md
docs/rules/no-unstable-nested-components.md
lib/rules/no-unstable-nested-components.js
tests/lib/rules/no-unstable-nested-components.js

I would like to adopt this rule but `render*` is not the only render prop naming convention in my codebases. Namely libraries such as [react-virtualized](https://github.com/bvaughn/react-virtualized/blob/master/docs/Table.md) have a `*Renderer` convention. 
This PR adds the ability to customize the prop name matcher.
~At the same time I cleaned up the `customValidators` documentation that appears to have been copy/paste error at implementation. I believe this would close 3664, which asks to document this non-existent option.~

[New] `no-unstable-nested-components`: add `propNamePattern` to support custom render prop naming conventions

---

CHANGELOG.md
README.md

Contrary to what [the comment](https://github.com/jsx-eslint/eslint-plugin-react/issues/3770#issuecomment-2179919625) says, a link to [this snippet](https://github.com/jsx-eslint/eslint-plugin-react/blob/c8917b0885094b5e4cc2a6f613f7fb6f16fe932e/index.js#L163-L176) is a red herring and adding `jsx-runtime` config to array is enough for error to go way.

[readme] flat config example for react 17+

---

CHANGELOG.md
README.md

- Updates the link to the eslint shared settings page in the `README.md` file.
As I was upgrading my eslint configuration for a personal project, I found that I needed to use the shared settings feature to configure my React version. The link in the docs section navigates to the main page but doesn't anchor you to the section that discusses the shared settings. I think the original link broke at some point. This PR fixes it.

[readme] Fix shared settings link

---

CHANGELOG.md
lib/rules/destructuring-assignment.js
tests/lib/rules/destructuring-assignment.js

Fixes #3828 
The rule failed to catch usages of `typeof props.a` because it is parsed a TSQualifiedName instead of a memberExpression.

[Fix] `destructuring-assignment`: fix false negative when using typeof props.a

---

CHANGELOG.md
tests/lib/rules/jsx-no-script-url.js

While developing [this](https://github.com/oxc-project/oxc/pull/6995), I noticed that test files for this rule don't explicitly cover the case when a non `linkAttribute`/`props` from a link component has the `"javascript:"` value. The rule seems to behave correctly for that case, so what I did in this PR is just to add a few tests for that.

[Tests] `jsx-no-script-url`: Improve tests

---

.github/workflows/type-check.yml
CHANGELOG.md
index.js
lib/rules/forbid-foreign-prop-types.js
lib/rules/forbid-prop-types.js
lib/rules/forward-ref-uses-ref.js
lib/rules/index.js
lib/rules/jsx-fragments.js
lib/rules/jsx-no-literals.js
lib/rules/jsx-props-no-spread-multi.js
lib/rules/jsx-space-before-closing.js
lib/rules/no-access-state-in-setstate.js
lib/rules/no-deprecated.js
lib/rules/no-unused-state.js
test-published-types/index.js
test-published-types/package.json
test-published-types/tsconfig.json
tsconfig.json
types/rules/jsx-no-literals.d.ts
types/string.prototype.repeat/index.d.ts

Closes https://github.com/jsx-eslint/eslint-plugin-react/issues/3838
This PR fixes various issues in the generated `index.d.ts`. The full diff for `index.d.ts` can be viewed in [this link](https://github.com/ocavue/eslint-plugin-react/commit/d8be0647b10f1ae01344bc83a8254e16064280e3). The change highlight are shown below:
```diff
rules: {
-   'react/display-name': number;
+   'react/display-name': 2;
-   'react/jsx-key': number;
+   'react/jsx-key': 2;
```
```diff
'jsx-no-duplicate-props': import("eslint").Rule.RuleModule;
'jsx-no-leaked-render': import("eslint").Rule.RuleModule;
-   'jsx-no-literals': {
-      meta: import("eslint").Rule.RuleMetaData;
-      create(context: any): (false & {
-      ...
-   };
+   'jsx-no-literals': import("eslint").Rule.RuleModule;
```

[Fix] correct generated type declaration

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

[Fix] `no-unknown-property` support new `precedence` prop

---

CHANGELOG.md
lib/util/propTypes.js
tests/lib/rules/prop-types.js

Fixes #3684.
TypeScript code that uses `ComponentProps` and `ComponentPropsWithoutRef` from a namespace import (such as `import React from 'react'` or `import * as React from 'react'`) led to destructured props receiving a "is missing in props validation" error.
For example:
```tsx
import * as React from 'react';
export const Button = React.forwardRef<HTMLButtonElement, React.ComponentPropsWithoutRef<'button'>>(
// Error: 'className' is missing in props validation (from the react/prop-types rule)
({ children, className, ...props }, ref) => {
return (
<button className={className} ref={ref} {...props}>
{children}
</button>
);
},
);
Button.displayName = 'Button';
```

[Fix] `prop-types`: props missing in validation when using generic types from a namespace import

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

[Fix] no-unknown-property: support `onBeforeToggle`, `popoverTarget`, `popoverTargetAction` attributes

---

CHANGELOG.md
docs/rules/jsx-no-constructed-context-values.md
lib/rules/jsx-no-constructed-context-values.js
tests/lib/rules/jsx-no-constructed-context-values.js

Fixes #3888 
This PR updates the `jsx-no-constructed-context-values` rule to support React 19-style context providers using the <Context> shorthand.

[Fix] `jsx-no-constructed-context-values`: detect constructed context values in React 19 `<Context>` usage

---

CHANGELOG.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

They body tag supports an onload event
https://www.w3schools.com/jsref/event_onload.asp

[Fix] `no-unknown-property`: allow `onLoad` on `body`

---

CHANGELOG.md
lib/rules/jsx-props-no-multi-spaces.js
tests/lib/rules/jsx-props-no-multi-spaces.js

Extends automatic fix support to cover the "no line gap" half of the jsx-props-no-multi-spaces rule. There is already automatic fix support for the "only one space" enforcement.

[New] `jsx-props-no-multi-spaces`: Add automatic fix for no line gap between props
