jsx-eslint/eslint-plugin-react

docs/rules/react-in-jsx-scope.md
index.js
lib/rules/react-in-jsx-scope.js
tests/lib/rules/react-in-jsx-scope.js

Hope this makes sense - I've included tests & docs as well.
See https://github.com/eslint/eslint/issues/1905 for some additional context.
I'm planning to follow up with a variant on `no-unused` that knows about JSX using `React.createElement`.
Sidenote: should there be a test which verifies all rules are exported in `index.js` ?

add react-in-jsx-scope rule

---

docs/rules/jsx-uses-react.md
index.js
lib/rules/jsx-uses-react.js
tests/lib/rules/jsx-uses-react.js

See eslint/eslint#1905 for additional context.
This rule somewhat unusual, in that it modifies the behaviour of a core eslint rule.
I'm not hugely keen on this, but it does work. It is possible for the rule to be broken by changes in eslint core.
The alternative would be to copy-paste the original rule and modify it.
That would require users to disable the core rule and replace it with this one - and then any improvements to the core rule would have to be tracked here and updated.
Of those two choices, I think the first one is the most practical, even if it breaks the usual clean separation of rules.

Add jsx-uses-react rule

---

tests/index.js

As discussed in the comments from #5

Add test to ensure all rules are exported

---

README.md

Sorting these alphabetically makes it easier to find what you are
looking for, and provides a simple and clear order for new items to be
added to the list.

Sort rules alphabetically in README.md

---

lib/rules/no-did-mount-set-state.js
lib/rules/no-did-update-set-state.js
tests/lib/rules/no-did-mount-set-state.js
tests/lib/rules/no-did-update-set-state.js

I think this should not be considered an error/warning by this rule: (my actual code follows)
```	
componentDidMount() {
this.handleStoreEvent = _.compose(this.setState, getStoreState).bind(this);
dependencies.add(this.handleStoreEvent);
},
```
While I don't know that this is great code per se, it is essentially binding `setState` to a list of Flux stores via a helper (`dependencies`). This seems to me like a valid use of `setState` within `componentDidMount`.
I refactored both rules pertaining to `setState` to respond to `CallExpression` nodes instead of `MemberExpression`, and it returns if the `callee` is not a `MemberExpression`. The original logic follows thereafter.
I can imagine also potentially making this reduction in strength an option, but I believe the behavior here captures …

Allow this.getState references (not calls) in lifecycle methods.

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Previously, accessing props dynamically with an expression like `this.props[propName]` would result in a linting error like:
> 'propName' is missing in props validation
However "propName" is simply the name of a variable, not the actual property name. Since there's no easy way to resolve the real property name for dynamic accesses like this, this modification simply ignores such cases.

Fix prop-types to check for computed prop names.

---

lib/rules/prop-types.js

It seems it had been copy-pasted and then forgot.

fix describing comment for hasSpreadOperator() method

---

index.js
tests/index.js

From original issue: "just wondering why jsx-uses-vars wouldn't be turned on by default (maybe to 'warn')? I guess the real question is: what's the use case for not wanting to mark them used?"
Fixes #49

Enable jsx-uses-vars rule to WARN by default

---

tests/lib/rules/react-in-jsx-scope.js

This is to reproduce the error described here https://github.com/yannickcr/eslint-plugin-react/issues/58, which fails with:
```bash
152 passing (174ms)
1 failing
1) react-in-jsx-scope import React from 'react/addons';
const Button = React.createClass({
render() {
return (
<button {...this.props}>{this.props.children}</button>
)
}
});
export default Button;:
AssertionError: Should have no errors but had 1: [ { ruleId: 'react-in-jsx-scope',
severity: 1,
message: '\'React\' must be in scope when using JSX',
line: 5,
column: 6,
nodeType: 'JSXOpeningElement',
source: '      <button {...this.props}>{this.props.children}</button>' } ]: expected 1 to equal 0
```

Reproduce error using ES6 imports

---

package.json

From http://eslint.org/docs/developer-guide/working-with-plugins.html
`To make clear that the plugin requires ESLint to work correctly
you have to declare ESLint as a peerDependency in your package.json`
Just some examples:
https://github.com/theodoreb/eslint-plugin-drupal/blob/v0.3.1/package.json#L22-24
https://github.com/Gillespie59/eslint-plugin-angular/blob/0.0.7/package.json#L30-32
https://github.com/ilyavolodin/eslint-plugin-backbone/blob/v1.0.2/package.json#L19-21
https://github.com/tlvince/eslint-plugin-jasmine/blob/v1.0.0-rc.2/package.json#L6-8

[fixed] Add mandatory eslint package as peerDependency.

---

lib/rules/jsx-uses-vars.js
tests/lib/rules/jsx-uses-vars.js

Previously, all JSX identifiers were marked as "used", even for prop names. This is an issue in cases where component props happened by chance to have the same name as a local variable, like this:
var App;
var foo;
React.render(<App foo="bar"/>);
Here, the "foo" prop prevents the `foo` variable from being marked as unused and ESLint gives no warnings for the `no-unused-vars` rule, even though `foo` is not actually referenced anywhere.
This change updates the `jsx-uses-vars` rule to only mark variables as used if they occur in a `JSXOpeningElement` node (thus excluding prop names, as they exist in `JSXAttribute` nodes instead).

Only mark component types as used, not prop names.

---

README.md
docs/rules/jsx-sort-prop-types.md
index.js
lib/rules/jsx-sort-prop-types.js
tests/lib/rules/jsx-sort-prop-types.js

Tests and Docs are included.
The `jsx-sort-prop-types` rule recognizes all supported patterns by this plugin
including those with ES6 classes syntax and `static propTypes`.
```js
var Component = React.createClass({
propTypes: {
a: React.PropTypes.number,
b: React.PropTypes.any
}
...
```
```js
class Component extends React.Component {
...
}
Component.propTypes = {
a: React.PropTypes.any,
b: React.PropTypes.string
};
```
```js
class Component extends React.Component {
static propTypes = {
a: React.PropTypes.any,
b: React.PropTypes.any,
c: React.PropTypes.any
}
render() {
}
}
```
By default it is disabled. 
Also it allows case ignoring.
Closes #38.
In the case this PR is merged it needs DRY refactoring.
(`isPropTypesDeclaration()` is the one to extract and …

[added] The rule to check propTypes declarations sorting.

---

docs/rules/jsx-uses-react.md
lib/rules/jsx-uses-react.js
tests/lib/rules/jsx-uses-react.js

This fixes #80 
Instead of taking the approach mentioned there, this turned out to be far less complicated, it basically adds a second config option to the `react/jsx-uses-react` rule:
```js
[ 2, 'dom' ]
```
This causes `dom` to be used in place of `React` as the used variable. I've also included a test and updated the docs for the aforementioned rule.
Let me know if there's anything else we need to do to get this merged! :D

adding support for setting the jsx pragma value via config

---

docs/rules/prop-types.md

Just a small doc update to suggest using `node` instead of `any` for `children`. Related to #7.

Suggest `PropTypes.node` for children

---

docs/rules/wrap-multilines.md
lib/rules/wrap-multilines.js
tests/lib/rules/wrap-multilines.js

This adds an option for enabling/disabling wrap-multilines in the context of the enclosing expression. In facebook/react, [we only care about jsx expressions in return statements](https://github.com/facebook/react/pull/4007#discussion_r31554866)

Make wrap-multilines more granular

---

package.json

Fixes #113 
Point directly to mocha instead of symlink in .bin. On Windows the file in .bin is not a symlink.
Inspired by solution in eslint.

Windows tests

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Closes #105 
Support nested prop types and use react propTypes to make further analysis.
Minimal analyse of primitive propTypes.
It uses `React.PropTypes.xxxx` to determine the depth of the property.
I might have missed some edge cases, I tried to cover as much as I could think.

Added support for nested prop types

---

docs/rules/require-extenion.md
index.js
lib/rules/require-extension.js
tests/lib/rules/require-extension.js

Created a new rule, 'require-extension', which inspects the required
module ID and warns if the file extension is .jsx.
The particular disallowed file extensions are configurable, defaulting to
just '.jsx'. If you wanted to also disallow '.js', the rule can be
configured as:
"rules": {
"react/require-extension": [1, { "extensions": [".js", ".jsx"] }],
}
Note: this rule does not prevent required files from containing forbidden
extensions, it merely prevents the extension from being included in the
`require()` statement.
This rule is inspired by the Airbnb react style guide:
https://github.com/airbnb/javascript/tree/master/react#naming

Allow blocking of '.jsx' extensions with `require()`

---

lib/rules/display-name.js
lib/rules/prop-types.js
tests/lib/rules/display-name.js
tests/lib/rules/prop-types.js

This PR introduces a small tweak in the ```react/display-name``` and ```react/prop-types``` custom eslint rules which adds to the detected React components any class created using the ```React.createClass``` helper when there isn't any jsx syntax in the render method.
Adding the above components definition object expressions to the component list is enough to detect missing ```displayName``` and ```propTypes``` properties as expected.

fix detection of missing displayName and propTypes when ecmaFeatures.jsx is false

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Fixes #118 
I saw that destructuring were not correctly detected when the first key was a string and also those were not handled properly.

Fix `prop-types` desctructuring with properties as string.

---

lib/rules/jsx-sort-prop-types.js
tests/lib/rules/jsx-sort-prop-types.js

While investigating another bug, I stumbled onto this, which was easier to fix, so here it is.
Added support for prop type identified by strings in rule `jsx-sort-prop-types`

`jsx-sort-prop-types` support for keys as string

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Following discussion at https://github.com/yannickcr/eslint-plugin-react/pull/124#discussion_r32871420
Added support for prop-types check of type `this.props['this-format']`.
Used list of nested names instead of dot-separated names to avoid conflict with properties like `this.props['this.format']`

`prop-types` computed string format

---

README.md

This rule was added by 0c132f5559 but was not added to the README, so it
was difficult to discover.

Add no-danger to README

---

docs/rules/jsx-curly-spacing.md
lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-curly-spacing.js

What do you think about this? I had hoped it would be like that by default when I first read about that rule being introduced! Which prompts my next question: should `allowMultiline` be on by default? I currently put it off by default and I'm ignoring it when the option is set to `"always"` as to not break current users (new warnings/errors) that do:
```js
<Hello name={
firstname
} />;
```
using
```json
"jsx-curly-spacing": [2, "always"]
```
If it were on by default, I could leverage the option in all cases, meaning users would have a way to enforce:
```js
// Valid
<Hello name={ firstname } />;
// Invalid
<Hello name={
firstname
} />;
```
with
```json
"jsx-curly-spacing": [2, "always", {"allowMultiline": false}]
```
However, current users relying on
```js
<Hello name={
firstname
} />;
``` …

Added `allowMultiline` property to the `jsx-curly-spacing` rule

---

index.js
lib/rules/jsx-no-duplicate-props.js
tests/lib/rules/jsx-no-duplicate-props.js

Added rule that checks for duplicate props sent to a React component written in JSX.
Has the options of specifying whether casing should be ignored when comparing, via `{ignoreCase: true}`
Closes #143

Added rule for no duplicated props

---

docs/rules/require-extension.md

I think it would be helpful to help users satisfy the requirements for this rule.
If someone knows how to configure Browserify, please add it.

Update require-extension.md with information on setting up Webpack.

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

A possible solution to the problem presented in #145.
Since we can't know what the `React.PropTypes` or `MyCustomValidator` is refering to when checking if it should be statically evaluated (or how to do so) I proposed adding an optional configuration to the prop-types rules: `customValidators`.
This allows us to ignore specific proptypes that the plugin doesn't have explicit knowledge of.
Example Usage:
``` javascript
"react/prop-types": [2, {customValidators: ['CustomValidator']}]
// Sample.js
var Hello = React.createClass({
propTypes: {
outer: React.PropTypes.shape({
inner: CustomValidator.map
})
},
render: function() {
return <div>{this.props.outer.inner.get('test')}</div>;
}
})
```
As a side note, it could possibly be added so the listed custom validators be actual modules that …

Custom validator detection

---

lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

Enforce casing for all event handlers from https://facebook.github.io/react/docs/events.html
I hate trying to debug my click handlers when I've typed `onclick` instead of `onClick` in my components.

Add event handlers to no-unknown-property

---

lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

This is the initial warnings range that I was considering before and should only report while inside of a JSX component.

Added type limits to jsx-no-literals.

---

lib/rules/prop-types.js

In standard (latest `master`) when I enable `experimentalObjectRestSpread` in eslint. We run into this issue when using eslint 1.1.0 and eslint-plugin-react 3.2.1.
```js
~/dev/standard (master) $ node bin/cmd.js test.js
standard: Unexpected linter output:
TypeError: Cannot read property 'type' of undefined
at isPropTypesDeclaration (/Users/jamuferguson/dev/standard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:49:13)
at /Users/jamuferguson/dev/standard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:589:14
at Array.forEach (native)
at EventEmitter.ObjectExpression (/Users/jamuferguson/dev/standard/node_modules/eslint-plugin-react/lib/rules/prop-types.js:588:23)
at EventEmitter.emit (events.js:129:20)
at Controller.controller.traverse.enter …
```

Fix A Crash

---

lib/rules/display-name.js
lib/rules/jsx-sort-prop-types.js

In a file like this with experimental object spread properties syntax:
```javascript
function lol(a, b, c) {
return {...a, b, c};
}
```
The following rules were throwing an error because `node.property` is undefined in a property node of type `ExperimentalSpreadProperty`.
Not sure if this is the right approach, but at least it allows me to run eslint!

Add defensive coding to support experimental object spread properties

---

docs/rules/sort-comp.md
lib/rules/sort-comp.js

In ESNext, the following is possible:
```
class extends React.Component {
state = {
key: value
}
}
```

add `state` in lifecycle methods

---

lib/util/component.js
tests/lib/rules/sort-comp.js

This component triggers a sort-comp warning:
```
return React.createClass({
render: function() {
return <div>Hello</div>;
},
displayName : 'Hello'
});
```
This one does not:
```
return React.createClass({
render: function() {
return React.createElement("div", null, "Hello");
},
displayName: 'Hello'
```
This change makes it so that classes of the latter type are correctly consider as react classes, and rules such as sort-comp will run against them.

Treat component with render which returns createElement as Valid

---

docs/rules/jsx-closing-bracket-location.md
lib/rules/jsx-closing-bracket-location.js
tests/lib/rules/jsx-closing-bracket-location.js

Optionally, one can configure the behaviour of `jsx-closing-bracket-location`
when dealing with different types of tags. Additionally, it allows a simple
string config instead of the previous object with a single location property
(which is still supported).
This fixes #208

Configure jsx-closing-bracket-location for self-closing and non-empty tags

---

lib/rules/forbid-prop-types.js
tests/lib/rules/forbid-prop-types.js

Forbid-prop-types will crash if you have a bit of code that looks like:
```
var object = React.PropTypes.object;
var Comp = React.createClass({
propTypes: {
someProp: object
},
render: function() {.....}
});
```
This pull request fixes that issue and adds a test case to ensure that the above is correctly flagged as an error.

Fix crash with destructured PropTypes

---

docs/rules/jsx-sort-prop-types.md
docs/rules/jsx-sort-props.md
lib/rules/jsx-sort-prop-types.js
lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-prop-types.js
tests/lib/rules/jsx-sort-props.js

In my team (ads at Facebook) we tend to sort callbacks to the end, in their own group:
```js
<Foo
a="blah"
b="blah"
y="blah"
z="blah"
onAwesome={() => alert('Woohoo!')}
onClick={blah}
onFoo={blah}
onZoom={blah}
```
This change adds a `callbacksLast` configuration option to allow this style of sorting.
Also fixed the `currenPropName` typo (missing `t`) and renamed `lastPropName` to `previousPropName` so it's clearer that it's the previously encountered prop and **not** the very last prop of the JSX tag.

Update `jsx-sort-props` to allow sorting callbacks last

---

lib/rules/forbid-prop-types.js
tests/lib/rules/forbid-prop-types.js

I believe this fixes #249.
The cause of the issue is that `checkForbidden()` modifies AST.  I fixed the issue by making local variable `value`.
<del>Note that this PR is work in progress.  I don't commit test case yet.  But</del> I'm already sure that the case reported in #249 was resolved.

Do not modify AST directly (fixes #249)

---

lib/rules/jsx-no-bind.js
tests/lib/rules/jsx-no-bind.js

When I actually started using this rule in real-life code, I noticed that it was crashing for normal function calls (eg. `foo={bar()}`) as `node.callee.property` is `null` for those. Instead, we want to explicitly check that the callee is a `MemberExpression`.

[jsx-no-bind] Ensure node is MemberExpression before checking property name

---

docs/rules/jsx-closing-bracket-location.md
lib/rules/jsx-closing-bracket-location.js
tests/lib/rules/jsx-closing-bracket-location.js

`'line-aligned'` acts like `'tag-aligned'` except when the opening JSX tag
is preceded by other code on the same line.
This commit adds the rules, the corresponding tests, and updates the
documentation.
Test Plan:
npm install
npm run test

Add 'line-aligned' option for jsx-closing-bracket-location

---

lib/rules/jsx-closing-bracket-location.js
tests/lib/rules/jsx-closing-bracket-location.js

By adding expected column information for the closing bracket, as well
as reporting the error at the closing bracket instead of the opening
bracket. Parsing the error message should now be sufficient to allow
writing an external autofixer.
Example input `test.jsx` with default options:
```jsx
<Provider
store> // <--
<App
foo
/>
</Provider>
```
Resulting error:
`test.jsx:2:10: Ereact/jsx-closing-bracket-location The closing bracket must be aligned with the opening tag (expected column 1 on the next line)`
Note that the reported error location now corresponds to the closing `>` bracket on line 2, and that the error message now includes the exact location of where that closing bracket should have been.
Test Plan:
`npm install`
`npm run test`

Improve jsx-closing-bracket-location error message

---

lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

React 0.14 has support for custom elements and their attributes are passed through. It's discussed in https://github.com/facebook/react/issues/4933. The custom element detection is similar to the one done in https://github.com/facebook/react/blob/b4b1add/src/renderers/dom/shared/ReactDOMComponent.js#L493-L495

no-unknown-property should not check custom elements

---

lib/rules/display-name.js
lib/rules/no-direct-mutation-state.js
lib/rules/prefer-es6-class.js
lib/rules/prop-types.js
lib/util/Components.js
package.json

Instead of putting the `react` object on `context`, this PR creates it as a separate variable and passes it as a 3rd parameter to the fn passed to `Components.detect`.
fixes #323

Fix crash when using eslint 1.10.0

---

README.md

The `jsx-pascal-case` isn't in the example complete config.

Add `jsx-pascal-case` to complete list of rules

---

docs/rules/jsx-pascal-case.md
lib/rules/jsx-pascal-case.js
tests/lib/rules/jsx-pascal-case.js

I've run into a couple of cases where I have consecutive capital letters
in React components (e.g. <CSSTransitionGroup>), and jsx-pascal-case is
complaining about them. This commit fixes this problem by allowing
consecutive uppercase letters.
Fixes #328

Allow consecutive uppercase letters in jsx-pascal-case

---

docs/rules/jsx-sort-props.md
lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

You can now require that shorthand props should come before all other props, but still respecting the alphabetical order.
---
The following are valid situations:
```jsx
<Component a b="b" />
<Component x z a="a" b="b" />
```
And the following are invalid:
```jsx
<Component z x a="a" b="b" /> // should be in alphabetical order
<Component x z b="b" a="a" /> // should be in alphabetical order
<Component a="a" b="b" x z /> // shorthand props should be at the start
```
---

Add option to sort shorthand props on jsx-sort-props

---

lib/util/variable.js

While looking into a bug, I noticed that there was a missing `@param`
here.

Add missing JSDoc `@param` in variable.js

---

lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

I realized the error messages were previously specifying a more specific method name than the rule actually enforced. 
For example, `onChange={this.itemClicked}` would throw the warning `Handler function for onChange prop key must be named handleChange`, when really `this.handleItemClick` would (and should) pass.

make jsx-handler-names error messages less specific

---

lib/rules/prefer-es6-class.js

Doesn't change the default behavior, but allows you to specify 'never' as an option that recommends createClass over using es6 classes.
[The argument for switching is still a little murky](http://reactjsnews.com/composing-components/). In the meantime its nice to be able to force it in either case.

allow es6 class rule to be configured to discourage usage as well

---

lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

Currently only failing tests because I'm new to developing ESLint rules, so it'll take me a couple of days.
I was planning to do it by detecting if the calling method is `map`. This would apply to `Array.prototype.map` as well as `React.Children.map`. Are there any other cases where the rule should be looking for `key`?
Will fix #320.

[jsx-key] Improve and fix false-positives

---

docs/rules/no-is-mounted.md

When I made this link, I used the wrong markdown syntax so it was
linking to "anti-pattern" instead of the intended URL.

Fix link in no-is-mounted documentation

---

README.md
docs/rules/no-string-refs.md
index.js
lib/rules/no-string-refs.js
tests/lib/rules/no-string-refs.js

Initially, the idea in #341 was to check if references in `this.refs` exist. Based on further discussion it was suggested to define a rule to disallow using string literals in reference properties.

Prevent string literals being used in ref attributes

---

lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

I was having the same crashes as #373 when using `jsx-key`.
It was triggering for non jsx stuff, so I added a few "valid" tests which don't actually test anything except that the rule doesn't crash. I'm not sure if its appropriate to have those tests in the specific rule test file, but I figured it would be good to prevent regressions.

fix crashes in jsx-key

---

lib/rules/forbid-prop-types.js

if you run `eslint test.jsx`
```js
//test.jsx
class A {
const
}
```
with
```
//.eslintrc
{
"parser": "babel-eslint",
"ecmaFeatures": {
"jsx": true
},
"rules": {
"react/forbid-prop-types": 1,
},
"plugins": [
"react"
]
}
```
you get the following output
```
/Users/nuno/cp/james/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:38
if (tokens[0].value === 'propTypes' || tokens[1].value === 'propTypes') {
^
TypeError: Cannot read property 'value' of undefined
at isPropTypesDeclaration (/Users/nuno/cp/james/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:38:19)
at EventEmitter.ClassProperty (/Users/nuno/cp/james/node_modules/eslint-plugin-react/lib/rules/forbid-prop-types.js:87:11)
at emitOne (events.js:77:13)
at EventEmitter.emit (events.js:169:7)
at …
```

rule: forbid-prop-types, handle situation where getFirstTokens() call returns only 1 Token

---

lib/rules/jsx-key.js

similar to PR #374
fix this crash:
```
TypeError: Cannot read property 'type' of null
at checkIteratorElement (/Users/nuno/cp/james/node_modules/eslint-plugin-react/lib/rules/jsx-key.js:25:13)
at EventEmitter.CallExpression (/Users/nuno/cp/james/node_modules/eslint-plugin-react/lib/rules/jsx-key.js:65:13)
```

fix another crash in jsx-key

---

docs/rules/sort-comp.md

There's now a jstransform codemod to do this automatically,
https://github.com/reactjs/react-codemod/blob/master/transforms/sort-comp.js
Added a note about it based on the pattern in http://eslint.org/docs/rules/no-trailing-spaces

Docs: How to automatically sort-comp compliance

---

lib/rules/sort-comp.js
tests/lib/rules/sort-comp.js

```
warning: componentWillUpdate must be placed after componentDidMount
```
Sorting component methods is only ever a style preference. "must" is a bit misleading - it implies that there will be errors in the program. Say "should" instead.
Thanks.

sort-comp: say "should" instead of "must"

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

This PR adds support for using [flow](http://flowtype.org/) type annotations for class props instead of `propTypes`. Flow added support for this quite recently in: https://github.com/facebook/flow/issues/850
The syntax looks like this:
```js
type Person = {
name: {
firstName: string;
lastName: string;
},
age: number;
};
type Props = {
greeting: string;
people: Person[];
};
class Hello extends React.Component {
props: Props;
render () {
const names = [];
for (let i = 0; i < this.props.people.length; i++) {
names.push(this.props.people[i].name.firstName);
}
return <div>{this.props.greeting}, {names.join(', ')}</div>;
}
}
```

Support flow annotations for component props

---

docs/rules/jsx-sort-prop-types.md
lib/rules/jsx-sort-prop-types.js
tests/lib/rules/jsx-sort-prop-types.js

Hey there, I've been really enjoying `eslint-plugin-react`, thanks for creating such a great set of React rules for ESLint!
Our team likes to put required prop type declarations first, followed by optional prop types. I extended the existing `jsx-sort-prop-types` rule to take a `requiredFirst` option to make this enforceable by ESLint.
When set to `true` required props must come first and be sorted alphabetically:
```js
class First extends React.Component {
render() {
}
}
First.propTypes = {
barRequired: React.PropTypes.string.isRequired,
fooRequired: React.PropTypes.any.isRequired,
a: React.PropTypes.any,
z: React.PropTypes.string,
onBar: React.PropTypes.func,
onFoo: React.PropTypes.func
};
```
In addition to the changes this PR includes tests and documentation.
Figured …

Add `requiredFirst` option to jsx-sort-prop-types

---

docs/rules/jsx-no-bind.md
lib/rules/jsx-no-bind.js
tests/lib/rules/jsx-no-bind.js

Not sure how you want to go about this. I first wanted to allow `ref` callbacks always, but it's still a bad practice for the same reasons, so I thought `allowRefs` option would be nice? However, it might be confusing that `allowArrowFunctions` and `allowBind` affects `ref` as well.
Also, I added other missing options to the docs. Is `|| false` a good way to document that it defaults to `false`?
Fixes #330.
Refs #357.

Add ignoreRefs to the jsx-no-bind rule

---

lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-curly-spacing.js

Hello!
This PR implements autofixing for the rule "jsx-curly-spacing", meaning it will add or remove whitespaces in JSX expressions according to the given options.
We would like to use this rule on our app but have too many errors for a manual fix, so I thought I'd give it a go.
This is my first PR to any opensource project ever, so my apologies if I got something wrong!

Add auto fix for jsx-curly-spacing

---

lib/rules/jsx-sort-prop-types.js
tests/lib/rules/jsx-sort-prop-types.js

Closes #408
caveats:
Might not behave correctly with complex propTypes when the are `required` although this was a problem with the original PR ( #392 ). But it might be fixed here too. I simply don't know how :grin:

Fix jsx-sort-prop-types issue with custom propTypes

---

docs/rules/prop-types.md
lib/rules/prop-types.js
tests/lib/rules/prop-types.js

The following should cause an error for missing propType validations,
but it doesn't.
```jsx
const Test = ({ name }) => {
return (
<div>{name}</div>
);
};
```
If you replace the destructuring with using the props object, it works
as expected. This commit fixes this problem.
Fixes #354.

Teach prop-types about destructing in function signatures

---

docs/rules/display-name.md
lib/rules/display-name.js
tests/lib/rules/display-name.js

This was a change that has been queued for v4. I considered changing the
default from false to true, but I think it makes more sense to invert
the option to be an ignore option.
Addresses #436

Change display-name's acceptTranspilerName to ignoreTranspilerName

---

docs/rules/sort-comp.md
lib/rules/sort-comp.js

A number of people have said that they think it makes sense for static
class methods to appear at the very top of classes. This PR allows
this to be configured by adding the `static-methods` keyword to the
sort-comp rule.
While I was at it, I fixed a couple of typos and made a minor perf tweak.
Fixes #128

Teach sort-comp rule about static class methods

---

README.md

Now that this list has grown considerably, I think it would be helpful
to people to break it up a bit. A natural break is JSX-specific rules
and non-JSX-specific rules.

[readme] Move JSX-specific rules to their own section

---

lib/rules/jsx-key.js
tests/lib/rules/jsx-key.js

Identified and added a fix for a false positive from the `jsx-key` rule. Happens when you pass a function that returns a `JSXElement` as the first parameter.

False positive jsx key rule

---

README.md

Rather than moving the recommended configuration I've added a link to it and specifically called out the issue I had as without that rule it will always fail.

Added a note about the recommended configuration at the bottom of the configuration section.

---

docs/rules/no-set-state.md

I've found this rule really helpful on Flux/Redux apps that don't use forms. I typically only use setState when working with forms.

Updated description to provide more context

---

index.js
lib/rules/require-render-return.js
tests/lib/rules/require-render-return.js

Hello react rules writers!
I have tried to make this feature #482. Hope this rule will be suitable for your repository.
The code is linted and tested. 
Waiting for your response.

Require return value in render function. Tests and rule.

---

lib/rules/jsx-closing-bracket-location.js
tests/lib/rules/jsx-closing-bracket-location.js

@yannickcr - I'm fairly new to eslint and the inner workings of this so this could be wrong, or there could be better ways of doing things. Let me know what you think, thanks!

Autofix for jsx-closing-bracket-location.

---

README.md
docs/rules/jsx-closing-bracket-location.md

Forgot to update the docs earlier.

Update docs to specify JSX closing bracket location as fixable.

---

docs/rules/prefer-stateless-function.md

While looking up this rule, this particular sentence read a little awkwardly.
This PR contains a minor grammar change in the markdown file for the `prefer-stateless-function` rule.

Fix grammar in prefer-stateless-function rule

---

lib/rules/jsx-closing-bracket-location.js

Since we already know what the correct column would be, we can use that to derive the number of spaces to add.
Fixes #533.
Don’t have time to write tests right now, sorry.

Fix line-aligned jsx-closing-bracket-location fixer

---

docs/rules/jsx-uses-vars.md

The old link returns a Github Pages 404 error.

Fix outdated Link

---

tests/lib/rules/jsx-curly-spacing.js

When the `jsx-curly-spacing` rule is set to `never` the rule reports an error when there is a comment in the expression. I've added a failing test to illustrate this but I'm not sure how to go about fixing it. Any pointers?
Using https://astexplorer.net/#/Y9uxLiaZ7W it looks like it should be possible to use the `trailingComments` and `leadingComments` attributes on the node to take comments into account when comparing ranges though I'm not sure how to access them in the `isSpaced` function (https://github.com/jkimbo/eslint-plugin-react/blob/2b5a612755723862ec51790b7a6037d3ed68e594/lib/rules/jsx-curly-spacing.js#L37-L45)

jsx-curly-spacing rule breaks with comments

---

README.md
docs/rules/jsx-no-target-blank.md
index.js
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

New rule to protect against a pretty serious security vulnerability: https://mathiasbynens.github.io/rel-noopener
Using `target='_blank'` to open a link in a new tab is inherently unsafe and should always be accompanied by `rel='noopener noreferrer'`

New Rule: jsx-no-target-blank

---

README.md

Keep rules in alphabetic order.

alphabetize readme rules

---

lib/rules/jsx-no-bind.js
tests/lib/rules/jsx-no-bind.js

Takes care of part of the issue brought up in #474.

Catch bind in render when assigned to a variable (#474)

---

lib/rules/jsx-closing-bracket-location.js
tests/lib/rules/jsx-closing-bracket-location.js

Currently situation where last prop is both multiline and starts at the same line as the opening bracket is not handled very well.
Example of the issue can be found here: https://github.com/yannickcr/eslint-plugin-react/issues/454#issuecomment-193284260

Improved multiline prop support for jsx-closing-bracket-location

---

lib/util/Components.js
package.json
tests/lib/rules/prop-types.js

This small addition enables linting component-specific rules if the author uses a JSDoc explicitly indicating that the component is a descendent of React.Component
e.g.
```
/** @extends React.Component */
class MyClass extends ChildClass {
...
```
Provides a good workaround for issues such as #68

Parse explicit declaration that class extends React.Component

---

index.js
lib/rules/no-render-return-value.js
tests/lib/rules/no-render-return-value.js

As documented initially in https://github.com/facebook/react/pull/6400 and on the documentation website at http://facebook.github.io/react/docs/top-level-api.html#reactdom.render
The return value of `ReactDOM.render` is considered legacy. It's rather hard to deprecate the return value of an element with runtime code, but fairly straight-forward with static analysis so this is intended to support the communities education and eventual migration from using that pattern.

no-render-return-value. closes #531

---

docs/rules/self-closing-comp.md
lib/rules/self-closing-comp.js
tests/lib/rules/self-closing-comp.js

This pr adds an option to the self-closing-comp suggested #572, which is corresponding what type of tags (`{component: <boolean>, html: <boolean>}`) should be self-closed when this is possible. **Note**: this not changes current behavior, default option is `{component: true, html: false}`, but in the next major
release we can change it to `{component: true, html: true}` to enforce all tags to be self-closing when that is possible.

Add option to the self-closing-comp

---

README.md
docs/rules/require-optimization.md
index.js
lib/rules/require-optimization.js
tests/lib/rules/require-optimization.js

Fixes #240. Adds a new rule called `require-optimization` which ensures all components either have a `shouldComponentUpdate` method or a `PureRenderMixin`.
Tested on several large React project repos without any issues using a beta release of this rule here (https://travis-ci.org/Eight-Solutions/eslint-plugin-cumul8). General feedback from users of this rule so far have been very positive.

Adds new require-optimization rule.

---

docs/rules/no-comment-textnodes.md
index.js
lib/rules/no-comment-textnodes.js
tests/lib/rules/no-comment-textnodes.js

Our team has run into issues where people mistakenly commit comments as text nodes, and they have managed to get through code review and appeared (embarrassingly) in our UI. I threw together this rule to try and catch such occasions, and thought it might be useful to other users of this ESLint plugin.
Feedback, comments greatly appreciated.

Add new rule: no-comment-textnodes

---

README.md

The README didn't make it clear that rule names should be prefixed with `react/`, so I fixed it.  Reasonable solutions:
1. Show an example `rules` block.
2. Add `react/` to each rule name in the index.
I've done both here.  Feel free to choose one or accept both.  :smiley:

[added] react/ prefix to rule names

---

docs/rules/no-unknown-property.md
lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

Context: insin/babel-plugin-react-html-attrs#4

Add ignore config to no-unknown-property rule

---

README.md
docs/rules/jsx-curly-spacing.md
lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-curly-spacing.js

Rule now accepts a `spacing` object, which takes its defaults from the first always/never option. It accepts:
- “default”: which controls all values unless otherwise specified.
- “objectLiterals”: controls object literal values.
(in other words, omitted spacing option values default to the first option, which is "always" or "never")
Warnings around object literals themselves are removed, because the built-in `object-curly-spacing` rule handles that.
(Re https://github.com/yannickcr/eslint-plugin-react/pull/604#issuecomment-223824638)

`jsx-curly-spacing`: fix “alternative” option

---

lib/rules/jsx-key.js
lib/rules/jsx-no-bind.js
lib/rules/jsx-pascal-case.js
lib/rules/jsx-sort-props.js
package.json

as discussed in evcohen/eslint-plugin-jsx-a11y#54 we can integrate the [jsx-ast-utils](https://github.com/evcohen/jsx-ast-utils) package here for better code reuse across these packages. 
We can start adding API functions to fit use cases for this project as well to `jsx-ast-utils` in the next few iterations (i.e. styling and spacing functions)

Integrate jsx-ast-utils

---

lib/rules/jsx-pascal-case.js
tests/lib/rules/jsx-pascal-case.js

Only test object (part before the `.`). Fixes #637

[fix] - Fix jsx-pascal-case for JSXMemberExpressions.

---

lib/rules/jsx-no-bind.js
tests/lib/rules/jsx-no-bind.js

Fixes #532 
[function-bind](http://babeljs.io/blog/2015/05/14/function-bind)

[new] - Throw error on stage-0 function-bind syntax.

---

package.json

- specify ESLint 2 **or 3** as a peerDependency to help `npm` users identify compatibility issues
- specify Node.js 0.10 as the minimum (same as ESLint 2)

bumps deps; peerDeps allows ESLint 2 or 3

---

lib/rules/jsx-filename-extension.js
tests/lib/rules/jsx-filename-extension.js

[Fix] Don’t check filenames on text input.

---

lib/rules/no-comment-textnodes.js
tests/lib/rules/no-comment-textnodes.js

Fix no-comment-textnodes incorrectly catching urls (fixes #664)

---

lib/rules/jsx-no-bind.js
lib/util/Components.js
tests/lib/rules/jsx-no-bind.js

Fix jsx-no-bind reporting errors on render functions that don't return JSX (Fixes #663)

Fix jsx-no-bind reporting errors on render functions

---

lib/rules/jsx-closing-bracket-location.js
tests/lib/rules/jsx-closing-bracket-location.js

Use the correctColumn attribute that is populated above.
I don't quite understand the error, but running with `--fix` I would still get errors that look like
"  247:37  error  The closing bracket must be aligned with the last prop (expected column 9)   react/jsx-closing-bracket-location"
But with this change, `--fix` does the right thing.

Repair `--fix` for props-aligned in jsx-closing-bracket-location

---

README.md
index.js
tests/index.js

Much like eslint:all
http://eslint.org/docs/user-guide/configuring#using-eslintall

Add in an "all" config

---

README.md
docs/rules/jsx-no-comment-textnodes.md
docs/rules/jsx-require-extension.md
docs/rules/jsx-wrap-multilines.md
index.js
lib/rules/jsx-no-comment-textnodes.js
lib/rules/jsx-require-extension.js
lib/rules/jsx-wrap-multilines.js
lib/rules/no-comment-textnodes.js
lib/rules/require-extension.js
lib/rules/wrap-multilines.js
tests/lib/rules/jsx-no-comment-textnodes.js
tests/lib/rules/jsx-require-extension.js
tests/lib/rules/jsx-wrap-multilines.js

Rename some JSX-specific rules to include jsx- prefix

---

docs/rules/jsx-sort-props.md
lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

I think `callbackLast` having precedence is a better fit than the other way around.

Added `shorthandFirst` option to `jsx-sort-props` rule. (Fixes #391)

---

lib/rules/jsx-filename-extension.js
tests/lib/rules/jsx-filename-extension.js

Things could get very spammy for no reason if you had a lot of JSX in a "disallowed file". I kept the first node for the report since it facilitates locating the culprit.
Let me know if there is anything!

Now only reporting up to once per file for `jsx-filename-extension`

---

docs/rules/require-optimization.md
lib/rules/require-optimization.js
tests/lib/rules/require-optimization.js

I like this require-optimization rule, but it is not suitable for our implementation. I think a lot of people use https://www.npmjs.com/package/pure-render-decorator or similar solutions. It is the reason I made an additional option. Now it will be possible to register a list of names of decorators, which allow to pass validation.
I hope my change will be useful and will get in release =)

New rule options allowDecorators in require-optimization

---

docs/rules/jsx-uses-react.md
docs/rules/no-deprecated.md
lib/rules/jsx-uses-react.js
lib/rules/no-deprecated.js
lib/util/pragma.js
lib/util/version.js
tests/lib/rules/jsx-uses-react.js
tests/lib/rules/no-deprecated.js

These options were deprecated in a previous release. Now that we are preparing for a major version bump, we want to clear them out. 
Addresses #686.

Remove rules deprecated options

---

lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

When running the `jsx-no-target-blank` rule against code like the following:
```
<a {...this.props} target='_blank' />
```
the following error would be raised:
```
TypeError: Cannot read property 'name' of undefined
```
The root cause is that the node representing the spread props does not have a `name` property.
Note that if the desired `rel` attribute appears before the spread props, the error does not occur.

Handle spread props in jsx-no-target-blank rule

---

lib/rules/jsx-uses-vars.js
tests/lib/rules/jsx-uses-vars.js

When I'm importing a component (say Input) which has other subcomponents
as it's properties (like Input.Placeholder, Input.Button, etc), and
there is another different component imported by a same name (say
Button), and then if I use `<Input.Button>` in my code then eslint doesn't
tell that `<Button>` is unused.
Reproducible code:
```jsx
import React from 'react';
import Button from './Button';
import Input from './Input';
export default class X extends React.Component {
render() {
return <Input.Button />;
}
}
```
What should be expected?
The import Button from './Button'; line should be highlighted with a
no-unused-vars error. You can see this if you just use `<Input>` in the
render function instead of `<Input.Button>`.
This was happening because the rule was checking for all …

Teach jsx-uses-vars about components as object properties

---

index.js

Using `dangerouslySetInnerHTML` is already very explicit and there are some things you actually can't do w/out it. I don't think I'd say that using it isn't "recommended". It's totally ok if you use it the way it's intended to be used.

Remove no-danger from recommended rules

---

docs/rules/no-did-mount-set-state.md
docs/rules/no-did-update-set-state.md
lib/rules/no-did-mount-set-state.js
lib/rules/no-did-update-set-state.js
tests/lib/rules/no-did-mount-set-state.js
tests/lib/rules/no-did-update-set-state.js

There are many people who regularly call `this.setState` in a callback
in `componentDidMount` and `componentDidUpdate`. Although there
was an option for this rule that would allow this to happen, we have
decided to make it the default.
Addresses #686.

Enable allow-in-func mode by default in no-did-mount-set-state and no-did-update-set-state rules

---

docs/rules/forbid-prop-types.md

This is a reference to code, so we should use backticks.
I've also changed it to be "PropTypes" instead of "PropType" since
that is what you would see in code.

Add backticks in forbid-prop-types documentation

---

index.js
tests/index.js

Since they are replaced by better versions

Don't include deprecated rules in `all` config

---

lib/rules/jsx-handler-names.js
tests/lib/rules/jsx-handler-names.js

The rule was triggered for a property `only`. This is because the regex
was checking for the prefix (by default "on") followed by any
characters. We can fix this by ensuring that the prefix we are checking
for is always followed by an uppercase character.
It was suggested in the issue that we might want to allow this rule to
accept a regex, which would allow for more flexibility in how this rule
is configured. I think this might be a nice enhancement, but since this
fix was so simple I decided to go with the quick and easy win at this
time.
Fixes #571

Prevent jsx-handler-names from incorrectly flagging `only`

---

lib/rules/wrap-multilines.js
tests/lib/rules/wrap-multilines.js

Wrap multilines was broken after switching to new eslint rule format.

Fix wrap-multilines rule

---

README.md

Folks might be arriving at this plugin, looking for
accessibility rules. Thankfully, there is another good
plugin that handles that, so I think it would be nice
for us to point people in the right direction.

Add link to eslint-plugin-jsx-a11y

---

README.md
docs/rules/forbid-component-props.md
docs/rules/forbid-prop-types.md
index.js
lib/rules/forbid-component-props.js
tests/lib/rules/forbid-component-props.js

Passing `className` or `style` to your Components is a source of much
hidden complexity that can be solved either by using a wrapper to add
styling or by adding props for specific styling. This rule aims at
preventing these props from being passed to your Components, to help
minimize hidden complexity.
The original issue proposed having this rule check propTypes. I
considered that route, but I worry that it won't be as effective for
people who do not have every prop used by the component listed in the
propTypes. Additionally, propTypes seem to have waning interest from the
React team in favor of Flow annotations, so I think in the long run
checking for this at the callsite will be more stable.
More information can be found by reading: …

Add rule to forbid className and style being passed to Components

---

lib/rules/require-optimization.js
tests/lib/rules/require-optimization.js

There was a problem with the ad functions and methods in classes, sample code -
```jsx
import React from "react";
class YourComponent extends React.Component {
handleClick() {}
render() {
return <div onClick={this.handleClick}>123</div>;
}
}
```
```json
{
"rules": {
"react/require-optimization": 2  
}
}
```
This code has been checked and is not output error, it is wrong

[Fix] In require-optimization corrected test for function declaration

---

lib/rules/jsx-uses-vars.js
tests/lib/rules/jsx-uses-vars.js

When importing an object and using a deeply nested property as a component, mark that variable as used.

Fix jsx-uses-var to handle nested object properties

---

README.md
docs/rules/no-danger-with-children.md
index.js
lib/rules/no-danger-with-children.js
tests/lib/rules/no-danger-with-children.js

Prevents dangerouslySetInnerHTML and children from being used at the same time (Fixes #710)

Add new dom-elements-no-danger-with-children rule (Fixes #710)

---

README.md
lib/util/Components.js
lib/util/pragma.js

Allows the the plugin to lint components created in a non-standard way with
configuration such as
```js
var MyComponent = SpecialReact.createSpecialClass({
...
});
```
with config looking like:
```json
{
"settings": {
"react": {
"createClass": "createSpecialClass",
"pragma": "SpecialReact", 
}
}
}
```

Add Pragma for createClass factory method

---

lib/rules/no-danger-with-children.js
tests/lib/rules/no-danger-with-children.js

Also no longer breaks for `...rest` properties.

Handle nested levels of spread properties (Fixes #771)

---

docs/rules/sort-comp.md
lib/rules/sort-comp.js
tests/lib/rules/sort-comp.js

Hey! I did a basic pass to add support for typeAnnotions in sort-component. Let me know what you think about that. I tested on files from react-native lib & couple of my own files and it everything seemed to be working properly so far.
https://github.com/yannickcr/eslint-plugin-react/issues/235
For anyone wanting to use that right now put this in your package.json:
```
"eslint-plugin-react": "https://github.com/dozoisch/eslint-plugin-react#typeannotations",
```

Add support for typeAnnotions in sort-comp

---

README.md
docs/rules/jsx-space-before-closing.md
docs/rules/self-closing-comp.md
lib/rules/self-closing-comp.js
tests/lib/rules/self-closing-comp.js

If you would like comments removed just let me know. Thanks for the awesome project.

Add auto fix for self-closing-comp

---

README.md
docs/rules/style-prop-object.md
index.js
lib/rules/style-prop-object.js
tests/lib/rules/style-prop-object.js

Add new dom-elements-style-is-object rule (Fixes #715)

---

docs/rules/prefer-stateless-function.md
lib/rules/no-multi-comp.js
lib/rules/prefer-stateless-function.js
lib/rules/require-optimization.js
lib/util/Components.js
tests/lib/rules/prefer-stateless-function.js

prefer-stateless-function should not return a warning when the user uses `PureComponent` to opt in for free optimisations with `shouldComponentUpdate` and is using props or context. 
Current false positive: 
```{js}
class Foo extends React.PureComponent {
render() {
return <div>{this.props.foo}</div>;
}
}
```
I first only added the same `isPureComponent` check as [require-optimization](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/require-optimization.js#L92) does. But realized that components that are extending form PureComponent but don't use `this.props` or `this.context` should be written as a pure function as well. So I had to change the existing checks a bit to check that too. 
Yeah I know, I could have first reacted to the discussion at #777, but I thought …

Make prefer-stateless-function PureComponent aware

---

README.md
docs/rules/no-unused-prop-types.md
index.js
lib/rules/no-unused-prop-types.js
lib/util/Components.js
tests/lib/rules/no-unused-prop-types.js

Fixes #226 by adding an new `unused-prop-types` rule.
The rule is based very heavily on the `prop-types` rule and shares a lot of the same code. For the time being, I have not made any attempts at breaking out the shared code into a reusable utility file. Please advise on the best way to do this. I was simply thinking of dropping a `proptypes.js` file into the `utils` directory with all the shared functions. If that's acceptable, let me know and I will do that.
Have tested against several React projects with great success so far. No false positive problems yet, but it needs a lot more testing against other repos. I'm hoping other users will report issues as they try it. For my needs, this rule is working great.
Can be tested by following these steps:
```
npm install …
```

Adds new `no-unused-prop-types` rule

---

docs/rules/prop-types.md

Because examples for ES6 are not immediately clear - I tried `propTypes: { ... }` in ES6 and it didn't work unless it's `static`.

Add examples of correctly specified propTypes

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

Fixes several false positives failures in the `no-unused-prop-types` rules:
- Ensures destructured props in component lifecycle methods are properly counted towards used props 
- Ensure common `nextProps` and `prevProps` property names in lifecycle methods are correctly counted towards used props
- Fixes https://github.com/yannickcr/eslint-plugin-react/issues/801

Fixes a few false positive failures in the `no-unused-prop-types` rule

---

lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

This pull request seeks to resolve lint errors which are raised when the `jsx-no-target-blank` rule is enabled when `target="_blank"` is applied to anything other than an anchor element. The [documentation for this rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-no-target-blank.md) clearly states that `<p target="_blank"></p>` is not considered an error, but adding this missing test case reveals that the rule applies to all elements.
We observed this in https://github.com/Automattic/wp-calypso/pull/7680 where we have custom components which handle the incoming `target` prop and apply the `rel` as necessary through custom render logic.

jsx-no-target-blank: Target only anchor elements

---

lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

`<a href="foo" target="_BLANK">` should also trigger no-target-blank.
Now it does.

Case insensitive comparisons for no-target-blank

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

This PR fixes issue #825 by ensuring that properties are valid arrays before trying to loop through their destructured values.

Fixes Issue #825

---

README.md
docs/rules/no-unescaped-entities.md
index.js
lib/rules/no-unescaped-entities.js
tests/lib/rules/no-unescaped-entities.js

I will also add in some documentation around this, but wanted to get this out there to make sure I was on the right track
I ran this on our codebase and it caught a bunch of errors so it appears to work

Rule for requiring HTML entities to be escaped

---

README.md
docs/rules/no-children-prop.md
index.js
lib/rules/no-children-prop.js
tests/lib/rules/no-children-prop.js

Prevents children being passed as props. Children should be actual children.
I've never written an eslint rule, so any suggestions are definitely appreciated.

Add new no-children-prop rule (Fixes #720)

---

lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

Right now jsx-indent linter won't catch cases like:
```
<App>
{test}
</App>
```
This diff will add support for JSXExpressionContainer

Add JSXExpressionContainer support for jsx-indent rule

---

lib/rules/style-prop-object.js
tests/lib/rules/style-prop-object.js

Fix style-prop-object to deal with null and spread props that can't be resolved

---

lib/rules/no-children-prop.js
tests/lib/rules/no-children-prop.js

Nodes of type `ExperimentalSpreadProperty` don’t have a `key` property, causing the `no-children-prop` to raise a “Cannot read property ‘name’ of undefined” error.
Code such as:
```
return React.createElement(
elementType,
{ className: classNames, ...otherProps },
children
)
```
will trigger the error.

Handle spread props in no-children-prop rule

---

docs/rules/jsx-indent.md
lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

Due to limitations of the RuleFixer class there is no way to safely fix these two cases:
1. When a file uses spaces but options requires tab and vice-versa.
2. If a parent node didn't pass the rule, autofixer won't fix folded child nodes. Second run will actually fix the next child node.
Even with these limitations the autofixer found to be very useful and was already used on Pinterest codebase.

jsx-indent rule autofixer

---

docs/rules/prop-types.md
lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Adding the `prop-types` rule can be a daunting task for
projects that have not been consistent about using prop
types to begin with.
This allows users to slowly opt-in to prop-types validation
by only erroring on "incomplete" propTypes declarations.

Allow skipping prop-types validation when not declared

---

docs/rules/jsx-no-bind.md

The rule name is missing from the `jsx-no-bind` title / header.
This PR adds it, like all the other rules.

Adds missing rule name for `jsx-no-bind` documentation.

---

docs/rules/react-in-jsx-scope.md

This way beginners using ES6 today won’t be confused about using something called "require" which they might be seeing for the first time.

Add ES6 import example to "jsx in scope" docs

---

lib/rules/jsx-closing-bracket-location.js
tests/lib/rules/jsx-closing-bracket-location.js

The autofix for this rule substitutes spaces even when the code is normally indented with tabs. This change accommodates tabs, spaces, and even mixed whitespace (we won't judge).

Support tab indentation

---

lib/rules/forbid-component-props.js
tests/lib/rules/forbid-component-props.js

Please check the information here https://github.com/yannickcr/eslint-plugin-react/pull/839 
I'm trying to include [xo](https://github.com/sindresorhus/xo) in one of our projects, i hit the issue exactly the same as @pfhayes . And after dig into the codebase, i found we have a self reference linked jsx element and that cause the issue, Like this 
```
class Foo extends React.createClass {
render() {
return <this.Bar  className='demo' />
}
}
```
That's cause the issue. I don't think it's a best practice, but at least it shouldn't crash the workflow.

Valid self reference jsx element.

---

docs/rules/prefer-stateless-function.md

When describing `PureComponent` behavior in the Rule Details section, it takes a lot more reading to realize it's a flag you must set to true.

mention ignorePureComponents earlier

---

index.js

This change allow you to extends "plugin:react/{something}" without having to do something more.
If you just extends one config, you get errors about missing rules definition.

Fix incomplete recommended configs

---

index.js
lib/rules/no-comment-textnodes.js
lib/rules/require-extension.js
lib/rules/wrap-multilines.js
tests/index.js

Over on [eslint-find-rules](https://github.com/sarbbottam/eslint-find-rules), there has been some discussion about being able to detect deprecated rules in order to [not report them as unused](https://github.com/sarbbottam/eslint-find-rules/issues/172) and to [report when they are still being used](https://github.com/sarbbottam/eslint-find-rules/issues/188).
In order to implement those features, there needs to be a way to detect that a rule has been deprecated.  Core ESLint rules that are deprecated are marked as such in their metadata.
This PR adds the same `deprecated` flag to the metadata of the deprecated rules in this plugin.
It might be possible to make use of this metadata in `index.js` to automatically determine which rules are deprecated, rather than duplicating the information …

Mark deprecated rules as deprecated in their metadata

---

docs/rules/jsx-first-prop-new-line.md
lib/rules/jsx-first-prop-new-line.js
tests/lib/rules/jsx-first-prop-new-line.js

addresses another part of https://github.com/yannickcr/eslint-plugin-react/issues/878

jsx-first-prop-new-line: add multiline-multiprop option

---

docs/rules/jsx-indent.md
lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

Everything seems correct except for the very last test. 
The real output is:
``` js
function App() {
return (
<App>
<Foo />
</App>
);
}
```
But I would _expect_ the output to be:
``` js
function App() {
return (
<App>
<Foo />
</App>
);
}
```
Anyone have any ideas what I'm doing wrong or if somehow this is indeed expected behavior?

Autofix: `jsx-indent`: Add support for tabs

---

README.md
docs/rules/jsx-first-prop-new-line.md
lib/rules/jsx-first-prop-new-line.js
tests/lib/rules/jsx-first-prop-new-line.js

Hi I have made an autofix for the rule jsx-first-prop-new-line for a fork and I thought it would be useful to have it on the main repo.
I am aware and monitoring #883. Will update the autofix after that is approved! Meanwhile, PR for visibility and to start the process :)

jsx-first-prop-new-line: autofix

---

README.md
docs/rules/jsx-tag-spacing.md
index.js
lib/rules/jsx-tag-spacing.js
tests/lib/rules/jsx-tag-spacing.js

Replaces #706 after some discussion summarised on https://github.com/yannickcr/eslint-plugin-react/issues/693#issuecomment-234842584.

Add jsx-tag-spacing rule (Fixes #693)

---

lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

This PR is an attempt at fixing #945.
I'm no master at ESLint or it's parser, but adding some new tests and looking at the AST and figuring out what it would take to make the new test pass while not breaking the tests from  https://github.com/yannickcr/eslint-plugin-react/commit/d88ee379079cee18e3bc718dddc7dfc1c91bee1c gave the following solution.
I also ran this version of the module against my large react project and all errors that occurred with `6.6.0` was then gone.

Fix jsx-indent bug on multiline ternary

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

The option `no-unused-prop-types` doesn't work properly for shape proptypes in lots of popular cases: #851, #819 and other cases, like when used outside of the component class.
This causes very annoying inconviences.
So currently the option only works without problems if the `skipShapeProps` is set to `true`. Therefore it's best to skip linting shape props by default until the mentioned problems are fixed and setting this option to false actually becomes useful.

skipShapeProps should be enabled by default until it works properly

---

lib/rules/jsx-tag-spacing.js

Fix `jsx-tag-spacing` crash when options object isn't passed

---

docs/rules/sort-comp.md

Also improve some of the readability!
Love this plugin!

Fix minor typos

---

README.md

The rule's docs specify that this rule is fixable, but the readme did not.

Indicate that jsx-indent is fixable (README)

---

index.js

ESLint looks for the `plugins` config property. Currently, if you extend `plugin:react/recommended` you still need to add `plugins: ['react']`.
This commit fixes the typo, so you no longer need to add the plugins prop when you extend `recommended` or `all` configs.
Before:
```
1:1  error  Definition for rule 'react/no-find-dom-node' was not found          react/no-find-dom-node
1:1  error  Definition for rule 'react/display-name' was not found              react/display-name
1:1  error  Definition for rule 'react/jsx-no-undef' was not found              react/jsx-no-undef
```
After:
```
28:21  error  'items' is missing in props validation      react/prop-types
28:27  error  'items.map' is missing in props validation  react/prop-types
```

Fix `plugin` typo in configs

---

README.md
docs/rules/no-array-index-key.md
index.js
lib/rules/no-array-index-key.js
tests/lib/rules/no-array-index-key.js

This rule will warn when using the array index as the `key`. As a first
pass, I decided to implement this for `Array.prototype.map`, since that
is likely the most common case, but it theoretically could be expanded
to find other cases so I kept the naming more generic.
Like many rules, this one is imperfect and is prone to some false
positives and negatives. For instance, if someone defines a `.map()`
function on an object that doesn't have the same signature as
`Array.prototype.map`, this will likely end up warning in those cases.
However, I think the value of this rule outweighs its hypothetical
drawbacks.

Add no-array-index-key rule

---

lib/util/Components.js
tests/lib/rules/prop-types.js

This is just a silly little thing – there's no way for async functions to be components.

Don't treat async functions as components

---

README.md
docs/rules/require-default-props.md
index.js
lib/rules/no-unused-prop-types.js
lib/rules/prop-types.js
lib/rules/require-default-props.js
lib/util/annotations.js
lib/util/variable.js
tests/lib/rules/require-default-props.js

Implements the new `require-default-props` rule. (#528)
~~**This is a work in progress**: support for flow annotations hasn't been added yet, but the code is already considerably big, so I thought I could get the PR up already to get some early feedback on implementation, docs, missing test cases, etc.~~ flow annotation support has now been added.
This is my first time contributing to eslint-plugin-react, so I hope I didn't do something horribly wrong in the implementation of the rule 😟

New: Add require-default-props rule (fixes #528)

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Fixes #961 
It looks like getKeyValue was naively grabbing the first token for `'ObjectTypeProperty'`, which was sometimes a '+'.  There's probably a more robust solution, but I've just opted to account for `'+'` and `'-'` as possible tokens that might be encountered.

#961 support flow variance syntax

---

tests/lib/rules/prop-types.js

Can't reproduce claimed bug in #991. The new test case asserts that it works, anyway.

Add regression for #991

---

.travis.yml
lib/rules/no-children-prop.js
lib/rules/no-danger-with-children.js
lib/rules/require-default-props.js
lib/rules/style-prop-object.js
package.json

[Fix] Don’t rely on `Array#find` existing pre node 4

---

docs/rules/prefer-stateless-function.md

ESLint will throw a very unclear complaint to somebody who converts a regular React component into a Pure Component (stateless) as instructed in this doc, if contextTypes are defined. Because there is no "this.context" accessible, it's unclear to someone that they need to use `props, context` arguments.
This will just help clarify and probably save a couple of people a few minutes of research if they come from an ESLint error. Cheers!

show context in pure component for clarity

---

.eslintrc
index.js
lib/rules/display-name.js
lib/rules/jsx-closing-bracket-location.js
lib/rules/jsx-max-props-per-line.js
lib/rules/jsx-no-duplicate-props.js
lib/rules/jsx-tag-spacing.js
lib/rules/jsx-wrap-multilines.js
lib/rules/no-array-index-key.js
lib/rules/no-direct-mutation-state.js
lib/rules/no-multi-comp.js
lib/rules/no-set-state.js
lib/rules/no-unused-prop-types.js
lib/rules/prefer-stateless-function.js
lib/rules/prop-types.js
lib/rules/require-default-props.js
lib/rules/require-optimization.js
lib/rules/require-render-return.js
lib/rules/sort-comp.js
lib/util/Components.js
package.json
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

Fixes #955.
I'll worry about removing all the for..in loops (which should also never be used) in a future PR.

[Fix] Never call Object prototype builtins directly

---

lib/rules/require-default-props.js
tests/lib/rules/require-default-props.js

This fixes the issue I reported in #1017.
The condition I added is hit when code like the following is used:
```js
type Props = Message
```
This just takes the right side of the annotation (`Message`) and tries to find that variable in scope and then continues on.

Fix `require-default-props` rule when using Flow type from assignment

---

docs/rules/no-unused-prop-types.md

Addresses the documentation comments from https://github.com/yannickcr/eslint-plugin-react/issues/976#issuecomment-272015442

Minor documentation updates for no-unused-prop-types rule for issue 976

---

lib/util/Components.js
lib/util/variable.js
tests/lib/rules/display-name.js

Fixes #996. This will prevent document.createElement triggering a
false positive for react/display-name.

Check for createElement being called from React

---

docs/rules/jsx-sort-props.md
lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

Adds a `noSortAlphabetically ` option to `jsx-sort-props` which will allow sorting of callbacks last without forcing alphabetical ordering.
Closes #541
Closes #786

jsx-sort-props noSortAlphabetically option

---

tests/lib/rules/require-default-props.js

Fix error while trying to map over `annotation.properties` that are undefined for `AnyTypeAnnotation`
Fix #1043.

Fix require-default-props rule filter of undefined exception

---

README.md
docs/rules/void-dom-elements-no-children.md
index.js
lib/rules/void-dom-elements-no-children.js
tests/lib/rules/void-dom-elements-no-children.js

There are some HTML elements that are only self-closing (e.g. `img`,
`br`, `hr`). These are collectively known as void DOM elements. If you
try to give these children, React will give you a warning like:
> Invariant Violation: img is a void element tag and must neither have
> `children` nor use `dangerouslySetInnerHTML`.
This rule prevents this from happening.
Since this is already a warning in React, we should add it to the
recommended configuration in our next major release.
Fixes #709

Add void-dom-elements-no-children rule

---

README.md
docs/rules/forbid-foreign-prop-types.md
index.js
lib/rules/forbid-foreign-prop-types.js
tests/lib/rules/forbid-foreign-prop-types.js

People may want to use babel-plugin-transform-react-remove-prop-types to remove propTypes from their components in production builds, as an optimization. The `forbib-foreign-prop-types` rule forbids using another component's prop types unless they are explicitly imported/exported, which makes that optimization less prone to error.
I've included the use-cases described in #696 as tests. I'd be happy to add additional test cases if recommended.
Fixes #696

Add forbid-foreign-prop-types rule

---

docs/rules/jsx-max-props-per-line.md
lib/rules/jsx-max-props-per-line.js
tests/lib/rules/jsx-max-props-per-line.js

addresses parts of https://github.com/yannickcr/eslint-plugin-react/issues/878
will happily change option names

Jsx max props per line updates

---

lib/util/Components.js
tests/lib/rules/no-unused-prop-types.js

detect used props in jsx

---

README.md
docs/rules/forbid-elements.md
index.js
lib/rules/forbid-elements.js
tests/lib/rules/forbid-elements.js

May specify a list of forbidden elements and their desired replacement
elements.
addresses https://github.com/yannickcr/eslint-plugin-react/issues/887

Add forbid-elements rule

---

docs/rules/jsx-indent.md
lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

This fixes the `--fix` for `jsx-indent`. Specifically my issue was with tabs (Fixes #1057), but this fixes the same issues with spaces as well.
Highlevel important bits:
1. Adds fix for when the ending of a tag (`>`) is on its own line. This will now lint and fix properly.
2. Adds fix for linting and fixing Literal strings inside JSX
3. Adds configuration option called `indentLogicalExpressions` which will allow for indenting the right side of logical expressions (documented)
4. Adds fix for linting and fixing the indentation of the closing tag.

[Fix] jsx-indent with tabs

---

lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

Template strings are constructed differently from other tokens in espree. Other tokens are created by the Token class and are thus Token class objects. They look like this:
```
Token {
type: 'String',
value: '"bar"',
start: 44,
end: 49,
loc:
SourceLocation {
start: Position { line: 4, column: 11 },
end: Position { line: 4, column: 16 } },
range: [ 44, 49 ] }
```
Template tokens, however, are constructed differently and end up as plain JavaScript objects, which look like this:
```
{ type: 'Template',
value: '`bar`',
loc:
{ start: Position { line: 4, column: 11 },
end: Position { line: 4, column: 16 } },
range: [ 44, 49 ] }
```
See: [espree's token-translator.js](https://github.com/eslint/espree/blob/58f75be6b89d8904b6366ed368045cb02c4a4e33/lib/token-translator.js#L43)
As a result of this …

Fix error caused by templates in ConditionalExpressions (jsx-indent)

---

lib/rules/void-dom-elements-no-children.js
lib/util/Components.js
tests/lib/rules/void-dom-elements-no-children.js

This ensures that the rule only checks for a `createElement` call from
React. It will also prevent the rule from failing when it hits a
`createElement` that only has an element as an argument.
This PR addresses #1073.

Update void-dom-elements-no-children createElement checks

---

lib/util/Components.js
tests/lib/rules/no-multi-comp.js

Previously, when createElement was destructured from React, it would
cause any function defined in the file to be flagged as a React
Component. This change makes it such that the function must call
createElement to be considered a component.
Fixes #1088 
---
Source of bug:
https://github.com/yannickcr/eslint-plugin-react/commit/416deff06d90b100f991bfbf86f7484061dca0d2#diff-bafb3355a409c4ba076a9e3d609ad65bR294
Note: Not sure if this is the best place for this test. I feel like component detection testing should have its own place where it happens. It seems like you have to run the whole test suite to see if Components are still being detected correctly. Thankfully the whole test suite runs fairly quickly.

Bug fix for false positives with no-multi-comp

---

docs/rules/void-dom-elements-no-children.md

Add the name of the rule in parentheses at the end of Markdown title like in other documentation files.

Improve title in void-dom-elements-no-children.md

---

docs/rules/no-string-refs.md

Attempting to improve clarity and grammar slightly, while inserting a needed comma in the second sentence.

Comma-fix and clarity

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

Fixes #1079
I did the same comparisons as the `prop-types` rules (https://github.com/yannickcr/eslint-plugin-react/blob/b64648521f9a7949eef4cd1a210768e906b4f3d1/lib/rules/prop-types.js#L130) for the `no-unused-prop-types` rule.
This way they both handle nextProps identically.
I also borrowed the test case from #1105.

Fix nextProps false positive in no-unused-prop-types

---

docs/rules/no-unused-prop-types.md

The `lastname` prop was indented with a tab instead of 4 spaces.

Fix indentation in no-unused-prop-types example.

---

README.md
docs/rules/no-will-update-set-state.md
index.js
lib/rules/no-did-mount-set-state.js
lib/rules/no-did-update-set-state.js
lib/rules/no-will-update-set-state.js
lib/util/makeNoMethodSetStateRule.js
tests/lib/rules/no-will-update-set-state.js

Basically just a copy and paste of the `no-did-update-set-state` rule for `componentWillUpdate`.  This rule would have saved me a fair bit of time tracking down an issue where this pattern had been used by accident so I thought it was worthwhile adding support for.

Add no-will-update-set-state rule

---

docs/rules/display-name.md
docs/rules/forbid-component-props.md
docs/rules/forbid-elements.md
docs/rules/jsx-closing-bracket-location.md
docs/rules/jsx-curly-spacing.md
docs/rules/jsx-equals-spacing.md
docs/rules/jsx-handler-names.md
docs/rules/jsx-indent-props.md
docs/rules/jsx-max-props-per-line.md
docs/rules/jsx-no-bind.md
docs/rules/jsx-no-duplicate-props.md
docs/rules/jsx-pascal-case.md
docs/rules/jsx-sort-props.md
docs/rules/no-did-mount-set-state.md
docs/rules/no-did-update-set-state.md
docs/rules/no-multi-comp.md
docs/rules/no-unknown-property.md
docs/rules/no-will-update-set-state.md
docs/rules/prefer-es6-class.md
docs/rules/prefer-stateless-function.md
docs/rules/require-optimization.md
docs/rules/self-closing-comp.md
docs/rules/sort-prop-types.md

Using `"jsx-pascal-case": ...` leads to
```shell
1:1  error  Definition for rule 'jsx-pascal-case' was not found  jsx-pascal-case
```
We need `"react/jsx-pascal-case": ...` as shown in the [Readme](https://github.com/yannickcr/eslint-plugin-react/blob/master/README.md)

Prepend "react/" to rule options documentation code

---

docs/rules/no-render-return-value.md

This fixes a link regarding ReactDOM.render. Previously these docs
were part of the Top Level API docs for React, but have since been
split into their own documentation.

Link fix: ReactDOM docs were broken out

---

docs/rules/prefer-stateless-function.md
lib/rules/prefer-stateless-function.js
tests/lib/rules/prefer-stateless-function.js

Currently prefer-stateless-function warns when using a decorated class
over a stateless function. The decorator syntax only works with classes,
so it makes sense not to warn in this case.
Fixes #1034

prefer-stateless-function w/ decorators

---

docs/rules/no-deprecated.md
lib/rules/no-deprecated.js
tests/lib/rules/no-deprecated.js

Added more deprecations rules regarding last react update.
But it does not seem to match patterns like this:
```javascript
import { PropTypes, createClass } from 'react';
```
Any idea on how we can match those too?

Add new deprecations from 15.5.0

---

docs/rules/jsx-space-before-closing.md
lib/rules/jsx-space-before-closing.js

Closes #967
As discussed in https://github.com/yannickcr/eslint-plugin-react/issues/693#issuecomment-234842809, the `react/jsx-space-before-closing` can now be deprecated in favour of `react/jsx-tag-spacing` which offers a superset of its functionality.
This PR marks the old rule as deprecated and triggers a warning where it is still being used, reusing some code from the also deprecated `react/require-extension` rule.
Let me know if I've missed any steps in the deprecation process!

Deprecate jsx-space-before-closing rule

---

docs/rules/jsx-no-undef.md
lib/rules/jsx-no-undef.js
tests/lib/rules/jsx-no-undef.js

This should allow for the use case outlined in #922.
With the `disallowGlobals` option enabled, the global scope will be ignored
when checking for defined components. Without this option enabled,
Pascal case global variables will be allowed when checking for defined
components.

react/jsx-no-undef allowGlobals option

---

docs/rules/jsx-wrap-multilines.md
lib/rules/jsx-wrap-multilines.js
tests/lib/rules/jsx-wrap-multilines.js

Aka "lambdas"
Close #790
I will duplicate issue desc here:
Given this code, check should not pass
```jsx
const Grade = ({ grade }) =>
<View style={styles.gradeContainer}>
<Text style={styles.grade}>{grade}</Text>
</View>;
```
For this code, check should pass:
```jsx
const Grade = ({ grade }) => (
<View style={styles.gradeContainer}>
<Text style={styles.grade}>{grade}</Text>
</View>
);
```
I leaved this behaviour by-default, but it can break backward compatibility?
May be It should be turned off by default?

jsx-wrap-multilines check arrow functions without block body

---

docs/rules/jsx-first-prop-new-line.md
lib/rules/jsx-first-prop-new-line.js

Right now just enabling the rule does nothing, you actually have to pass in a value. 
This seems very counterintuitive to me.
If you feel the default should be something else I'm fine with whatever.

Add default for jsx-first-prop-new-line

---

docs/rules/jsx-sort-props.md
lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

This PR is in response to reading some of the comments in #807 plus real-world needs by my company: we always put the `key` prop first, and then alphabetize the rest of them.
First time writing an ESLint rule option, so please let me know what could be better.
Thinking about this option, I intentionally placed it before `shorthandFirst` so that it trumps that option. This seemed appropriate to me based on thinking about props as reserved or not, and considering that there are no reserved shorthand props.
For "reserved," I am considering all props that are specifically related to React. So for example, DOM properties are not reserved since they are related to JSX, not React.
-------------------------------------------------------
This adds a new option, `reservedFirst`, to the …

Add a `reservedFirst` option to the `jsx-sort-props` rule

---

lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-curly-spacing.js

From comment https://github.com/yannickcr/eslint-plugin-react/issues/857#issuecomment-299664309:
> Btw. I think there was a small bug: when only "spacing" was set in the extended options, the following line was setting "allowMultiline" to undefined:
>
> ```
> var multiline = context.options[1] ? context.options[1].allowMultiline : true;
> ```
> Then in all the following conditions !multiline was being checked, which yielded a different result than the > default true value would.
>
> Now I'll be checking if the property exists on the config object (using the has package, I found it being used in other rules).

Fix "allowMultiline" being undefined in some cases

---

lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-curly-spacing.js

From comment https://github.com/yannickcr/eslint-plugin-react/issues/857#issuecomment-299698993:
> Found another bug:
>
> ```
> <App foo={
> { bar: true, baz: true }
> } />;
> ```
> This would get 2 errors using the default settings: `There should be no space after '{'` and `There should be no space before '}'`.
>
> This is because conditions for the object literal spacing were written so that the second one was never reached:
>
> ```
>           if (sourceCode.isSpaceBetweenTokens(first, second)) {
>             reportNoBeginningSpace(node, first);
>           } else if (!config.allowMultiline && isMultiline(first, second)) {
>             reportNoBeginningNewline(node, first, config);
>           }
> ```
> If the first condition fails, `isMultiline` will return `false` - there is no …

Fix the newline with object literals bug

---

docs/rules/no-unused-prop-types.md
docs/rules/prop-types.md

This fixes the syntax in the docs for the prop-types rule: "prop-types" (wrong) instead of "react/prop-types" (correct)

FIX: wrong syntax in docs for prop-types rule

---

lib/rules/void-dom-elements-no-children.js
tests/lib/rules/void-dom-elements-no-children.js

For some reason, we were using the following pattern that eslint **don't like**:
```js
const props = {}
React.createElement('img', props)
```

fix: void-dom-elements-no-children

---

docs/rules/jsx-first-prop-new-line.md
docs/rules/jsx-wrap-multilines.md

* Fix typos and clarify default value for `jsx-first-prop-new-line.md`.
* Clarify options and examples for `jsx-wrap-multilines.md`.

Small document improvements

---

README.md
docs/rules/jsx-max-props-per-line.md
lib/rules/jsx-max-props-per-line.js
tests/lib/rules/jsx-max-props-per-line.js

Hi this is my attempt at implementing #929. This aims to implement the fix such that a line with more than max props can be broken into more than 2 lines:
```jsx
// Test case
<App a b c d e />
// [1]
<App a
b
c
d
e />
// [2]
<App a b
c d
e />
```
Would like an opinion on this if it is overkill. An alternate way of fixing would be under the `simple fix` commit (a simple addition of `\n` at a only one point).
Also, aware of #882 and hope to see some progress!

jsx-max-props-per-line: autofix

---

lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

This is a fix for: https://github.com/yannickcr/eslint-plugin-react/issues/1175
I have explained the problem already in the issue, but a quick recap:
* Bug only occurs when using `ignoreCase: true` and `callbacksLast: true`
* `isCallbackPropName(propName)` looks for pattern: `on[A-Z]`
* This pattern can't be found after `toLowerCase()` has been executed (because of `ignoreCase: true`
Bug was introduced in 7.0.0. Reverted the code to how it was working originally, and added a test case to cover this specific combination of options.

Fix regression bug in jsx-sort-props

---

lib/util/Components.js
tests/lib/rules/no-unused-prop-types.js

This related to the following issue: https://github.com/yannickcr/eslint-plugin-react/issues/1183. It also seems to fix: https://github.com/yannickcr/eslint-plugin-react/issues/1135
**Note**: I am not very experienced with the code base. I took a look at this bug to learn a bit more about the code. Therefore I am not sure if my solution is the right solution - but in the worst case perhaps it can help someone else figure out the real issue if it is completely wrong. All the tests continue to pass and I added tests that were failing before my changes.
I tracked the issue down to `components.list()` function.
* It seems that both these callbacks are somehow evaluated to `true` for the condition on line 101: `if (component) {` -- this part seems a bit weird to me? Why are these functions …

Fix false positive in no-unused-proptype

---

docs/rules/jsx-no-target-blank.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

`<a href="relative/path" target="_blank"/>`and `<a href="/absolute/path" target="_blank"/>` are considered safe because the link is placed in the same host, so the rule only issues for URLs with protocols.

Don't issue errors for `<a/>` with target=_blank and non-external URLs

---

README.md
docs/rules/no-redundant-should-component-update.md
index.js
lib/rules/no-redundant-should-component-update.js
tests/lib/rules/no-redundant-should-component-update.js

This will check for `shouldComponentUpdate` defined in a class that extends React.PureComponent.
In regards to the name: I went with what is in the proposal, but perhaps something more informative can be found. Also, I realized that the functions dealing with component properties are duplicated in a few spots, but since there were some differences, I figured they could be refactored out at some other point. That's ultimately up to the reviewers, though.
This PR implements the rule proposed in #985.

Add react/no-redundant-should-component-update

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

The added test illustrates the failing case. Proptypes with quotes
were referred to by the quoted name, instead of by the bare name,
for flow types.

remove quotes when considering the name of a proptype

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

The `react/prop-types` rule incorrectly considers  flow type
annotations on class methods with arguments named `props` as
prop type declarations for the class, even though flow itself
gives them no such weight.
When a react component is defined as a class extending `React.Component`,
and it defines a method that takes an annotated argument named `props`,
then, even though flow still thinks the props have `any` type, the
`prop-types` rule will not produce 'missing in props validation' errors.
A pattern that gets used a lot in React components is as follows:
```javascript
type Props = {...};
class Comp extends React.Component {
constructor(props: Props) {
super(props);
// do something...
}
// ...
}
```
which makes this especially nefarious.

Fix required prop types for classes with annotated methods.

---

lib/rules/no-unescaped-entities.js

See issue: https://github.com/yannickcr/eslint-plugin-react/issues/1211
Implemented as in the issue description:
* Renamed the function
* Removed the noop if

Remove some dead code

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

https://github.com/yannickcr/eslint-plugin-react/issues/1213 https://github.com/yannickcr/eslint-plugin-react/issues/1142#issuecomment-304737468
This makes the no-unused-prop-types work when a prop is used in React lifecycle components other than `componentWillReceiveProps` using the "dot-operator". E.g:
```
shouldComponentUpdate(nextProps) {
if (nextProps.foo) { // This will now be detected
...
}
```
There is one thing to keep in mind: under the current implementation the rule will only work if the parameter is named `nextProps`, `prevProps` or `props`. This logic already existed and I did not want to touch it, though I thought it was kind of odd. Do we want to keep it that way? 
Perhaps we could introduce a rule that validates the parameter names in lifecycle methods - sometimes it's …

Support lifecycle methods with nextProps/prevProps in no-unused-prop-types

---

README.md

Update README to include default-props-match-prop-types rule

---

lib/rules/no-array-index-key.js
tests/lib/rules/no-array-index-key.js

Fixes https://github.com/yannickcr/eslint-plugin-react/issues/1242

Treat "key" without value as a valid case instead for "no-array-index-key"

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

This picks up prop types when set using flow [SuperTypeParameters ](https://flow.org/en/docs/frameworks/react/) such as:
```
type Props = { /* ... */ };
class MyComponent extends React.Component<void, Props, void> {
...
}
```
@ljharb This is modified from the property annotation checks. However, I couldn't test the wrapped `TypeAnnotation` or `NullableTypeAnnotation` resolution checks.

Register prop-types when set through Flow SuperTypeParameters

---

README.md
docs/rules/jsx-closing-tag-location.md
index.js
lib/rules/jsx-closing-tag-location.js
tests/lib/rules/jsx-closing-tag-location.js

For issue #1206:
This rule validates that the closing tag for a multi-line jsx component matches the indentation of the opening tag.

Add indentation rule for closing tag of multi-line jsx

---

README.md
docs/rules/jsx-curly-spacing.md
lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-curly-spacing.js

This is a feature discussed in #857.

Enable curly spacing check for children

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Closes #1255 
Object type spreads are ignored, but only at the top level.  This ignores object type spreads at any level.

Fix nested object type spread

---

README.md

The link in the README to the new `default-props-match-prop-types` rule is broken. This fixes that.

Fix link to default-props-match-prop-types rule

---

docs/rules/no-unused-prop-types.md
lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

PropTypes would previously get ignored if wrapped in forbidExtraProps.

Add support for propTypes wrapped in a function

---

docs/rules/no-direct-mutation-state.md
lib/rules/no-direct-mutation-state.js
tests/lib/rules/no-direct-mutation-state.js

Allow this.state assignment on constructor

---

lib/rules/void-dom-elements-no-children.js
tests/lib/rules/void-dom-elements-no-children.js

I've seen in issue #1240 that using some new patterns from node 4 would be a nice addition. 
Starting out I only updated the ```void-dom-elements-no-children``` rule and test file to use:
* ```const``` and ```let``` instead of ```var```
* Arrow funtions
* Template literals instead of ```[].join()```
* Some minor unification of formatting
I've also seen a [comment](https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/void-dom-elements-no-children.js#L16) in the rule file that using Set would be nice, which is also available with node 4. Can I make that conversion too?
Is this PR okay, and if so, is there a preferred way I should continue with updating?

ES6-ify void-dom-elements-no-children rule and test file

---

README.md
docs/rules/no-unused-prop-types.md
lib/rules/default-props-match-prop-types.js
lib/rules/forbid-prop-types.js
lib/rules/no-unused-prop-types.js
lib/rules/prop-types.js
lib/rules/require-default-props.js
lib/rules/sort-prop-types.js
tests/lib/rules/default-props-match-prop-types.js
tests/lib/rules/forbid-prop-types.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js
tests/lib/rules/require-default-props.js
tests/lib/rules/sort-prop-types.js

Add more support for wrapped propTypes

---

docs/rules/jsx-boolean-value.md
lib/rules/jsx-boolean-value.js
tests/lib/rules/jsx-boolean-value.js

[New] `jsx-boolean-value`: add inverse option for always/never

---

README.md
docs/rules/boolean-prop-naming.md
index.js
lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

At my workplace, we prefer to name our boolean props as "isSomething" or "hasWhatever". This is an ESLint rule which allows devs to specify a Regex pattern for how they want their boolean props named.
Tested with createReactClass, ES6 components, stateless components and Flowtype.
I support, in the future, this rule can be expanded to support naming rules for ANY props, but that felt like overkill for the time being. Hopefully this rule will be useful as is.

New `boolean-prop-naming` rule for enforcing the naming of booleans

---

lib/rules/sort-comp.js
tests/lib/rules/sort-comp.js

Fix sort-comp ClassExpression

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

There was an incosistency with access and storage of the usedPropTypes
of a component that would cause proptypes to not be correctly marked as
used if more than one prop was used in the body of an async function
class property or async class method.
Fixes #1053
---
bug source:
First time around
- get the parentComponent using utils.getParentComponent() https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/no-unused-prop-types.js#L594
- save off the usedPropTypes array from what component was found.
- modify the array with my new used props.
- set the new array on the node https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/no-unused-prop-types.js#L638
Note that in this case the node is a MemberExpression
- Components#set will then just crawl the parents …

fix no-unused-prop-types + async class properties and methods

---

docs/rules/default-props-match-prop-types.md

When adding this rule in my project, I wasn't sure if it's `react/default-props-match-prop-types` or `default-props-match-prop-types`... Use the full name should be clear.

Use full name of the rule

---

lib/rules/jsx-curly-spacing.js

See: https://github.com/yannickcr/eslint-plugin-react/issues/1290

Use full schema object instead of an array for jsx-curly-spacing

---

lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

`{...spreadProps}` was not working correctly in case there was an external url. Added test case + fix + a small code refactor.
Should fix https://github.com/yannickcr/eslint-plugin-react/issues/1296

Fix crash in jsx-no-target-blank

---

docs/rules/default-props-match-prop-types.md

As compare with other docs, it's better to add `react/` prefix

Add `react/` prefix for the title of default-props-match-prop-types.md

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

This is tackling one of the many issues with the rule (issue #1162).
The problem was that the rule simply ignored the components that had no used properties. Once this condition was removed I had to fix some tests and remove some other (that were never actually worked correctly but were passing because of the component had no used props and thus was excluded from validation).
This change might fix few more false positives that users reported. I am planning to go through the list of open issues for the rule and close/fix some more after I get some feedback on my change.

no-unused-props: not ignoring components with no used props

---

docs/rules/sort-comp.md
lib/rules/sort-comp.js
tests/lib/rules/sort-comp.js

We wanted to be able to sort our getters and setters and it was mentioned in an issue, so I implemented it. This PR allows getters and setters to be sorted by adding the keywords `getters` and/or `setters` to the `sort-comp` rule.
Fixes #100

Teach sort-comp rule about getters and setters.

---

index.js
lib/rules/no-unused-state.js
tests/lib/rules/no-unused-state.js

Link to significant commit [is here](https://github.com/wbinnssmith/eslint-plugin-react/commit/1e5b989cf7299962e62e65574241b7288120dd61)
This adds a new rule, react/no-unused-state, which discovers state fields in a React component and warns if any of them are never read. It was developed internally at Facebook by @rjbailey and has been in use throughout Facebook's JS for a couple months now. It was written against a modern version of node, so has been rebased on @ljharb's branch dropping support for node < 4.
It currently supports es2015 classes extending `React.Component`  (no support currently for `React.createClass()`) and can detect when state is as `this.state = {}`, assigning state in a property initializer, and when calling `this.setState()`.

Add no-unused-state

---

tests/lib/rules/no-unused-prop-types.js

Fixes #816

---

docs/rules/jsx-no-bind.md

#1306 - what has been seen, cannot be unseen.

Fix typo in jsx-no-bind doc

---

lib/util/Components.js
tests/lib/rules/no-unused-prop-types.js

Issue #1309

---

tests/lib/rules/no-unused-prop-types.js

`no-unused-prop-types`: add `.map` test case from #1107

---

lib/rules/jsx-no-duplicate-props.js
tests/lib/rules/jsx-no-duplicate-props.js

jsx-no-duplicate-props is causing error. 
TypeError: name.toLowerCase is not a function. 
When <Element {...props}> is used.

#969 fix: exception for jsx-no-duplicate-props

---

lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

This rule should only check strings.
Fixes #1301

Fix false positives in no-literals

---

docs/rules/no-typos.md
lib/rules/no-typos.js
tests/lib/rules/no-typos.js

`no-typos` rule currently checks for class properties (`defaultProps`, `childContextTypes` etc.) only. 
My attempt is to make sure that react lifecycle methods also do not have any casing typos.
The following patterns are considered warnings:
```js
class MyComponent extends React.Component {
componentwillMount() {}
}
class MyComponent extends React.Component {
ComponentWillReceiveProps() {}
}
class MyComponent extends React.Component {
componentdidupdate() {}
}
```
The following patterns are not considered warnings:
```js
class MyComponent extends React.Component {
componentWillMount() {}
}
class MyComponent extends React.Component {
componentWillReceiveProps() {}
}
class MyComponent extends React.Component {
componentDidUpdate() {}
}
```
I'm open to improvements to this rule. Thanks!

Add lifecycle methods check to no-typos rule

---

README.md
lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

Hi all.
I've been meaning to dabble with eslint for a while, and this was a small project I wanted to take on. We're currently using this linter on our codebase, and I thought it would be great to have a fixer for this one. 
This particular rule has so many configurations, and I didn't bother to handle all of them although it wouldn't be hard to do so. I may do that in a follow-up PR.
I tested using the following:
```
node_modules/mocha/bin/_mocha /Users/amirsharif/Projects/eslint-plugin-react/tests/lib/rules/jsx-sort-props.js
```
I also added an additional, multi-line test.

Add fixer for jsx/sort-props

---

tests/lib/rules/no-unused-prop-types.js

[no-unused-prop-types] test cases

---

docs/rules/no-array-index-key.md

https://github.com/yannickcr/eslint-plugin-react/issues/1123

Update no-array-index-key.md to address issue 1123

---

lib/rules/no-typos.js
tests/lib/rules/no-typos.js

This is a fix for: https://github.com/yannickcr/eslint-plugin-react/issues/1353
I'm not particularly happy with how I fixed this issue, but I think it should be fine for now. At least, the rule will not crash anymore.
There's more info in the ticket + there is a related ticket on the eslint repo with additional info.

Fix crash for no-typos rule

---

lib/rules/require-default-props.js
tests/lib/rules/require-default-props.js

This is to fix an edge case where linting stops when it finds a component without props.  Instead it should move on to the next component in the file.

require-default-props - fixing an edge case where linting stops early

---

lib/rules/no-typos.js
lib/util/Components.js
tests/lib/rules/no-typos.js

Second attempt at fixing https://github.com/yannickcr/eslint-plugin-react/issues/1353
I think this is a better approach, but it means that currently one case is not supported. See the added test:
```js
MyComponent.PROPTYPES = {}
/** @extends React.Component */
class MyComponent extends BaseComponent {}
```
I suppose that is acceptable for now, at least it is better than having the rule crash.
Also explained why the try/catch is needed and linked to relevant eslint-scope issue that needs to be implemented before it can be removed.

More robust no typos fix

---

lib/rules/no-unused-state.js
tests/lib/rules/no-unused-state.js

For https://github.com/yannickcr/eslint-plugin-react/issues/1361.
This sets the no-unused-state rule to ignore computed property keys when the contents aren't literal.
I think it should cover all kinds of literals for checking unused state properties because it could happen in types other than string and could be checked. If that is undesirable, I could change it to only checking string literals. 
Other than that, let me know what other improvements you have in mind.

[no-unused-state] Ignore computed property keys for no unused state rule

---

lib/rules/default-props-match-prop-types.js
lib/rules/no-unused-prop-types.js
lib/rules/prop-types.js
tests/lib/rules/default-props-match-prop-types.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

Fixes #1364. Fixes #1323.
The following snippet creates an `IntersectionTypeAnnotation` which was not handled in both rules.
```js
type Props = PropsA & PropsB;
```
I hope the tests/implementation are speaking for themselves on this one 😄 If anyone has any advice for additional test cases please let me know. I didn't test the `React.Component<Props>` syntax because I figured these shouldn't affect that implementation, but perhaps it's worth it?

Add support for Flow IntersectionTypeAnnotation to prop-types and no-unused-prop-types

---

.eslintrc

While checking the source the code, I found in the **.eslintrc** missing the doublequote in the parserOptions, made a quick fix on this PR.

Fix typo in .eslintrc

---

lib/rules/no-typos.js
lib/util/Components.js
tests/lib/rules/no-typos.js

There was another report of a crash with `no-typos` rule: https://github.com/yannickcr/eslint-plugin-react/issues/1373#issuecomment-325717418
Fixed this one 2 ways:
* Added a null check around the code that was causing this crash
* Added an extra validation on the `MemberExpression" visitor to make sure we are dealing with one of the supported properties
The second point may not be needed, but I think it's a nice addition to the rule... currently we visit **all MemberExpressions**, including those outside of React-related code. There are probably a whole bunch of these in any given code-base, and it's not needed to find the related component for that MemberExpression if we're not going to report a typo issue for the property name.

Fix crash for no-typos: Cannot read property 'name' of undefined

---

lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

Fixes another crash in the `boolean-prop-naming` rule related to old-style Flow prop types.

Fix another crash in boolean-prop-naming

---

lib/rules/no-unused-prop-types.js
lib/rules/prop-types.js
tests/lib/rules/no-unused-prop-types.js

While working on https://github.com/yannickcr/eslint-plugin-react/issues/1393 I noticed that `no-unused-prop-types` rule supports way more cases than `prop-types` rule already supports.
Since we would release Flow 0.53 support in the next release for the `prop-types` rule, I felt it wouldn't be really complete if we supported the Flow TypedArgument syntax for this rule either.
Since https://github.com/yannickcr/eslint-plugin-react/issues/1393 will take a bit more time for me to complete, I figured that an additional extra small PR to add this support to this rule would be very useful.
The code is 100% copy-paste from the `prop-types` rule. The goal for https://github.com/yannickcr/eslint-plugin-react/issues/1393 is to actually eliminate that duplication.

Add support for Flow TypedArgument in no-unsed-prop-types rule

---

lib/rules/no-unused-prop-types.js
lib/rules/prop-types.js
tests/lib/rules/no-unused-prop-types.js

Fixes https://github.com/yannickcr/eslint-plugin-react/issues/1388
Added a more generic implementation that supports all prefixes, not just `-` and `+` like it was the case in the `prop-types` rule.
Additionally, made both rules implement the same logic. Although, as described in the other PR, the logic for detecting prop-types should really be extracted out to a separate file. I'd like to tackle that separately as well though.

Support read-only props in Flow for no-unused-prop-types

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

I'm not super happy with the solution, perhaps others have a better idea?
It turns out that ESLint visits `ClassExpression` before it visits `TypeParameterDeclaration`, but I want it the other way around.
I tried using the `ClassExpression:exit` key, but it doesn't change anything.
Therefore, I needed a way to defer class expressions evaluations util after `TypeParameterDeclaration` has been visited, by storing the nodes in an array and looping through it in `Program:exit`.
This fixes https://github.com/yannickcr/eslint-plugin-react/issues/1376#issuecomment-325166909 and several other cases which we didn't catch before.
I'm not sure it will cover all of the issues related to Flow Props yet.
I'll add the same support to `no-unused-prop-types`  in …

Add support to ClassExpressions in the prop-types rule

---

lib/rules/no-direct-mutation-state.js
tests/lib/rules/no-direct-mutation-state.js

This rule should also catch increment & decrement operators.
Fixes #1386

Handle UpdateExpressions in no-direct-mutation-state

---

lib/rules/no-unused-prop-types.js
lib/rules/prop-types.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

Closes #1413
3 cases needed to be covered:
* Mutliple intersections:
```js
type PropsA = {}
type PropsB = {}
type PropsC = {}
type PropsD = PropsA & PropsB
type Props = PropsC & PropsD
```
* Importing types. This was already handled for other cases, but not for the intersection.
* `type Props = PropsA & { foo: string }`

Fix issues with IntersectionTypeAnnotation for prop-types and no-unused-prop-types

---

README.md

Fixes example missing comma

---

docs/rules/jsx-curly-brace-presence.md
lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

This is an attempt to fix https://github.com/yannickcr/eslint-plugin-react/issues/1449, so that the jsx-curly-brace-presence rule, when set to get rid of unnecessary curly braces(JSX expression), will bail out or deem a JSX expression necessary when a character that needs to be escaped in its JSX form is found in the expression. It also improves the fix in enforcing curly braces by escaping backslashes in its JSX form.
Gigantic thanks to @lydell for suggesting the implementation [plan](https://github.com/yannickcr/eslint-plugin-react/issues/1449#issuecomment-332750344) for this PR. I hope I didn't screw it up too much. 😄 
Let me know if there is any improvement you have in mind.
Fixes #1479. Fixes #1449.

[jsx-curly-brace-presence] Bail out in warning JSX expression when some chars exist

---

lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

There is an issue where using Object.spread syntax with this rule causes Eslint to break as it attempts to look for `node.value.property` in a spread object. We avoid validating spread nodes by checking for the `ExperimentalSpreadProperty` type.
Reopened #1482 (github wasn't showing new commit) @ljharb

Fix `boolean-prop-naming` with Object.spread syntax

---

README.md
docs/rules/no-unused-state.md

Added some simple docs for `no-unused-state`. I do not know if this really needs more examples than the ones I added. They're taken from the tests.

Add docs for no-unused-state

---

lib/rules/no-unused-state.js
tests/lib/rules/no-unused-state.js

For https://github.com/yannickcr/eslint-plugin-react/issues/1363, so that state property usage by object destructuring assignment in a class method defined with an arrow function gets recorded. Examples:
```js
class ArrowFunctionClassMethodTest extends React.Component {
constructor() {
this.state = { foo: 0 };
}
doSomething = () => {
const { state: { foo } } = this;
return foo;
}
render() {
return <SomeComponent />;
}
}
```
should not be warned.
Let me know if there is anything I can do to improve this PR. Also, just to confirm, this rule doesn't care about whether the class method is used or not, right?

[no-unused-state] Add ability to handle arrow function class method

---

lib/rules/jsx-closing-bracket-location.js
lib/rules/jsx-closing-tag-location.js
lib/rules/jsx-equals-spacing.js
lib/rules/jsx-first-prop-new-line.js
lib/rules/jsx-indent-props.js
lib/rules/jsx-indent.js
lib/rules/jsx-max-props-per-line.js
lib/rules/jsx-sort-props.js
lib/rules/self-closing-comp.js

Usage of non-standard `.start`/`.end` properties causes failures when they aren't set by some parsers that follow the official AST (e.g. [typescript-eslint-parser](https://github.com/eslint/typescript-eslint-parser)).
See: https://github.com/eslint/eslint/issues/8956

Replace node.start/node.end with node.range[0]/node.range[1], respectively

---

README.md
docs/rules/destructuring-assignment.md
index.js
lib/rules/destructuring-assignment.js
tests/lib/rules/destructuring-assignment.js

to enforce consistent usage of destructuring assignment closes #216, closes #556, closes #278

[destructuring-assignment] : new rule

---

tests/lib/rules/jsx-indent.js

I think an update to acorn picked up through eslint->espree caused this test to fail very recently.

Remove `super` being used as variable in a test

---

docs/rules/sort-prop-types.md
lib/rules/sort-prop-types.js
tests/lib/rules/sort-prop-types.js

This allows the rule to enforce the sorting rules in a shape prop object.
I think it makes more sense to happen by default, but I expect it would be better to wait until the next major version for that. This PR should allow the rule to satisfy the request in #1476.

Add `sortShapeProp` option to sort-prop-types rule

---

docs/rules/jsx-wrap-multilines.md
lib/rules/jsx-wrap-multilines.js
tests/lib/rules/jsx-wrap-multilines.js

Add ConditionalExpression, LogicalExpression and JSXAttribute

[jsx-wrap-multilines] Add new nodes for wrap

---

docs/rules/jsx-no-bind.md
lib/rules/jsx-no-bind.js
tests/lib/rules/jsx-no-bind.js

This will fix #1444, #1395 and #1417, so that the rule will only warn if there are violations in JSX attributes and will keep track of `const` variable declarations of violations. 
For examples,
```jsx
renderButton(someParams){
const clickHandler = this.handleClick.bind(this, someParams);
return(
<ButtonComponent
onClick={clickHandler}
>
Submit
</ButtonComponent>  
)
} 
```
will warn.
But
```jsx
render() {
return (
<div>
{this.props.list.map(this.wrap.bind(this, 'span'))}
</div>
);
}
```
will not.
The new implementation is simply keeping track of each `const` variable declaration that references a violation in each block statement and reports them if they got passed into JSX props.
With the update, this rule does not account for any assignment expression and variable declarations that are …

[jsx-no-bind] Only warn for props and account for variable declaration

---

docs/rules/jsx-wrap-multilines.md
lib/rules/jsx-wrap-multilines.js
tests/lib/rules/jsx-wrap-multilines.js

This changes the options from a boolean to an enum with three possible
values: `ignore`, `parens`, and `parens-new-line`. Using `ignore` is like
the previous `false` while `parens` is like the previous `true`. The new
option (`parens-new-line`) will check that the parentheses around the
multiline JSX are on separate lines for better readability.
This PR attempts to address #1469.

Check parentheses with new lines for multiline JSX

---

README.md
docs/rules/no-access-state-in-setstate.md
index.js
lib/rules/no-access-state-in-setstate.js
tests/lib/rules/no-access-state-in-setstate.js

This rule prevents the use of `this.state` within `this.setState`. It is further described in `docs/rules/no-access-state-in-setstate.md` in the PR, but to summarize: `this.setState` is async, and referring to `this.state` within it may lead to race conditions. 
This is my first eslint-plugin PR, so I am really happy to get any kind of feedback.
edit: 
This is also the recommended way doing it in the [react docs](https://facebook.github.io/react/docs/react-component.html#setstate): 
> If the next state depends on the previous state, we recommend using the updater function form, instead
> ```
> this.setState((prevState) => {
>  return {counter: prevState.quantity + 1};
>}); 
> ```

Rule proposal: no-access-state-in-setstate

---

.eslintignore

since it was ignored by default.

chore: rm node_modules from eslintignore.

---

lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

If reservedFirst is enabled and noSortAlphabetically is off, then alphabetical order is only enforced in the reserved props but not in the other props. This PR fixes this.
If existing behavior is the desired, please ignore this PR.
Fixes #1320

fix(jsx-sort-props): enforce prop sort when reservedFirst is enabled

---

docs/rules/prefer-stateless-function.md
lib/rules/prefer-stateless-function.js
tests/lib/rules/prefer-stateless-function.js

Previously, a class component that could be converted to a stateless
functional component would not be reported as such if the component had
`defaultProps` defined as a class property.
Closes #1521

Account for defaultProps in prefer-stateless rule

---

lib/rules/jsx-no-comment-textnodes.js
tests/lib/rules/jsx-no-comment-textnodes.js

The rule was reporting usage of two slashes via html entities at the
beginning of a literal between JSX elements. Since that is not a valid
comment, there should be no error reported by this rule.
Closes #1517

Fix bad report by jsx-no-comment-textnodes

---

lib/rules/default-props-match-prop-types.js
tests/lib/rules/default-props-match-prop-types.js

The rule would crash when checking an intersection with a
GenericTypeAnnotation that was not defined in the scope of the file.
Closes #1499

Fix crash in default-props-match-prop-types

---

lib/rules/boolean-prop-naming.js
lib/rules/default-props-match-prop-types.js
lib/rules/display-name.js
lib/rules/forbid-prop-types.js
lib/rules/no-redundant-should-component-update.js
lib/rules/no-unused-prop-types.js
lib/rules/prefer-stateless-function.js
lib/rules/prop-types.js
lib/rules/require-default-props.js
lib/rules/require-render-return.js
lib/rules/sort-comp.js
lib/rules/sort-prop-types.js
lib/util/ast.js
lib/util/props.js

In the previous times I have made changes, I have noticed some duplication in code and wanted to deduplicate it. I have started that in this PR, and I wanted to open it up for some feedback. Is this desired? Should I go further?

Code clean up

---

docs/rules/no-deprecated.md
lib/rules/no-deprecated.js
tests/lib/rules/no-deprecated.js

React.DOM factories were deprecated in 15.6.0 -> https://github.com/facebook/react/pull/8356

Deprecation check for React.DOM factories 

---

docs/rules/forbid-prop-types.md
lib/rules/forbid-prop-types.js
lib/util/Components.js
lib/util/ast.js
lib/util/props.js
tests/lib/rules/forbid-prop-types.js

This PR adds support for checking `contextTypes` and `childContextTypes` for forbidden prop types. I also added support for checking getters, too, since I have seen them supported elsewhere.
Closes #1513

forbid-prop-types: forbid contextTypes, childContextTypes

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

Handle when props are used in the setState update callback
Fix #1506

Fix no-unused-prop-types setState updater 

---

lib/util/Components.js

While working on https://github.com/yannickcr/eslint-plugin-react/issues/1393 and figuring out how to share code related to prop-types detection based on how `Components` works, I noticed this class is still using the old ES5 syntax for defining classes.
It seems node 4 supports class syntax, and I think it simplifies things slightly. I also changed the exports of the file to be a single object with a `detect()` function, rather than exporting the whole `Components` class that also had `detect` defined on it.
This is purely refactoring of the structure of the file, I didn't change any logic or comments (though some could probably use an update, e.g. `list()` does more than just returning a `list()` and it's not obvious from the code what exactly is going on).

Refactor Components into ES6 class syntax

---

docs/rules/require-default-props.md
lib/rules/require-default-props.js
tests/lib/rules/require-default-props.js

New option for require-default-props rule that forbids defining default
props for props that are required.
This doesn't handle spread properties since the work needed should also work for the default state of the rule. If that were to happen, it could cause reports for previously valid code, and that seems more suitable for a major version bump. Therefore, I think that should be in a separate PR.
Closes #1524

Add forbidDefaultForRequired option

---

lib/rules/jsx-closing-tag-location.js
lib/rules/jsx-indent-props.js
lib/rules/jsx-indent.js
lib/util/ast.js
tests/lib/rules/jsx-indent.js

Fixed this bug in the jsx-indent rule: Fixes #1246
Along the way, discovered that a very similar function was defined 3 different times with 3 different implementations in 3 different rules. Using a more advanced version of this function fixed the bug, and then decided to use the same function in all three rules thanks to the new `astUtil` helper file that we have.

Fix alignment bug in jsx-indent (and extract duplicate code)

---

lib/rules/jsx-no-bind.js
tests/lib/rules/jsx-no-bind.js

The rule would assume a variable is initialized when checking a
VariableDeclarator node.
Fixes #1543

Prevent jsx-no-bind crash

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

When checking props in setState updater functions, some assumptions were
being made about the props argument being defined.
Fixes #1542

Fix crash in no-unused-prop-types

---

README.md

Added the link. Partially resolves: https://github.com/yannickcr/eslint-plugin-react/issues/1546
I was now wondering though, should this rule not have the `jsx-` prefix? As it's dealing with JSX specific linting only.
Unfortunately that would be a breaking change, since it is already released without this prefix right now.

Add link to "button-has-type" rule docs in the main README

---

README.md
docs/rules/jsx-one-expression-per-line.md
lib/rules/jsx-one-expression-per-line.js
tests/lib/rules/jsx-one-expression-per-line.js

[Docs] jsx-one-expression-per-line

---

lib/rules/no-access-state-in-setstate.js
tests/lib/rules/no-access-state-in-setstate.js

With an IIFE in the return statement of render that uses `this.state`,
there is no parent with a name. In this rule, the method names are later
checked to see if they are being called elsewhere in the file. Since
there is no intention of this being called anywhere else, the IIFE will
just be skipped being added to the list of methods.
Fixes #1559

Fix crash in no-access-state-in-setstate

---

lib/rules/no-unused-prop-types.js
lib/rules/prop-types.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

This will fix the crash when using Union flowtypes for the following rules:
- `prop-types`
- `no-unused-prop-types`
The library already escapes early when facing a `typeNode` it doesn't recognize; this will escape early when we can't even figure out the `typeNode` because `UnionTypeAnnotation`s don't have an `annotation.id`.
This will not actually resolve the issue of using unions; it will simply prevent eslint from crashing.
Fixes issue https://github.com/yannickcr/eslint-plugin-react/issues/1468

Fix crash when using Unions in flow propTypes

---

lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-curly-spacing.js

The first bug is that comments in children get deleted when the rule auto fixes
```
<a>
{ /*test*/ }
</a>
```
==>
```
<a>
{}
</a>
```
The second bug is that if the penultimate token spans multiple lines, like it is for example a template literal, then it reports an error when none should.
```
<pre>
{`
text
`}
</pre>
```
rule options and more info is in the test cases

Fix two bugs with jsx-curly-spacing

---

tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

Please note this only tests that using `import` and `Union` propTypes won't crash eslint. This does _not_ actually test that the propTypes are not unused or that they are defined when used.
Contributes to issue https://github.com/yannickcr/eslint-plugin-react/issues/1468

Add flow `Union` tests for `no-unused-prop-types` and `prop-types` with `import`

---

README.md
docs/rules/forbid-component-props.md
docs/rules/forbid-dom-props.md
index.js
lib/rules/forbid-dom-props.js
tests/lib/rules/forbid-dom-props.js

A new rule forbid-dom-props was added. It is based on
forbid-component-props but it only forbid property on DOM Node
elements.
This can be useful to enforce some good practices, as not using 'id'
attributes or inline styles.

Add a forbid-dom-props rule

---

lib/rules/jsx-wrap-multilines.js
tests/lib/rules/jsx-wrap-multilines.js

This change removes the newline that comes before opening parentheses, if `"parens-new-line"` is specified as an option and the multiline JSX starts on a new line.
i.e. when `"parens-new-line"` is specified,  instead of fixing these cases: 
```jsx
<div prop={
<div>
<p>Hello</p>
</div>
}>
<p>Hello</p>
</div>
// &
<div>
{foo &&
<div>
<p>Hello World</p>
</div>
}
</div>
```
like this: 
```jsx
<div prop={
(
<div>
<p>Hello</p>
</div>
)
}>
// &
<div>
{foo &&
(
<div>
<p>Hello World</p>
</div>
)
}
</div>
```
this change will inline the opening parentheses: 
```jsx
<div prop={(
<div>
<p>Hello</p>
</div>
)}>
// &
<div>
{foo && (
<div>
<p>Hello World</p>
</div>
)}
</div>
```
~I did not change the position of closing parens in this PR, I'm not sure if there is another rule that might cover that? if …

Potential autofix improvement for jsx-wrap-mulitlines

---

README.md
docs/rules/no-this-in-sfc.md
index.js
lib/rules/no-this-in-sfc.js
lib/util/Components.js
tests/lib/rules/no-this-in-sfc.js

This rule will report errors when a stateless functional component is
attempting to use `this`.
This attempts to address the request in #1435.

Add new rule for preventing `this` in SFCs

---

lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

This adds support for checking prop types  in `boolean-prop-naming` when using the `propWrapperFunctions` setting.
Closes #1452.

Support propWrapperFunctions for boolean-prop-naming

---

docs/rules/boolean-prop-naming.md
lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

The default message for boolean-prop-naming does not make it clear why the rule is being flagged. I'd like my organization to be able to immediately know what the issue is without them having to parse the Regex.
This PR introduces functionality such that the following configuration:
```js
{
'react/boolean-prop-naming': [
'error',
{
rule: '^(is|has)[A-Z]([A-Za-z0-9]?)+',
message: 'Boolean prop names must begin with either \'is\' or \'has\'.'
}
]
}
```
displays the custom message of `Boolean prop names must begin with either 'is' or 'has'.`.

Allow for Boolean Prop Naming Custom Message

---

lib/rules/no-access-state-in-setstate.js
tests/lib/rules/no-access-state-in-setstate.js

This fixes #1597.
This also fixes another bug I found where the following were reported as an error (added a new test case for this): 
```js
var nextValueNotUsed = this.state.value + 1;
var nextValue = 2;
this.setState({value: nextValue});
```

Find edge case in no-access-state-in-setstate (#1597)

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

Summary
----------
There seems to still be an unresolved regression introduced in 7.5.0 from https://github.com/yannickcr/eslint-plugin-react/pull/1507 
(see https://github.com/yannickcr/eslint-plugin-react/issues/1581#issuecomment-351220583)
When passing an empty function as a PropType - it causes the `no-unused-prop-types` to crash eslint with the following error:
```js
Cannot read property 'properties' of undefined
TypeError: Cannot read property 'properties' of undefined
```
When this part of `no-unused-prop-types` is run:
https://github.com/yannickcr/eslint-plugin-react/blob/f6e4c891a474aaff8f69088b174de8c1317f8fa8/lib/rules/no-unused-prop-types.js#L652-L660
it breaks because `node.params` is an empty array. In my testing, it looks like #1507 introduced this breakage (the test I've …

Add empty params check for unused prop types rule to fix empty proptype functions from causing crashes

---

lib/rules/no-access-state-in-setstate.js
tests/lib/rules/no-access-state-in-setstate.js

Avoids this error which appears in `master` in the `no-access-state-in-setstate` rule
```
TypeError: Cannot read property 'type' of undefined
at ObjectPattern (/Users/patrick/dev/sigopt-api/node_modules/eslint-plugin-react/lib/rules/no-access-state-in-setstate.js:158:52)
at listeners.(anonymous function).forEach.listener (/Users/patrick/dev/sigopt-api/node_modules/eslint/lib/util/safe-emitter.js:47:58)
at Array.forEach (<anonymous>)
at Object.emit (/Users/patrick/dev/sigopt-api/node_modules/eslint/lib/util/safe-emitter.js:47:38)
at NodeEventGenerator.applySelector (/Users/patrick/dev/sigopt-api/node_modules/eslint/lib/util/node-event-generator.js:251:26)
at NodeEventGenerator.applySelectors (/Users/patrick/dev/sigopt-api/node_modules/eslint/lib/util/node-event-generator.js:280:22)
at …
```

Handle nodes without init

---

lib/rules/require-optimization.js
tests/lib/rules/require-optimization.js

Hello, thanks for the great ESLint rule.
This is an error report.
When the rule `require-optimization` encounters arrays with empty items as values in object (ex. `{ 
const obj = { prop: [,,,,,] } }`),  an error rises.
This PR provides null avoidance, simply.

Add null avoidance in rule `require-optimization`

---

lib/rules/no-typos.js
tests/lib/rules/no-typos.js

#1471 checking to see if node is truthy to prevent TypeError on undefined node.

Fix TypeError for undefined node in PropType.shape

---

docs/rules/jsx-tag-spacing.md
lib/rules/jsx-tag-spacing.js
tests/lib/rules/jsx-tag-spacing.js

- Add `beforeClosing` option to `jsx-spacing-rule` which enforces spacing before closing JSX tags
- Fixes issue #1396
- Updated docs
- Add unit tests

Add beforeClosing option to jsx-tag-spacing rule

---

lib/rules/no-deprecated.js
tests/lib/rules/no-deprecated.js

This pull request fixes #1644.

Adding a warning for React.addons.TestUtils.

---

lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

Find string literals as a part of BinaryExpressions in jsx-no-literals

---

README.md
docs/rules/jsx-sort-default-props.md
index.js
lib/rules/jsx-sort-default-props.js
tests/lib/rules/jsx-sort-default-props.js

Related to https://github.com/yannickcr/eslint-plugin-react/issues/281
```js
var First = createReactClass({
getDefaultProps: function() {
return {
barRequired: "barRequired",
onBar: "onBar"
};
}
});
```

Add jsx-sort-default-props rule

---

lib/rules/jsx-tag-spacing.js

add missing meta to jsx-tag-spacing

---

lib/rules/no-typos.js
tests/lib/rules/no-typos.js

fixes: #1607 and helps in #1389.
if will add support for the following cases:
```js
{
a: string.isRequired,
b: customProp.isRequired,
// added support for isRequired in call expressions. No validation is done inside
c: PropTypes.shape({
d: string
}).isRequired
e: customShape({
f: number
}).isRequired
}
```
for a custom prop type like `string.isrequired` the error message will be: `Typo in declared prop type: isrequired` because currently it doesn't know that it's a prop type cualifier
for call expressions like `customShape({}).isrequired` the error message will be `Typo in prop type chain qualifier: isrequired` and it will work as long as it's not something like `customShape().number.isRequired`

support for custom propTypes with isRequired in no-typos

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

prop-types doesn't check nextProps of componentWillReceiveProps

---

lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

[Fix] crossOrigin is wrong; and crossorigin is only valid on script/img/video

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Originally written by @phpnode as part of #1138
That PR was closed in favor of #1377, which does not appear to include a solution for the recursive type definition issue.
This allows for code like
```js
type Note = {text: string, children?: Note[]}
type Props = {
notes: Note[]
};
```
to run without triggering an infinite loop.

Support recursive type annotations, fixes #913

---

lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

Fixed crossorigin naming convention to match React's supported HTML attributes.
https://reactjs.org/docs/dom-elements.html
Fixes #1656. Per https://github.com/yannickcr/eslint-plugin-react/issues/1642#issuecomment-360881470

Fixed crossorigin naming convention and missing tag support.

---

lib/rules/forbid-foreign-prop-types.js
tests/lib/rules/forbid-foreign-prop-types.js

Add an option to allow using another components propTypes inside a propTypes declaration.
Closes #1647

Add allowInPropTypes option to forbid-foreign-prop-types (#1647)

---

lib/rules/sort-prop-types.js
tests/lib/rules/sort-prop-types.js

Resolves issue https://github.com/yannickcr/eslint-plugin-react/issues/1668

fix(sort-prop-types): Fix sortShapeProp when shape is not an object literal

---

lib/rules/jsx-child-element-spacing.js
tests/lib/rules/jsx-child-element-spacing.js

Fix error location

---

docs/rules/jsx-child-element-spacing.md

Fixed a typo in the documentation which referenced `(react/jsx-curly-spacing)` instead of `(react/jsx-child-element-spacing)`.

Fix an issue with the documentation for 'jsx-child-element-spacing'

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

We got `PropType is defined but prop is never used  react/no-unused-prop-types` when used **createReactClass**.
Added fix, tests and removed 2 duplicated tests.

Fixed "PropType is defined but prop is never used  react/no-unused-prop-types"

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Resolves #1684 
I've added the `shouldComponentUpdate` to the list of functions to include with this rule, following how `componentWillReceiveProps` was implemented.
The only thing outstanding are the tests, I've only included a single test but it may need to be put in a different spot.

Rule prop-types includes nextProps checking in shouldComponentUpdate

---

lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-curly-spacing.js

See also:
https://github.com/yannickcr/eslint-plugin-react/issues/648#issuecomment-327519650

Added tests for jsx-curly-spacing that deal with comments in children.

---

docs/rules/jsx-max-depth.md
index.js
lib/rules/jsx-max-depth.js
tests/lib/rules/jsx-max-depth.js

[New] `jsx-max-depth`: validate a specific depth for JSX

---

lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

As audio elements also inherit from HTMLMediaElement and thus have the `crossOrigin` property
Also see:
Audio element: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio
HTMLAudioElement: https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement
HTMLMediaElement crossOrigin: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/crossOrigin

Allow crossOrigin on audio elements

---

lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

There was a bug in boolean-prop-naming where the following would trip the rule:
```js
class Something extends React.Component {
static propTypes = {
something: PropTypes.bool
};
// ...
}
```
but the following would not:
```js
class Something extends React.Component {
static propTypes = {
something: PropTypes.bool.isRequired
};
// ...
}
```
I added an extra conditional to `getPropKey` to handle this scenario.

Handle isRequired for boolean-prop-naming

---

lib/rules/no-unused-prop-types.js
tests/lib/rules/no-unused-prop-types.js

The upcoming React 16.3 release will make a couple of changes to the class component lifecycles: `componentWillMount`, `componentWillReceiveProps`, and `componentWillUpdate` are being aliased to `UNSAFE_componentWillMount`, `UNSAFE_componentWillReceiveProps`, and `UNSAFE_componentWillUpdate` and a new static lifecycle, `getDerivedStateFromProps`, is being added.
For background information, see [RFC 6](https://github.com/reactjs/rfcs/blob/master/text/0006-static-lifecycle-methods.md).
When running codemods at Facebook to rename these lifecycles, I noticed that it caused a couple of false positives with the `react/no-unused-prop-types` lint rule since that rule was not yet aware of the lifecycle changes. I _think_ this PR corrects that. I added a couple of sanity check tests (which failed …

Update no-unused-prop-types rule for new React class component lifecycles

---

docs/rules/jsx-no-bind.md

https://reactjs.org/blog/2015/01/27/react-v0.13.0-beta-1.html#autobinding

[Fix] `react/jsx-no-bind` Add props to example

---

docs/rules/jsx-curly-brace-presence.md
lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

allows whitespace in JSX container in `react/jsx-curly-brace-presence` regardless of options. 
Potential fix for #1717  
cc. @pbondoer @ljharb

[fix] Allow whitespace jsx container in jsx-curly-brace-presence (fixes: #1717)

---

lib/rules/no-typos.js
tests/lib/rules/no-typos.js

This is simply a rebase of @jseminck's branch, plus the removal of the
lingering failing test.
I removed the failing test because I believe it's a very small corner case
that should not block the resolution of this issue, which seems to affect
a lot of people and limits our ability to keep our components' proptypes DRY.
If it's determined that this corner case *should* be handled, I suggest creating
a new issue to track just that case.
Closes #1389.

Allow custom PropType classes with no-typos rule

---

lib/rules/jsx-no-bind.js
tests/lib/rules/jsx-no-bind.js

handle ternary operation for jsx-no-bind

---

lib/rules/require-default-props.js
tests/lib/rules/require-default-props.js

Hi it's my first PR to this repo so if something is wrong please comment me.

Issue #1724 support for Flow generic PropTypes declaration in require-default-props rule

---

docs/rules/forbid-component-props.md
lib/rules/forbid-component-props.js
tests/lib/rules/forbid-component-props.js

Docs are still missing ;)
fixes #1732

forbid-component-props: add component whitelist

---

docs/rules/jsx-key.md

Spreaded key is discouraged and currently triggering the rule. Added some clarification to the doc.
Resolves yannickcr/eslint-plugin-react#1753.

Added key object spread example

---

README.md
docs/rules/no-deprecated.md
lib/rules/no-deprecated.js
tests/lib/rules/no-deprecated.js

Added warnings for deprecated lifecycle methods:
* componentWillMount,
* componentWillReceiveProps,
* componentWillUpdate.
See details [React 16.3.0](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#component-lifecycle-changes).

Adjusted no-deprecated rule for React 16.3.0

---

docs/rules/sort-comp.md
lib/rules/sort-comp.js
tests/lib/rules/sort-comp.js

Relevant issue: #1767 
The new lifecycle methods added in React 16.3 need to be added to the `sort-comp` rule for compatibility.
Also the rule needs to be updated to allow static method positions to be overridden so that `getDerivedStateFromProps` can be placed in the ordering that exists in [React documentation](https://reactjs.org/docs/react-component.html#static-getderivedstatefromprops), which appears to be how the other methods are currently ordered by default (aside from the render method).
Would love to hear any feedback/suggested changes.
I detailed potential issues etc. in my commit notes here:
- Add React 16.3 lifecycle methods to default config
- Allow static method position to be overriden by specification
- Note: this update means that a static method of the same name as a …

Add support for React 16.3 lifecycle methods in sort-comp

---

lib/rules/no-typos.js
tests/lib/rules/no-typos.js

There was a file in an old code base that improperly imported react anonymously...and had been unnoticed until we added this no-typos rule and eslint crashed. :)

guard against accidental anonymous react imports

---

lib/rules/sort-comp.js
tests/lib/rules/sort-comp.js

Fixes bug: https://github.com/yannickcr/eslint-plugin-react/issues/1793
Example of **incorrect** code with `"react/sort-comp": "error"`:
```jsx
class Test extends React.Component {
static getDerivedStateFromProps() {
return null
}
constructor(props) {
super(props)
this.state = { test: 'test' }
}
render() {
return this.state.test
}
}
```
Example of **correct** code with `"react/sort-comp": "error"`:
```jsx
class Test extends React.Component {
constructor(props) {
super(props)
this.state = { test: 'test' }
}
static getDerivedStateFromProps() {
return null
}
render() {
return this.state.test
}
}
```

sort-comp: enforcing static lifecycle methods order

---

docs/rules/jsx-no-target-blank.md
lib/rules/jsx-no-target-blank.js
tests/lib/rules/jsx-no-target-blank.js

Made from the suggestion in @ksdmitrieva's [issue](https://github.com/yannickcr/eslint-plugin-react/issues/1737), I believe this is the right approach even though you would get false positives since it cannot check for relative paths in dynamic links. However, I think that would be rare since it's not best practice to use `target='_blank'` on internal links anyway.

Target blank dynamic link should fail

---

README.md
docs/rules/jsx-props-no-multi-spaces.md
index.js
lib/rules/jsx-props-no-multi-spaces.js
tests/lib/rules/jsx-props-no-multi-spaces.js

This rule enforced consistent spacing of JSX tag attributes and is especially useful together with `jsx-indent-props` in "first" mode (#1729) to actually require consistency of where the first attribute begins.

Add jsx-props-no-multi-spaces rule

---

docs/rules/jsx-indent-props.md
lib/rules/jsx-indent-props.js
tests/lib/rules/jsx-indent-props.js

This adds support for the JSX prop style suggested in #398 which is the default of the various JetBrains IDEs.
I haven't updated the docs yet since writing docs isn't fun so I'd rather know first that the PR has a chance of getting accepted before doing that.
Fixes #398.

Add JSX prop alignment based on the first prop & between-prop space consistency

---

lib/rules/destructuring-assignment.js
tests/lib/rules/destructuring-assignment.js

Resolves #1728
Not sure if this needs to also check that assignment is in the constructor? Also, would the following do anything useful / should this be allowed?
```js
constructor(props, context) {
this.context.foo = 'blah';
}
```

Allow LHS in destructuring-assignment

---

README.md
docs/rules/no-unsafe.md
index.js
lib/rules/no-unsafe.js
tests/lib/rules/no-unsafe.js

Added  `no-unsafe` rule to address the corresponding issue #1830. See discussion details https://github.com/yannickcr/eslint-plugin-react/pull/1750#discussion_r194915657.

Added `no-unsafe` rule

---

.travis.yml
appveyor.yml
package.json

Looks like it just works.
The peer dep change sees to it that this plugin can be used in projects that use eslint 5 and npm 2 (the default in node 4) without `npm install` failing.

Add support for eslint 5

---

lib/rules/no-will-update-set-state.js
lib/util/makeNoMethodSetStateRule.js
tests/lib/rules/no-will-update-set-state.js

Account for UNSAFE_ method in no-will-update-set-state

---

lib/rules/jsx-space-before-closing.js
lib/util/log.js
lib/util/version.js

Resolves #1789
This message will appear when running some of the tests. Not sure if that should be avoided.

Output a warning if React version is missing in settings

---

lib/rules/no-deprecated.js
lib/util/ast.js
tests/lib/rules/no-deprecated.js

When the `no-deprecated` rule finds a deprecated lifecycle method, it reports the whole class declaration as the AST node for the error. Doesn't look good in editor: makes the whole class declaration red and obscures all other ESLint errors inside the class.
This patch changes the reported AST node to the method name identifier. The errors are much better targeted at the infringing code and look much better when shown in editor UI.
Added also test coverage to check for the reported AST node type.

For deprecated lifecycle methods, report identifier AST node instead of the class node

---

docs/rules/jsx-no-bind.md
lib/rules/jsx-no-bind.js
lib/rules/jsx-no-undef.js
lib/rules/jsx-pascal-case.js
lib/rules/jsx-sort-props.js
lib/rules/no-danger.js
lib/rules/self-closing-comp.js
lib/util/jsx.js
tests/lib/rules/jsx-no-bind.js

Add ignoreDOMComponents option to jsx-no-bind

---

lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

The attribute `charset` was considered an error in favor of `charSet`, but both of them result in valid HTML because HTML is case-insensitive. In other words, these two lines will be interpreted in the same way:
```jsx
<meta charSet="utf-8" />
<meta charset="utf-8" />
```
They will render different HTML (exactly like this JSX suggests), but browsers won't care. If nothing else, `charset` should be the more "correct" form of this attribute because it doesn't suggest a dash (`fillOpacity` = `fill-opacity`, `charSet` ≠ `char-set`).
https://github.com/facebook/react/issues/11492#issuecomment-342953964

Make attribute "charset" valid

---

lib/rules/prop-types.js
tests/lib/rules/prop-types.js

Similar to other fix for flow intersection (#1806). I am not sure if this is the correct fix but the change stops Eslint crashing.
Fixes #1770
Fixes #1631

Stop crashing on undefined or null properties in flow intersection

---

lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

Hello,
this PR should (hopefully) fix #1692 .
Previously if `reservedFirst` was enabled, it would customly check for the sorting of the props, if the currently viewed items were of the same type (either both reserved or both unreserved) and if not otherwise set up (i.e. `noSortAlphabetically` was enabled).
This PR now adds test cases for the viewed case: `reservedFirst` and `shorthandLast` (I didn't add any more test cases, but can do so, if requested). Also it removes the special handling of the sorting but delegates to the rest of the handler to take care of any other options (e.g. `shorthandLast`, `shorthandFirst`, `callbackLast`, etc.). (Also there was a missing parameter in the shadowed alphabetically-sorting check, which I added).
Yeah. If you need/require anything else from this …

Fix `reservedFirst` for `jsx-sort-props` rule

---

lib/rules/sort-comp.js
package.json
tests/lib/rules/sort-comp.js

Fixes #1821. Fixes #1838. Fixes #1808. Also fixes a no-issue bug (see bottom in **bold**).
The history of the rule implies that it was intended that methods matching multiple groups should be able to be placed in any of those groups.  See [initial commit](https://github.com/yannickcr/eslint-plugin-react/commit/8b93659ded2ec0fc2278d68b700338625bbcfda7#diff-ced56472004c220d7b811bb48e0bacccR146) of the rule.
It seems over time that restrictions have come into the code that prevent this.   I didn't find any discussions about this change in behavior.  This change has lead to multiple bugs because the config isn't refined enough to accommodate individual preferences. 
This PR solves those bugs by reintroducing the ability for methods to be grouped with any matching group.
For example:
Static …

sort-comp Allow methods to belong to any matching group.

---

docs/rules/sort-prop-types.md
lib/rules/sort-prop-types.js
tests/lib/rules/sort-prop-types.js

This adds adds a fixer for the `react/sort-prop-types` rule. 
It fixes ordering issues including the `sortShapeProp` and the `ignoreCase` option.
~~It doesn't work yet for `callbacksLast` or `requiredFirst`, but that could be added later. (Right now those errors would just be ignored)~~

Add fixer for sort-prop-types

---

lib/rules/jsx-props-no-multi-spaces.js
tests/lib/rules/jsx-props-no-multi-spaces.js

Handle member expressions in jsx-props-no-multi-spaces

---

lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

[Fix] Handle inline Flow type in boolean-prop-naming

---

lib/util/Components.js
tests/lib/rules/destructuring-assignment.js

Make Components.get ignore components with confidence = 0

---

docs/rules/destructuring-assignment.md
lib/rules/destructuring-assignment.js
tests/lib/rules/destructuring-assignment.js

Fixes #1875
Please let me know if you would like me to add more tests or if anything can be improved

Ignore class properties in destructuring-assignment

---

lib/rules/no-unused-prop-types.js
lib/rules/prop-types.js
lib/util/Components.js
lib/util/propTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

~~This still fails a bunch of tests, but wanted to put it up for preliminary high-level review early.~~
~~The reason tests are failing is because I extracted similar code from `prop-types` and `no-unused-prop-types` but those two have diverged and I need to reconcile two implementations into a single helper.~~
Next steps:

Extract propTypes detection code

---

docs/rules/jsx-one-expression-per-line.md
lib/rules/jsx-one-expression-per-line.js
tests/lib/rules/jsx-one-expression-per-line.js

[New] Add allow option to jsx-one-expression-per-line

---

docs/rules/sort-prop-types.md
lib/rules/sort-prop-types.js
tests/lib/rules/sort-prop-types.js

Same as https://github.com/yannickcr/eslint-plugin-react/pull/979

 Rule sort-prop-types add noSortAlphabetically

---

lib/util/propTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

[Fix] stop crashing when assigning to propTypes

---

lib/rules/no-unused-prop-types.js
lib/rules/prop-types.js
lib/util/propTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

So I was adding test cases to both rules to bring them to parity after the refactoring, but a couple of things didn't make sense.
In particular, having just one flag for ignoring props validation doesn't seem to be enough (and that was the case before the refactoring as well). For instance, let's say we encounter a spread in props e.g.
```js
type Props = {
...data,
lastname: string
};
```
That means any `this.props.foo` usage is considered to have a corresponding propType and it's ignored in `prop-types` via `ignorePropsValidation` flag we set in the helper.
However, this shouldn't preclude us from being able to detect whether `lastname` is an unused propType in `no-unused-prop-types` (this would be ignored if we met a `{...props}` spread). But we can't rely on the same flag, because that …

Additional cases for prop-types and no-unused-prop-types

---

lib/rules/jsx-child-element-spacing.js
lib/rules/jsx-closing-tag-location.js
lib/rules/jsx-curly-brace-presence.js
lib/rules/jsx-curly-spacing.js
lib/rules/jsx-filename-extension.js
lib/rules/jsx-indent.js
lib/rules/jsx-max-depth.js
lib/rules/jsx-one-expression-per-line.js
lib/rules/jsx-uses-react.js
lib/rules/jsx-wrap-multilines.js
lib/rules/no-unescaped-entities.js
lib/util/Components.js
lib/util/jsx.js
tests/lib/rules/jsx-child-element-spacing.js
tests/lib/rules/jsx-closing-tag-location.js
tests/lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-spacing.js
tests/lib/rules/jsx-filename-extension.js
tests/lib/rules/jsx-indent.js
tests/lib/rules/jsx-max-depth.js
tests/lib/rules/jsx-no-comment-textnodes.js
tests/lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-one-expression-per-line.js
tests/lib/rules/jsx-uses-react.js
tests/lib/rules/jsx-wrap-multilines.js
tests/lib/rules/no-unescaped-entities.js
tests/lib/rules/prop-types.js

[New] Support shorthand fragment syntax

---

lib/rules/no-this-in-sfc.js
lib/util/Components.js
tests/lib/rules/no-this-in-sfc.js

Fixed #1967. Adjusted component detection in `getParentStatelessComponent` for arrow functions inside a class field, e.g.:
```js
class Foo {
bar() { 
() => {
this.something();
return null;
};
}
}
```
See details in #1972.

Fix `no-this-in-sfc` rule behavior for arrow functions inside a class field

---

lib/util/Components.js
lib/util/ast.js
tests/lib/rules/no-this-in-sfc.js

The PR fixes #1960 - `no-this-in-sfc` rule for class properties.
Class properties example:
```js
class Foo {
bar = () => {
this.something();
return null;
};
}
```
The corresponding AST: [link](https://astexplorer.net/#/gist/01be31cd9af1884c028099be843c3bab/ade0ae41ec5b2a03737618519741454bdaa0dc33).

Fix `no-this-in-sfc` for class properties

---

lib/rules/no-unused-state.js
tests/lib/rules/no-unused-state.js

Don't depend on state parameter name in no-unused-state

---

lib/rules/default-props-match-prop-types.js
lib/rules/no-unused-prop-types.js
lib/rules/require-default-props.js
lib/util/propTypes.js
lib/util/usedPropTypes.js
tests/lib/rules/default-props-match-prop-types.js
tests/lib/rules/require-default-props.js

Last one - this adds `isRequired` detection to `propTypes.js` helper and finalizes deduplication of `require-default-props` and `default-props-match-prop-types`. Resolves #1908, resolves #1865, resolves #1159.

Extract required propTypes detection

---

lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

Just a little bug. Fixes #1922. Fixes #1993

Fix fixer for jsx-sort-comp in case of more than 10 props

---

lib/rules/jsx-no-literals.js
tests/lib/rules/jsx-no-literals.js

Basically I did some tweaks to the jsx-no-literals rule to be able to print the node value. :)
Fixes #2007.

Adding option to print node value

---

.gitignore
lib/util/version.js
package.json
tests/fixtures/version/detect-version/node_modules/react/index.js
tests/fixtures/version/detect-version/node_modules/react/package.json
tests/util/version.js

[New] Support "detect" option for React version setting

---

lib/rules/jsx-first-prop-new-line.js
package.json
tests/lib/rules/jsx-first-prop-new-line.js

Not all parsers fill the `name.end` field in the AST structure so relying on it is less robust. 
Ref: https://github.com/babel/babel/issues/6681     
But the `range` syntax is widely supported (babel has a flag). 
I ran into this issue using the `typescript-eslint-parser` which does not add `start` and `end` to the nodes, but has range.
Here is an example to see the difference:
https://astexplorer.net/#/gist/c336be172990d7b467d1ed3dbc1882ee/d312c83cd24626d2e82ba791add48fe061b7cdc0

Use `loc` version of `end`, to handle parsers that don't fill `name.end`.

---

lib/rules/jsx-wrap-multilines.js
tests/lib/rules/jsx-wrap-multilines.js

Fixes #1965. The only interesting question is how the fixer should treat the newlines. I chose to make it add a new line if there was exactly zero after or before the parens. This means:
```
var Hello = createReactClass({
render: function() {
return (<div>
<p>Hello {this.props.name}</p>
</div>
);
}
});
```
Fixes to:
```
var Hello = createReactClass({
render: function() {
return (
<div>
<p>Hello {this.props.name}</p>
</div>
);
}
});
```
----
And:
```
var Hello = createReactClass({
render: function() {
return (<div>
<p>Hello {this.props.name}</p>
</div>
);
}
});
```
Fixes to:
```
var Hello = createReactClass({
render: function() {
return (
<div>
<p>Hello {this.props.name}</p>
</div>
);
}
});
```
----
The alternative would be to make exactly _one_ newline regardless of how many there were …

jsx-wrap-multilines now catches single missing newlines

---

docs/rules/jsx-sort-props.md

It says that `reservedFirst` can be a boolean or an array of strings yet the example shows a mixed array.

Small mistake in the docs of jsx-sort-props

---

lib/rules/forbid-foreign-prop-types.js
tests/lib/rules/forbid-foreign-prop-types.js

Fix @csantos1113 problem in #2023 
The `allowInPropTypes` option can't apply following definition for `propTypes`.
```
const space = () => {};
space.propTypes = {
name: PropTypes.string
};
export default class List extends PureComponent {
static propTypes = {
...space.propTypes, // but I'm getting the warning here!
message: PropTypes.string
}
render() {
return <div>{this.props.message}</div>
}
}
```
Got following node hierarchy when define `propTypes` by each method, `AssignmentExpression` is only contained by the latter.
```
ExperimentalSpreadProperty
ObjectExpression
ClassProperty
```
```
ExperimentalSpreadProperty
ObjectExpression
AssignmentExpression
```

Apply allowInPropTypes option to class property

---

lib/rules/require-default-props.js
tests/lib/rules/require-default-props.js

Fixes: https://github.com/yannickcr/eslint-plugin-react/issues/2063

Change naming from singular defaultProp to plural defaultProps

---

docs/rules/jsx-no-bind.md

The PR removes a controversial and debatable line that is the source of much confusion
See: 
- https://twitter.com/sophiebits/status/1069150849467731968
- https://cdb.reacttraining.com/react-inline-functions-and-performance-bdff784f5578?gi=cfceda6d7a59

Remove debatable statement on perf in jsx-no-bind

---

README.md
lib/rules/boolean-prop-naming.js
lib/rules/forbid-prop-types.js
lib/rules/jsx-sort-default-props.js
lib/rules/sort-prop-types.js
lib/util/defaultProps.js
lib/util/propTypes.js
lib/util/propWrapper.js
tests/util/propWrapper.js

This change is adapting the `propWrapperFunctions` setting to allow for
using objects along side the already present strings. This will help
facilitate adding extra attributes to these objects like for exact prop
functions.
This was initially proposed [here](https://github.com/yannickcr/eslint-plugin-react/pull/1547#issuecomment-345545576).

Change allowed propWrapperFunctions setting values

---

README.md
docs/rules/no-unsafe.md
lib/rules/no-unsafe.js
tests/lib/rules/no-unsafe.js

[The original PR](https://github.com/yannickcr/eslint-plugin-react/pull/2069) has been broken down to 2 parts, the changes related to `no-unsafe` rule have been moved to this PR.
- `no-unsafe` rule has been adjusted to handle all unsafe life-cycle methods including their aliases. Developers who want to avoid using of legacy lifecycle methods can enable it today.
- Instructions on updating components have been adjusted in `no-unsafe` rule to be consistent with React runtime warnings.
- Documentation pages have been updated.
- Corresponding unit tests have been updated/added.

Adjust `no-unsafe` rule to handle all unsafe life-cycle methods

---

lib/rules/no-unused-state.js
tests/lib/rules/no-unused-state.js

Handle functional setState in no-unused-state

---

docs/rules/jsx-indent.md
lib/rules/jsx-indent.js
lib/util/ast.js
tests/lib/rules/jsx-indent.js

Handle JSX attribute indentation in jsx-indent

---

docs/rules/no-array-index-key.md
lib/rules/no-array-index-key.js
tests/lib/rules/no-array-index-key.js

The `no-array-index-key` was not flagging any errors when iterating via `React.Children` methods. This fixes that!
Fixes #2083

Fix: no-array-index-key not working in React.Children methods

---

lib/rules/void-dom-elements-no-children.js
lib/util/Components.js
lib/util/usedPropTypes.js
tests/lib/rules/prop-types.js

This updates the component detection to allow for considering components
wrapped in either React.forwardRef or React.memo.
Resolves #1841. Resolves #2059

Support detecting React.forwardRef/React.memo

---

tests/lib/rules/prop-types.js

Fixes and verifies: https://github.com/yannickcr/eslint-plugin-react/issues/1422

Chore: Add tests for prop-types destructuring

---

tests/lib/rules/display-name.js

See https://github.com/yannickcr/eslint-plugin-react/pull/1089#issuecomment-283423305
Before that pull request an arrow function such as: `() => foo(bar("x"))` would be detected as a component if `createElement` was destructured (`import {createElement} from 'react'`).
This adds a test for display-name that it's ok that a function like that does not need a display name, as it's not a component.

Test false positive component detection for destructured createElement

---

lib/rules/no-typos.js
tests/lib/rules/no-typos.js

Resolves #1721 
Also added some more tests for good measure.
Not sure about the exact message for an ES5 component, but mentioning `static class property` didn't make sense.

Support createClass in no-typos

---

lib/rules/no-unused-state.js
tests/lib/rules/no-unused-state.js

Don't assume `classInfo.aliases` is a set since there are some cases where
it is `null` for a `ClassProperty`.
Fixes #2096

Fix no-unused-state crash

---

lib/util/usedPropTypes.js
tests/lib/rules/prop-types.js

This will prevent triggering on any member expression inside a lifecycle
method. Instead, it will do the naive checking of the node names for
`props`, `nextProps`, and `prevProps` which is already done here.
Resolves #2094

Fix false positives inside lifecycle methods

---

lib/util/Components.js
tests/lib/rules/display-name.js

This will only consider the React `memo`/`forwardRef` wrappers to be components themselves if they are wrapping a `FunctionExpression`/`ArrowFunctionExpression` directly. In the issue code sample, the normal function component will be picked up as a component as usual.
Resolves #2105

Fix display-name false positive for React.memo

---

lib/util/propTypes.js
tests/lib/rules/no-unused-prop-types.js

While testing #2110, I found a bug with `declaredPropTypes` and the `no-unused-prop-types` rule.
The `propTypes` module incorrectly detects function parameters inside a class property as props of the class component, which results in this code being considered a warning:
```jsx
type Props = {
used: string,
}
class Hello extends React.Component<Props> {
renderHelper = ({unused}: {unused: string}) => {
}
render() {
return <div>{this.props.used}</div>;
}
}
```
It thinks that `unused` is an unused prop of `Hello`.
I'm not a 100% if the fix is the correct fix, but I made `markAnnotatedFunctionArgumentsAsDeclared` check if the `node` has a `ClassProperty` ancestor, and if so, bail. I also added a test to `no-unused-prop-types` to check for this.
Having these kinds of class …

Fix issue with propTypes misclassifying props

---

lib/rules/jsx-fragments.js
tests/lib/rules/jsx-fragments.js

[Fix] avoid crashing on self-closing fragments

---

lib/util/propTypes.js
tests/lib/rules/no-unused-prop-types.js

I investigated it a bit more and it turns out #2111 has more instances than just `ClassProperties`. A legit example is JSX render props:
```jsx
type Props = {
used: string,
}
class Hello extends React.Component<Props> {
render() {
return <QueryRenderer
render={
({notAProp}: {notAProp: string}) => <div>{this.props.used}</div>
}
/>;
}
}
```
The `no-unused-prop-types` rule gives a warning that `notAProp` is not used, because it thinks `notAProp` is a prop of `Hello`.
I added two more tests. The problem seems to occur in many cases involving functions being declared inside class bodies. The nice thing is that all of them have a `ClassBody` node as an ancestor so I changed the previous fix to look for `ClassBody` instead, which actually feels more like a proper fix.

Fix propType detection inside class bodies

---

lib/util/Components.js
tests/lib/rules/prop-types.js

In isPragmaComponentWrapper check name of callee object if awailable.
Fixes #2124

Fix isPragmaComponentWrapper

---

lib/rules/no-unused-state.js
tests/lib/rules/no-unused-state.js

Fix no-unused-state rule:
1. When using destruction in `setState` callback.
2. When using state inside `setState` callback.
Fixes #1697
This is my first PR to open source :)

Fix set state callback destructing & state use inside callback

---

docs/rules/no-string-refs.md
lib/rules/no-string-refs.js
tests/lib/rules/no-string-refs.js

This PR aims to fix https://github.com/yannickcr/eslint-plugin-react/issues/2148.
no-string-ref will throw warning when using template literals in string refs.

Added check for template literals in no-string-refs rule

---

README.md

The link to the eslint docs should be enough to clear confusion on where "settings" goes.
Initially I thought I could add the same note to flowVersion, but that config is set to throw if tested for and missing, so there isn't a default value.

Added shared settings info, React version default note fix for #2169

---

CHANGELOG.md
README.md
docs/rules/jsx-props-no-spreading.md
index.js
lib/rules/jsx-props-no-spreading.js
tests/lib/rules/jsx-props-no-spreading.js

This adds a rule to disallow JSX props spreading as it reduces both the readability and maintainability of the code. Fixes #1094.
So, instead of passing props like this:
```
function MyComponent(props) {
return <MySubComponent {...props} />
}
```
This rule will enforce passing props like this:
```
function MyComponent(props) {
return <MySubComponent one_prop={props.one_prop} two_prop={props.two_prop} />
}
```

[new] Add jsx-props-no-spreading rule

---

lib/rules/jsx-sort-default-props.js
tests/lib/rules/jsx-sort-default-props.js

Closes #2178
I thought an option was needed, but instead it was a bug

[jsx-sort-default-props] Bug fix for one case with spread

---

tests/lib/rules/jsx-curly-spacing.js

test(jsx-curly-spacing): test against fixed in the past bug

---

lib/rules/jsx-one-expression-per-line.js
tests/lib/rules/jsx-one-expression-per-line.js

Fix tabs for ´jsx-one-expression-per-line´ rule

---

lib/rules/jsx-curly-brace-presence.js
tests/lib/rules/jsx-curly-brace-presence.js

Fixes #1592
Multi-line template string is no longer considered error.
```javascript
<App prop={`
a
b
`} />
```

[Fix] `jsx-curly-brace-presence`: accept multiline template string

---

lib/rules/no-unknown-property.js
tests/lib/rules/no-unknown-property.js

[Fix]`no-unknown-property`: fix case like `<Foo.bar>`

---

docs/rules/jsx-indent.md
lib/rules/jsx-indent.js
tests/lib/rules/jsx-indent.js

[New] `jsx-indent`: Add `indentLogicalExpressions` option

---

lib/rules/display-name.js
tests/lib/rules/display-name.js

Fixes https://github.com/yannickcr/eslint-plugin-react/issues/2221
RFC --- this is most likely not a good solution.
I've made sure that the component is marked only if the function node is the component itself.

[Fix] `display-name`: fix false negative around nested functions

---

lib/rules/sort-prop-types.js
tests/lib/rules/sort-prop-types.js

Error occurs when some of props has keys declared as numbers. Object keys shouldn't be declared as numbers. Nevertheless, error should not occur.
Fixes #2212.

[Fix] - Fix sorting props with numeric keys

---

lib/rules/require-render-return.js
tests/lib/rules/require-render-return.js

Previously the reported node is the whole component.
Now the reported node is the render method.

[Update]`require-render-return`: more accurate report location

---

lib/util/version.js
tests/fixtures/version/detect-version/node_modules/flow-bin/package.json
tests/util/version.js

not sure why you guys implemented React version detection without doing the same for Flow

implement flow version detection

---

lib/rules/self-closing-comp.js
tests/lib/rules/self-closing-comp.js

Closes #1717
React does not trim JSXText if it is single-line spaces.
In case like `<span>    </span>`, the spaces are left as is.

[Fix]`self-closing-comp`: stop reporting single-line spaces

---

README.md
docs/rules/static-property-placement.md
index.js
lib/rules/display-name.js
lib/rules/static-property-placement.js
lib/util/props.js
tests/lib/rules/static-property-placement.js

This adds a rule discussed in these two issues:
* Fixes #1923
* Fixes #1807
I have based the options on @ljharb suggestions from both issues. This is my first attempt at writing a rule so I expect plenty of feedback. 
* `static public field` (`ClassProperty`)
* `static getter` {`MethodDefinition`)
* `property assignment` (`MemberExpression`)
```
...
"react/static-property-placement": [<enabled>, <string>, {
childContextTypes: <string>,
contextTypes: <string>,
contextType: <string>,
defaultProps: <string>,
displayName: <string>,
propTypes: <string>,
}]
...
```
- Also I have never worked with TypeScript/Flow so I am not sure what (if any) additional changes are needed?
- **This rule only applies to ES6 classes.** 
-- Ignored: Stateless functional components can only ever have a …

[new] add static-property-placement rule

---

lib/util/propTypes.js
tests/lib/rules/prop-types.js

fix(resolveSuperParameterPropsType): add null check

---

docs/rules/boolean-prop-naming.md
lib/rules/boolean-prop-naming.js
tests/lib/rules/boolean-prop-naming.js

Prop names nested inside of `shape` weren't validated. Issue shouldn't occur.

Validate boolean prop names nested deeper

---

docs/rules/prefer-stateless-function.md
lib/rules/prefer-stateless-function.js
tests/lib/rules/prefer-stateless-function.js

Pure components without props are still valid, since they prevent rerendering of component even if parent component is being rerendered.

[Fix] Ignoring pure components without props and context usage

---

lib/rules/jsx-sort-props.js
tests/lib/rules/jsx-sort-props.js

Not all the jsx-prop-sort lints were fixable.
There were cases when existing fix would cause other lints to trigger.
For example, in case when normal props were not sorted but callback functions were in the end(As they are supposed to be), sorting lint fix would mix callbacks props in between the other props.
```
Case:
ignoreCase = false;
callbacksLast = true;
shorthandFirst = false;
shorthandLast = false;
noSortAlphabetically = false;
reservedFirst = false;
--
<div a z onClick=y />
Existing lint fix would transform it to
<div a onClick=y z />
However, this also triggers another lint about callbacksLast.
```
Updated the tests accordingly.

Make all jsx-prop-sort lints fixable

---

lib/util/usedPropTypes.js
tests/lib/rules/prop-types.js

[fix]`prop-types`: fix case with destructuring and default param

---

lib/rules/jsx-props-no-multi-spaces.js
tests/lib/rules/jsx-props-no-multi-spaces.js

```typescript
<Foo<T> bar />
```
**Error:**
Expected only one space between "Foo" and "bar"
Fixes https://github.com/yannickcr/eslint-plugin-react/issues/2181

[fix] `jsx-props-no-multi-spaces`: support generic components (ts)

---

lib/rules/no-render-return-value.js
tests/lib/rules/no-render-return-value.js

This commit likely fixes the performace issue noted in #2259.

[Refactor] `no-render-return-value`: reuse version test result

---

README.md

The link to the [`react/prefer-read-only-props`](https://github.com/yannickcr/eslint-plugin-react/blob/v7.13.0/docs/rules/prefer-read-only-props.md) rule which was added on v7.13.0 is missing in [READEME](https://github.com/yannickcr/eslint-plugin-react/blob/v7.13.0/README.md), so this PR adds just it.
See also [Changelog](https://github.com/yannickcr/eslint-plugin-react/blob/v7.13.0/CHANGELOG.md).

Add missing `react/prefer-read-only-props` link

---

README.md
docs/rules/static-property-placement.md
lib/rules/static-property-placement.js
tests/lib/rules/static-property-placement.js

[fix] `static-property-placement`: fix bug with static property refs inside methods

---

lib/rules/sort-prop-types.js
tests/lib/rules/sort-prop-types.js

Support proptype shape in a variable for sortShapeProp

---

lib/util/makeNoMethodSetStateRule.js
tests/lib/rules/no-did-mount-set-state.js
tests/lib/rules/no-did-update-set-state.js

This fixes #1595, catching this.setState used within cDU/cDM when cDU/cDM is defined as ClassProperties. 
Even though defining cDU/cDM as ClassProperties may not be the smartest thing to do, this rule should still handle it.

no-did-mount-set-state with cDU or cDM as ClassProperties

---

lib/util/usedPropTypes.js

This pr removed code smell in `getPropertyName()` and removed code duplication in the handling of destructuring. The code smell is caused by trying to handle cases like `const {foo} = this.props` in `MemberExpresion` handler. Handling the case in `VariableDeclarator` handler simplified away things.

[Refactor]: simplify utils/usedPropTypes.js

---

CHANGELOG.md
docs/rules/jsx-curly-newline.md
index.js
lib/rules/jsx-curly-newline.js
tests/lib/rules/jsx-curly-newline.js

fixes #1493
This rule is based on eslint core rule [function-paren-newline](https://eslint.org/docs/rules/function-paren-newline). Its options is similar to that of `function-paren-newline`, `array-bracket-newline`,  and `object-curly-newline`. However there is one new option `multiline-lax` (default), which is the same as `multiline` but tolerate cases like
```jsx
<div>
{
foo
}
</div>
```
, that is, single line expressions are allowed to have both newlines.
Separately, since this commit is modified copy of the eslint core rule [function-paren-newline.js](https://github.com/eslint/eslint/blob/9ffdde5a95f45fac0d87a9f47ed42591f6ae42a6/lib/rules/function-paren-newline.js), I need help on how to deal with the license things.

New: jsx-curly-newline rule

---

lib/util/usedPropTypes.js
tests/lib/rules/no-unused-prop-types.js
tests/lib/rules/prop-types.js

Fixes #1422. Fixes #296.
This commit fixes cases like `const {a: {b}} = this.props;`. Nested destructuring are now marked as used **recursively**.

[New]: `prop-types`: handle nested destructuring

---

README.md

[Docs] add `jsx-curly-newline` to README
