docs/rules/prop-types.md, lib/rules/prop-types.js
=> Add annotation to docs for props.children and alike

docs/rules/no-did-update-set-state.md
=> Change `componentDidMount` to `componentDidUpdate`

README.md
Sorting these rules alphabetically will help people find the rules that
they are looking for easier.
=> Sort list of rules in readme

lib/rules/jsx-no-undef.js, tests/lib/rules/jsx-no-undef.js, tests/lib/rules/jsx-uses-vars.js
=> Namespaced JSX fixes

README.md, docs/rules/no-direct-mutation-state.md, index.js, lib/rules/no-direct-mutation-state.js, tests/lib/rules/no-direct-mutation-state.js
Rule to call out direct state mutation.
First eslint rule I have written and am very open to feedback to make it better. Its very simple right now.
=> Add no-direct-mutation-state rule (fixes #133, #201)

tests/lib/rules/prop-types.js
These are the failing test case for #259.
I copy-pasted the tests from #254 but tweaked them to use `this.props` instead of `props`.
=> Failing test case for using this.props in constructor

tests/lib/rules/prefer-es6-class.js
Added a test case for this scenario that I was running into that I thought was valid, but was throwing and error without the ecmaFeatures. This test case it just for future reference if anything is ever changed.
=> added new test case for another scenerio that was valid

lib/rules/jsx-sort-prop-types.js, lib/rules/sort-comp.js
=> Fix crash on incomplete class property declaration

package.json
Fixes this error https://github.com/babel/babel-eslint/issues/243 by updating to latest release https://github.com/babel/babel-eslint/issues/243#issuecomment-178307477
=> update babel-eslint to 5.0.0-beta10

docs/rules/no-unknown-property.md
=> "used to write plain" -> "used to writing plain"

tests/lib/rules/prefer-stateless-function.js
Adds a failing test for my issue #516. I will try to solve this. If you have a fix for this, feel free to continue this PR.
=> Add failing test for #516

lib/rules/require-extension.js
While working on a different rule, I noticed a small typo here and
thought it was worth fixing.
=> Change "extentions" to "extensions" in require-extension

lib/rules/display-name.js, tests/lib/rules/display-name.js
Fixes #590. 
Imho, it is not very common style to define components, but I think it should be fixed.
=> Fix display-name when JSON style is used for defining components

lib/rules/jsx-curly-spacing.js, tests/lib/rules/jsx-curly-spacing.js
Fixes https://github.com/yannickcr/eslint-plugin-react/issues/388 and https://github.com/yannickcr/eslint-plugin-react/issues/211
=> Alternative Rule for `jsx-curly-spacing`

docs/rules/self-closing-comp.md
This came up when reviewing #730
=> Update self-closing-comp doc to show example of a intentional space

lib/rules/jsx-indent.js, tests/lib/rules/jsx-indent.js
=> Fix jsx-indent single line jsx

package.json
The only change is that the license changed.
https://github.com/eslint/doctrine/releases/tag/v2.0.0
=> Update doctrine to 2.0.0

lib/rules/jsx-no-target-blank.js, tests/lib/rules/jsx-no-target-blank.js
=> Fix crash when rel tag is empty

lib/rules/no-find-dom-node.js, tests/lib/rules/no-find-dom-node.js
=> Make no-find-dom-node work correctly with named imports

tests/lib/rules/no-unused-prop-types.js
Just adding the test case from #1309
=> [Tests] `no-unused-prop-types`: add test case

tests/lib/rules/no-unused-prop-types.js
=> `no-unused-prop-types`: adding test cases from #811

tests/lib/rules/no-unused-prop-types.js
=> [no-unused-prop-types] graphql issue #1097

lib/rules/no-unused-prop-types.js, tests/lib/rules/no-unused-prop-types.js
=> [no-unused-prop-types] flow should respect skipShapeProps

lib/rules/boolean-prop-naming.js, tests/lib/rules/boolean-prop-naming.js
=> Fix propTypes wrapper crash in boolean-prop-naming

lib/rules/prop-types.js, tests/lib/rules/prop-types.js
=> [prop types] fix an assignment to prop

lib/rules/boolean-prop-naming.js, tests/lib/rules/boolean-prop-naming.js
Fixed a crash in the boolean-prop-naming rule.
=> Fixes #1369

docs/rules/no-typos.md, lib/rules/no-typos.js, package.json, tests/lib/rules/no-typos.js
=> [no-typo] rule enhancement checking for a correct prop type spelling

tests/lib/rules/no-unused-prop-types.js, tests/lib/rules/prop-types.js
=> [prop-types, no-unused-prop-types] test case

package.json
New dependency has MIT license
=> Update to latest prop-types

lib/rules/destructuring-assignment.js
https://github.com/yannickcr/eslint-plugin-react/pull/1462#discussion_r147326722
I also added a newline which make the diff bigger than it needs to be, but makes the code more readable, IMO
=> Remove duplicate assertion

docs/rules/button-has-type.md
Looks like a copy&pasta error.
Ref #1525
=> Fix docs for button-has-type

docs/rules/no-access-state-in-setstate.md
Minor doc fix in no-access-state-in-set state rule to make it consistent with the others.
=> Minor documentation fix

lib/rules/default-props-match-prop-types.js, lib/rules/forbid-prop-types.js, lib/rules/require-default-props.js, lib/rules/sort-prop-types.js, lib/util/variable.js
I noticed the duplication when working on another rule.
=> Move findVariableByName to variable util

docs/rules/jsx-max-depth.md, index.js, lib/rules/jsx-max-depth.js, tests/lib/rules/jsx-max-depth.js
Originally proposed by @chriswong (https://github.com/yannickcr/eslint-plugin-react/pull/1260)
=> [Rebased] `jsx-max-depth`: validate a specific depth for JSX

docs/rules/jsx-no-literals.md
Make same as other rules.
It will be appreciated if you review it. 😊
=> [Docs] Fix sample config code in "react/jsx-no-literals"

lib/rules/no-deprecated.js, lib/util/version.js, tests/lib/rules/no-deprecated.js
=> Hotfix - fix no-deprecated bug

lib/rules/button-has-type.js, tests/lib/rules/button-has-type.js
=> Account for pragma in button-has-type

tests/lib/rules/jsx-indent.js
=> Add test case for jsx-indent

tests/lib/rules/prop-types.js
=> Additional test case for literals as prop keys in prop-types

CHANGELOG.md
No big deal, just changing to the right contributor
=> Fix changelog "Ignore class properties" contributor

lib/rules/sort-prop-types.js, tests/lib/rules/sort-prop-types.js
=> Fix sort-prop-types string property order

lib/util/makeNoMethodSetStateRule.js
=> Fix noMethodSetState docsUrl's

lib/rules/jsx-max-depth.js, tests/lib/rules/jsx-max-depth.js
=> Fix depth of JSX siblings in a JSXEpressionContainer

lib/util/version.js
=> Link does not end with '.'

lib/rules/jsx-indent.js, tests/lib/rules/jsx-indent.js
=> Prevent crash of jsx-indent rule

lib/util/usedPropTypes.js, tests/lib/rules/prop-types.js
=> [Fix] `prop-types`: Fix false positive on computed member expression

package.json
v15.7 adds the `elementType` propType
=> no-typos: update prop-types

tests/lib/rules/prop-types.js
=> [Tests]`prop-types`: add passing test case about array.length

docs/rules/forbid-prop-types.md
=> Add missing quotes to rule options example

.eslintignore, .gitignore, package.json
=> Change istanbul output directory to ./coverage (default)

lib/rules/no-adjacent-inline-elements.js, tests/lib/rules/no-adjacent-inline-elements.js
=> [Fix] no-adjacent-inline-elements: crash on one child

tests/lib/rules/boolean-prop-naming.js
I created a test to try and debug #2602 but it seems to pass.  Opened a PR so that ticket can potentially be closed.
=> Added test for function invocation of bool #2602

lib/rules/no-unused-state.js, tests/lib/rules/no-unused-state.js
=> [Fix]`no-unused-state`: check for class expression

tests/lib/rules/no-unused-prop-types.js
=> [Test]`no-unused-prop-types`: add test assigning this.props to a variable

lib/util/Components.js, lib/util/isFirstLetterCapitalized.js, lib/util/propTypes.js, tests/lib/rules/no-unused-prop-types.js, tests/util/isFirstLetterCapitalized.js
=> [Fix]: improve component declared props detection

tests/lib/rules/prop-types.js
It is working. Adding test.
Closes #2747
=> [Test]`prop-types`: add test

.eslintrc, lib/rules/destructuring-assignment.js, lib/rules/forbid-foreign-prop-types.js, lib/rules/jsx-indent.js, lib/rules/jsx-max-depth.js, lib/rules/jsx-one-expression-per-line.js, lib/rules/no-set-state.js, lib/rules/no-this-in-sfc.js, lib/rules/no-unknown-property.js, lib/rules/no-unused-state.js, lib/rules/prefer-read-only-props.js, lib/rules/prefer-stateless-function.js, lib/rules/self-closing-comp.js, lib/rules/sort-comp.js, lib/rules/style-prop-object.js, lib/util/propTypes.js, lib/util/usedPropTypes.js
Explicitly wrapping brackets around operators with higher precedence
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
=> [Refactor] cleanup no-mixed-operators warnings

CHANGELOG.md, docs/rules/no-unused-prop-types.md
Adding a new example to resolve #2849.
Also fixing a comment in the same file that got out of sync with its code.
=> [Docs] Add new example to no-unused-prop-types

CHANGELOG.md, docs/rules/jsx-indent.md
=> [Docs] added missing curly braces

CHANGELOG.md, README.md
Fix example trailing commas in json settings.
=> [readme] fix missing trailing commas

CHANGELOG.md, README.md
Documentation about "Adding Shared Settings" is moved by eslint/eslint#13837 and eslint/eslint#14036.
=> [readme] fix broken anchor link

package.json
Updates `eslint-remote-tester` to new major v3.
The breaking changes do not affect this project. The changes mainly reduce some verbose default logging which is also preferred for this project. 
https://github.com/AriPerkkio/eslint-remote-tester/blob/master/CHANGELOG.md#300-2022-06-12
=> [Dev Deps] update `eslint-remote-tester`

CHANGELOG.md, tests/lib/rules/jsx-wrap-multilines.js
More tests covering case from #3545. If passes, then fixes #3545 ?
=> [Tests] `jsx-wrap-multilines`: passing tests
